### ISSUE TITLE
Running docker for non-administrator users on Windows

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/butterfly#142]
This might address the issue for users with standard account. This is important as if the docker runs without administrative privilege then we can use it also for honeybee.
 
https://forums.docker.com/t/running-docker-toolbox-as-standard-user-in-windows-7-issue-workaround/13036

**Comment by mimarilker** [comment]
I have also tried this one, but no success. The docker runs but this time Of container cant run without admin. privileges. This is the most challenging part that I am trying to solve.

**Comment by saket411** [comment]
I had to get IT in my office grant me admin permissions for OpenFOAM, Docker and Git. Then only I was able to run it.

**Comment by mimarilker** [comment]
Yeah I know that saket411, have you reviewed the issues that I opened. I am working to solve it, at the end I will let all you know about it. Just need time, I have re-installed OF, docker and vm for nearly 50 times until now to try possibilities:)

**Comment by mostaphaRoudsari** [comment]
While it doesn't seem to be possible to run docker without Administrative account @mimarilker suggested a solution by changing the compatibility settings for the programs in Windows. It can be done once by an admin and should work fine afterwards.

![image](https://cloud.githubusercontent.com/assets/2915573/21725811/ecd0743c-d407-11e6-87ef-46b659549142.png)

![image](https://cloud.githubusercontent.com/assets/2915573/21725830/04710822-d408-11e6-8fa1-cadb171424a1.png)

**Comment by saket411** [comment]
I cannot run BF after the update. I asked IT to give admin rights and they changed it as mentioned above. 
BF is throwing the same error whatever I do. 
_1. Solution exception:In order to run OpenFOAM using butterfly you must use an admin account or run the program as administrator._

It was working smoothly before.
Pls help!! urgent!

**Comment by saket411** [comment]
Any way I can revert back to old version.

**Comment by mimarilker** [comment]
I have cleaned all the script and ghuser files and used installer.gh file to reinstall butterfly, than it begun to work. You may try this maybe, I think there is sth wrong with replacing older files during update which may stem from even admin. issues:(

**Comment by saket411** [comment]
@**mimarilker** Are you running as the admin yourself or working as another user on the machine.
I cleaned up the scripts folder and ghuser files. Restarted the pc and reinstalled BF. It won't work. Would be great if someone can help. 
@**mostaphaRoudsari** pls assist

**Comment by DambronOlivier** [comment]
@saket411  
I ran into the same issue after updating.
I closed Gh, Rhino and shut down Default through Oracle.
Re-opened OpenFOAM_Start and Rhino both as admin.

**Comment by saket411** [comment]
@**DambronOlivier** Tried. No luck. 
Again, are you the admin yourself? Maybe restarting/reinstalling works if you are the admin. In my case I am unable to work it out.

**Comment by mimarilker** [comment]
I have admin. account, I think there is no problem with the updated runmanager.py, the new lines in the code just shows if the problem stems from admin.privileges issues or I think so.

**Comment by saket411** [comment]
I was able to run it on my personal laptop (as admin). Had to fresh install BF. 
I think for non admin users its not working.

**Comment by mostaphaRoudsari** [comment]
@saket411 this exception `1. Solution exception:In order to run OpenFOAM using butterfly you must use an admin account or run the program as administrator.` has nothing to do with OpenFOAM installation. It simply checks to make see if you are running Rhino with an administrative account. Are you sure that you're running Rhino as an administrator? You need to right click on Rhino logo and then select run as administrator or follow [the above directions](https://github.com/ladybug-analysis-tools/butterfly/issues/142#issuecomment-270950371) to set it up to always run as administrator.

Here is the piece of code that you can use to test if you're an admin user:

```python
import ctypes
print ctypes.windll.shell32.IsUserAnAdmin()
```

**Comment by saket411** [comment]
@**mostaphaRoudsari** 
I am not admin on the pc I am working on. But I asked IT to set rhino run as admin as described in your steps. 
![image](https://cloud.githubusercontent.com/assets/1322619/21767318/62eefc30-d6ae-11e6-932a-835e9bcb6841.png)

**Comment by TheodoreGalanos** [comment]
@saket411 Did that fix things? Were you able to run BF after opening Rhino as admin?

**Comment by saket411** [comment]
Hi @**TheodoreGalanos** 
No it did not work. Since I had to get things going I asked IT to give me full admin rights. Things were normal after that. 
I still think for a non admin user, running rhino as admin with the settings mentioned [here](https://github.com/ladybug-analysis-tools/butterfly/issues/142#issuecomment-270950371) doesn't work. But then, someone else needs to try this and confirm.

**Comment by wangrf123** [comment]
HI @mostaphaRoudsari, so if I am not able to run Rhino as administrator, should I install Docker? Sorry I did not quite get the link you sent. Thanks!

**Comment by mostaphaRoudsari** [comment]
This is not an issue anymore. One can run BlueCFD-Core without admin privileges.
