### ISSUE TITLE
"UNC paths are not supported"

### ISSUE THREAD

**Issue by MaxMarschall** [ladybug-tools/butterfly#158]
An error I have been getting quite often lately is this:
![untitled](https://cloud.githubusercontent.com/assets/23235030/21763557/bb94e7be-d65e-11e6-9645-6dadc54f5843.png)

It seems to happen when Grasshopper has been open for a while without me having worked in it for some time, or when I change a lot in the definition. If I restart Rhino, everything starts working again. It's only a minor inconvenience but maybe someone knows a quick solution or explanation for it?

Cheers,
Max

**Comment by mimarilker** [comment]
when I take this kind of error, I just change the case file name or in worse cases I delete the current case folder.

**Comment by mostaphaRoudsari** [comment]
@MaxMarschall thanks. The next time that it happens can you open the python component and copy the full error message. It's much easier to fix if we know the line number.

**Comment by mostaphaRoudsari** [comment]
also are you running butterfly on a shared network folder? or `\\berlin\...` is a local path and butterfly is adding an extra \ to it that makes it look like a UNC?

**Comment by MaxMarschall** [comment]
Dear @mostaphaRoudsari ,

It's a shared folder. Like I said it usually works fine. I just ran into the error again after I linked new geometry to the definition and changed the boundary conditions. I may have saved the GH file under a new name just before this happened, but I can't remember for sure.

This is the full error message:
```
Runtime error (IOException): '\\berlin80\Performing\Projects\MartinGmbH\MM'

CMD.EXE was started with the above path as the current directory.

UNC paths are not supported.  Defaulting to Windows directory.

	
Traceback:
  line 93, in getShellinit, "C:\Users\mma\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 105, in getContainerId, "C:\Users\mma\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 67, in containerId, "C:\Users\mma\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 228, in _RunManager__command, "C:\Users\mma\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 182, in command, "C:\Users\mma\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 284, in run, "C:\Users\mma\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 667, in command, "C:\Users\mma\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\case.py"
  line 699, in blockMesh, "C:\Users\mma\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\case.py"
  line 46, in script
```

**Comment by TheodoreGalanos** [comment]
@mostaphaRoudsari Is this still an issue? Seems like you were spot on with the UNC path, could it be that this doesn't relate to BF? Or can we make it see if it's a shared folder smh?

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos I would still consider this as butterfly issue/limitation. At least we need to catch this exception and give a more helpful error message.

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
