### ISSUE TITLE
A case study with indoor and outdoor air flows. Issue with the outdoor flow

### ISSUE THREAD

**Issue by frank984** [ladybug-tools/butterfly#193]
Dear @mostaphaRoudsari, @TheodoreGalanos and all,

please consider the following case study:

an office with indoor/outdoor air flow of 2.0 m/s (circular surface as reported in the model).

To consider the outdoor air flow I have modified the outlet boundary component (see attached file).

I have also reduced the end time of the Butterfly_ControlDict from the starting value (5000) of the indoor air flow example file to the value 200 to speed up the analysis.

The result is reported below:
![butterlfy_in-out_example](https://cloud.githubusercontent.com/assets/6491927/23104889/95ce2bec-f6d6-11e6-99b1-9e9e1872c0a3.jpg)

It seems that the outdoor flow is not considered. It's correct? Eventually how can I solve?

As you can see from the model, I have considered also a surface pressure 0 (the door). If I want to consider the case of a closed door, maybe I can consider as o pressure the thin surface space under the door approximatively equal to 70 X 1 cm (in a second attempt I have considered also an height of 2 cm but nothing..). In this case the model does not work because it requires a 0 pressure condition.  How can I solve?

Can you suggest me how to optimize it?

[in-out_airflow.zip](https://github.com/ladybug-analysis-tools/butterfly/files/786078/in-out_airflow.zip)

Regards,
F.

**Comment by TheodoreGalanos** [comment]
Hi @frank984 

My initial suggestion would be that if you wish to evaluate natural ventilation performance in a room like this, you should simply model it as an outdoor case. 

Just put the room in a wind tunnel with the expected inlet velocity at the reference height for your region (see your EPW for that information) or simply change the boundary condition to a fixedValue in your wind tunnel, and let all openings in your room open in the model.

This should generally give better results.

If you wish to use outdoor study results for indoor cases, then the pressure and not velocity is generally used as BC.

Kind regards,
Theodore.

**Comment by frank984** [comment]
Hi @TheodoreGalanos,

first of all thank you for your reply.

If I put the room in a wind tunnel with the expected inlet velocity at the reference height, I can model only the case with an inlet fan and the open door.

But if I want to consider the case with a closed door and two flows (inlet and outlet) on the same wall with the same air velocity and opposite direction, I can't model it as an outdoor case. It's correct? Have you some suggestion regarding this case?

Regards,
Francesco

**Comment by MikkiSeidenschnur** [comment]
Maybe I can help here:

@frank984 what is your experience with CFD in general (beginner, advanced, etc)? And can you try to rephrase the question. Try to tell us: What do you want to accomplish with this simulation, then it will be easier to understand your question. 

Best regards
Mikki

**Comment by MikkiSeidenschnur** [comment]
Thank you for elaborating the issue further @frank984 

1. Try writing the case file to a new name. I've encountered this error before, it seems to happen after I close and reopen the GH files. 
2. I'm not seeing that the outlet flow is nearly zero. What you would need to clarify this is a classic "FluxReport". This would tell you the mass of air coming in/out of your BC's. But right now, all we're seeing is velocity plots, which all depends on the inlet/outlet cross-section that you're removing/adding the air with. As far as I know you cannot report the flux directly within Butterfly, but there is a function to do it in OpenFOAM called "FluxSummary". We discussed this in #177. Until you can report the flow that comes through the openings, I wouldn't know how to help you. 

Can I get you to attach the sample files under the ".../Butterfly" folder for the current case. I would like to see how your Boundary conditions are defined. 

Best regards 
Mikki Seidenschnur

**Comment by frank984** [comment]
> I'm not seeing that the outlet flow is nearly zero. What you would need to clarify this is a classic "FluxReport".

I'm sorry, you're right, I used an inappropriate term. I re-formulate the question: it is correct that, on the right side of the section 1-1' (outlet flow), the speed is so low?

`Can I get you to attach the sample files`

I Have attached the file in the previous post in a zip folder.

**Comment by TheodoreGalanos** [comment]
Hi @frank984 I am going through your file now. It's a bit late here to test thoroughly but I'll share my thoughts below.

Firstly it seems there is some design issues with the surfaces. From what I can see the outlet surface is being used in 2 boundary conditions (one called window and another window holes) at the same time. Additionally, it seems that you haven't split your geometry. While this worked, and it's unclear why, it is generally advised that you assign unique geometries to CFD. I went ahead and split the walls to create actual holes, which are then 'sealed' from the inlet and outlet patches. This creates 3 geometries in total:

1. walls with holes
2. inlet
3. outlet.


Furthermore, the other issue is meshing quality. This is very common. What we always try in meshing is to assign small enough cell sizes in order to capture the smallest detail in our model. In your case, that details is a 0.15m radius inlet and outlet patch. This means that you would need a subdivision of this length, perhaps smth as 0.05m or 0.075m, at maximum in your mesh and especially around the inlet/outlet. At the moment I see you have 0.5m background mesh (i.e. blockMesh) and 2 levels of refinement in the surfaces, which means refined_lengh = (0.5/2)/2 = 0.125m. While smaller than your inlet radius, this cell size is way too big to model the patches properly. And of course the volume mesh, at 0.5m, is even rougher. 

I would suggest setting the background mesh as low as 0.05m on all directions and then assigning 1 level of refinement to the inlet and outlet patches. You can recheck your results after that.

An even easier, but perhaps unrealistic for what you are trying to assess, way to mesh this with sufficient quality would be to enlarge the inlet/outlet patches thereby increasing your minimum required cell size.

Hope this helps!

Kind regards,
Theodore.

**Comment by frank984** [comment]
@MikkiSeidenschnur
> Try writing the case file to a new name.

I have tried and it doesn't work

@TheodoreGalanos 
> Finally, the pRef issue is usually due to boundary conditions in the outlet, specifically undefined pressure. In your case, the outlet is zeroGradient while it should have been fixedValue uniform 0. Are you creating this case with the updated BF components?

I have the updated BF components (v.0.0.03).

> The case will run if you do that change in the p file in your 0 folder (outlet from zeroGradient to type fixedValue; value uniform 0;

If I try to change the p file in the 0 folder from zeroGradient to type fixedValue; value uniform 0; 
![cattura3](https://cloud.githubusercontent.com/assets/6491927/23435484/e81bc9bc-fe07-11e6-96c4-09ae0b419d5f.JPG)
it doesn't work because the Butterfly solution component rewrites every time this file.

@TheodoreGalanos  I have modified the file considering your suggestions. Here below the new version:

[in-out_airflow_r2.zip](https://github.com/ladybug-analysis-tools/butterfly/files/809036/in-out_airflow_r2.zip)

**Comment by TheodoreGalanos** [comment]
Hi @frank984 I think we can look into this and make sure BF isn't assigning these BCs for pressure. Have you maybe added any custom BCs to the file?

There are two more things you can try. The first one is to 'force' the fixedValue boundary condition on the outlet either using the BF custom boundary component or the premade BCs. The second is to edit the p file as you did and then run the case from the Docker terminal. The following will run your case.

```
cd /workingDir/butterfly/your-case-folder-here
simpleFoam
```

Of course the second one is just a workaround for you to see if the case is running, in case the other options don't work. I'll look into this a bit more thoroughly today.

Kind regards,
Theodore.

**Comment by frank984** [comment]
Thanks @TheodoreGalanos for the suggestions.

I have found the error:

As reported in [the previous post](https://github.com/ladybug-analysis-tools/butterfly/issues/193#issuecomment-283057105) 

> I have modified the outlet Boundary component, assuming a uniform velocity value instead of a uniform pressure value.

I have written a stupid error in the last line of this custom component. Now I have changed "bc.FixedIntletBoundaryCondition (U= _velocityVec, T = temperature_)" in "bc.FixedOutletBoundaryCondition (U= _velocityVec, T = temperature_)" and the model seems to work properly.

A question remains: why this big difference in the air velocity between the indoor area closest to the inlet and outlet flows?
![cattura5](https://cloud.githubusercontent.com/assets/6491927/23451403/158d24ec-fe60-11e6-9081-233948d3d8dd.JPG)

Finally, I want now to know if there is a method to refine the mesh only in the area of inlet/outlet flows so as to speed up the calculation.  Because I have seen the Mesh and is very dense also in some areas where it is not necessary. 
![cattura1](https://cloud.githubusercontent.com/assets/6491927/23451421/26f7fd9c-fe60-11e6-85dd-48ce74f13e43.JPG)

Maybe I have to use the Butterfly Refinement Region component, defining a name, geometry and a refmode with the Butterfly Location RefinementMode. There is another example that I can consider in order to know how this component can be applied?

Regards,
Francesco

**Comment by TheodoreGalanos** [comment]
Hi Francesco,

Sorry for the late response. You can increase refinement in any region you want by using the refinement region component.

What you need to do is draw your refinement region in Rhino (the most optimal shape is a box) around the area you want to refine, bring that to a brep in GH, connect that to a refinement region component, apply locationRefinement with the level of refinement you want, and finally connect the refinement region to the create case component. That should apply refinement.

It can take a bit of trial and error after that but that is the main logic.

**Comment by TheodoreGalanos** [comment]
@frank984 I will go ahead and close the issue. Please feel free to reopen if there is still an open question after this.

**Comment by sebacos** [comment]
has some one tried this in 0.0.05? 
I have tried to replicate a similar case, no luck.
FYI: I don't have experience with OpenFoam
Everything works until the solution and while calculating it gives me this error:
![image](https://user-images.githubusercontent.com/45425794/54589110-09319300-4a25-11e9-87f1-0a22f16d338e.png)


Changed the code to:
`try:
    from butterfly.boundarycondition import FixedOutletBoundaryCondition
    from butterfly.fields import FixedValue
except ImportError as e:
    msg = '\nFailed to import butterfly:'
    raise ImportError('{}\n{}'.format(msg, e))

if _velocityVec:
    _velocityVec = FixedValue(str(tuple(_velocityVec)).replace(',', '')) \
                   if _velocityVec \
                   else None

temperature_ = FixedValue(str(temperature_ + 273.15)) if temperature_ \
               else None

outlet_boundary = FixedOutletBoundaryCondition(U=_velocityVec,
                                                   T = temperature_)`

![image](https://user-images.githubusercontent.com/45425794/54588512-852adb80-4a23-11e9-866b-ef300f86e6cb.png)

I've been using the indoor_airflow example a guide.
![image](https://user-images.githubusercontent.com/45425794/54588756-1d28c500-4a24-11e9-8aef-4882142b710c.png)

**Comment by mostaphaRoudsari** [comment]
If the solution runs fine that error can be neglected. It can't find the error file for simplefoam possibly because there has been no errors to generate the file. If that is not the case please post the issue on the forum or open a new issue here.
