### ISSUE TITLE
Dynamo HBZones extra input needed

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/butterfly#205]
@mostaphaRoudsari  I am experiencing problem with getting required,
Would be possible to get to your HBZones apart from polylines and zones also Elements ID, I think same to Zones would be good to get Room/Space object
Different nodes show this in a different way, so I guess we could replicate yours and display with duplicate element ID so per polygon is displayed.

Also, can you add Doors to be recognised, currently there are only windows.

![image](https://cloud.githubusercontent.com/assets/14005893/23831354/5b1be538-0717-11e7-8f5e-dc70d2fddcec.png)

![image](https://cloud.githubusercontent.com/assets/14005893/23831425/cc460332-0718-11e7-9a1d-1052d87baeee.png)

**Comment by mostaphaRoudsari** [comment]
@mdengusiak, The elements are there and can be easily exposed. You already have the room element Id which is the zone ID. Is this what you need?

**Comment by mdengusiak** [comment]
Yes, Please expose them both as elements so I can get parameter value by name and import all design value for boundary etc this I got working, just can not find same order to polylines

**Comment by mostaphaRoudsari** [comment]
@mdengusiak I added the output that you asked for. Download the new honeybee from package manager!

![image](https://cloud.githubusercontent.com/assets/2915573/23841249/57ede33c-0782-11e7-9c5f-f27ec5942b20.png)
