### ISSUE TITLE
Point is not inside the mesh or on a face or edge.

### ISSUE THREAD

**Issue by Lily-s** [ladybug-tools/butterfly#208]
Hi,

I tried the outdoor airflow analysis. However, I kept receiving this error:
 
```
"1. Solution exception:
 --> snappyHexMesh Failed!
--> FOAM FATAL ERROR: 
Point (15.72323 63.68281 10.59472) is not inside the mesh or on a face or edge.
Bounding box of the mesh:(-51.62151 5.651228 0) (3.81664 88.9563 10.75654)

    From function static Foam::labelList Foam::refinementParameters::findCells(bool, const Foam::polyMesh&, const pointField&)
    in file snappyHexMeshDriver/refinementParameters/refinementParameters.C at line 206.
FOAM exiting"
```

It doesn't happen when I used the default breps. This is the files that I used.
![screen](https://cloud.githubusercontent.com/assets/26450451/23980994/696cfa44-0a3e-11e7-8f03-cb055a314478.jpg)

How can I solve this?

Thank you!!

Cheers,
Lily

**Comment by TheodoreGalanos** [comment]
Hi @Lily-s 

OF is generally very explicit on error reporting. In this instance it is telling you that the locationInMesh input is outside the bounding box of the Wind Tunnel.

An easy way to get an automatic location in mesh from your model is to connect a bounding box component on the output of the Wind Tunnel component, right-click and press union box, then connect the output of that to a volume GH component. The point output can then be used as an input to your case.

![example](https://cloud.githubusercontent.com/assets/13436572/23981195/a937034e-0a3f-11e7-8752-0ca587d4aac9.PNG)

Hope this helps.

Kind regards,
Theodore.

**Comment by Lily-s** [comment]
Hi @TheodoreGalanos ,

Thank you for your help.
I encountered another error,  some of the values at specific points are way higher compare to other points. 
![capture](https://cloud.githubusercontent.com/assets/26450451/23984102/acedbac4-0a52-11e7-9660-56d0bfffd7a6.PNG)

Do you know what is the cause of this problem?

Thanks!!

Cheers,
Lily

**Comment by TheodoreGalanos** [comment]
Hi @Lily-s this is usually an error that happens when the probe point is either near or outside the mesh, either on the edges of the mesh or very close to a Temperature. You can choose to ignore these points with a check (e.g. get rid anything above 1000). 

The more permanent solution, if you are using a surface to generate your mesh points that you then plug in to the probe component, is to  scale the surface slightly so that it is at least 1xd away from the edge, where d is your blockMesh cell size.

Kind regards,
Theodore.

**Comment by Lily-s** [comment]
Hi @TheodoreGalanos ,

Thanks! It works! I used the check approach (ignore the points below above 1000)!
May I know what does it means when the solution doesn't converge after 561 (default settings)?

Cheers,
Lily

**Comment by TheodoreGalanos** [comment]
Hi @Lily-s Usually openfoam will tell you the opposite, something like "your solution has converged after 561 iterations". If you have that then this means your results are within the accuracy you requested (i.e. residual error).

If you mean that after 561 iterations it is still working then this means the opposite that it has not reached the residual errors requested. Generally, 561 iterations is considerably low to be considered converged, so I would suggest you just let it run a few thousand (3k is a good first number).

Kind regards,
Theodore.

**Comment by Lily-s** [comment]
Hi @TheodoreGalanos !

Okay, I got it now.
Thank you so much!

Cheers,
Lily

**Comment by TheodoreGalanos** [comment]
Hi @Lily-s I'm glad the problem was resolved! Have fun with Butterfly!

**Comment by mostaphaRoudsari** [comment]
@Lily-s one quick question. What was the units in your model? and which version of Butterfly are you using? I can probably check your file but it would be much easier if you can tell me the settings. Thanks.

**Comment by Lily-s** [comment]
Hi @mostaphaRoudsari .

It is in metres.
I'm using butterfly version 0.0.03.

Cheers,
Lily

**Comment by Lily-s** [comment]
Hi @TheodoreGalanos !

I have another question to ask,
I am trying to stimulate the wind condition in a park with many trees and shrubs around.
Do you think by changing the landscape parameter as 8, is accurate enough? Or Would it better if I model the trees?

Thanks!

Cheers,
lily

**Comment by thinklikeanarchitect** [comment]
I strongly advise you to model the trees, check this article...
[Including trees in the numerical simulations.pdf](https://github.com/ladybug-tools/butterfly/files/857296/Including.trees.in.the.numerical.simulations.pdf)

**Comment by TheodoreGalanos** [comment]
@Lily-s We are aiming to add the porosity solver in our next release, see #95 for more information.

as @thinklikeanarchitect mentioned the impact of landscape is too specific to be covered with the ground roughness parameter. The porosity solver is the best trade-off between quality of results and computational demand of the model. In the porosity solver you don't really mesh the trees but assign porous properties to areas (usually a sphere representing the canopy).

My way of deriving these properties is to create a decoupled model of a detailed tree geometry into which I blow different wind velocities. I would then calculate pressure differences before and after and derive the coefficients required for the porosity solver (ofc even this misses out tree and leaf movement, actual geometry, etc). I have been doing this for assessment of facade systems and other geometrical details with some success.

On the other hand, you can also follow a trial and error approach. If for example some rule of thumb tells you that this tree should slow down wind by 20%, you can have a porosity model and adjust the parameters until you get that decrease in wind velocity.

Hope this helps. When I get a bit of time I'll upload a case including landscape assessment.

Kind regards,
Theodore.

**Comment by thinklikeanarchitect** [comment]
Thanks for the detailed reply Theodore. As you said the best economical solution is porosity option, actually as we know simulation means achieving most similar realistic model. However if there is no problem on computer resources 3d modelling approach can be used for simple cases. On the other hand as to porosity, an example file would be great and most of the users around me asking about it.

**Comment by Lily-s** [comment]
Porosity solver seems great. I've tried to model the trees, but the site is too complex to do 3d modelling approach. The case file will be extremely helpful and I'm looking forward to your next release!
Thank you!

Regards,
Lily

**Comment by thinklikeanarchitect** [comment]
Actually its not a solver, I think you can easily find porosity values of different tree species in literature with a rough research. Also the article that I uploaded is very helpul to see the effect of different trees. So if you re in a hurry, make research to find these values or use the method of Theodore that only model one tree and see the losses in pressure, thats it.

**Comment by Lily-s** [comment]
I do understand the concept behind it (find porosity value through literature or model one tree to see the impact), but I am not sure how to assign the porosity values of the trees in butterfly. Is there resources where I could learn how to do it?

Thank you!

**Comment by TheodoreGalanos** [comment]
@Lily-s At the moment there is no way to assign this through BF, as i mentioned it is a planned feature for upcoming releases.

I will probably get some time in the weekend to share an example of how this works in OF, will try to upload it here.

Kind regards,
Theodore.
