### ISSUE TITLE
Increasing refinement level yields different results 

### ISSUE THREAD

**Issue by saket411** [ladybug-tools/butterfly#211]
Hello all,

It might sound weird but for a particular outdoor run that I am doing, by changing the refinement levels from 1 or 2 to 3 changes the wind flow pattern drastically. I was doing a verification run with bf on a old project simulated in ansys. 

![l_e4c tmp](https://cloud.githubusercontent.com/assets/1322619/24102248/46ddf688-0db6-11e7-8b56-5ee35d8aace4.PNG)
L - ref lvl 3, R - ref lvl 2
The ansys results show turbulence similar to right side in the image above

![l_2f6f tmp](https://cloud.githubusercontent.com/assets/1322619/24103325/e1e286e6-0db9-11e7-803b-5d9d814c8493.PNG)
Comparision of ref lvl 2 and ansys results.

![rerun_1](https://cloud.githubusercontent.com/assets/1322619/24102491/244b70c2-0db7-11e7-9d56-a4caf1fbedac.JPG)
Comparison of ref lvl 3 and ansys results.

I even changed the cell size in bf and rerun the case with ref lvl 1, 2 and 3 and observed the same pattern. 1 and 2 look similar to ansys, 3 looks totally different, wind goes around the building instead of creating a downdraft.

I presume I am doing something wrong somewhere but still, just changing the ref level should not have such effect irrespective of the meshing. I changed the file name each time I did a rerun/change in ref lvl, tested on two different machines as well, problem still persists. 

ref lvl 2 ~6M cells, ref lvl 3 ~18M cells, ref lvl 4 went out of memory.

Because of confidential reasons I cannot share the file but I will try to perform a simplified test case (which takes less time to run) with similar geometry and see if the pattern persists. If it does, I will upload the model and the script.

I would really appreciate if someone has any suggestions/comments as to what might be the source of such error.

Thank you for your time.

Regards
Saket

**Comment by thinklikeanarchitect** [comment]
You have confronted with mesh independency for the first time:)

I think its a normal situation, I have always done mesh independency studies as to get stabilisation in results. Otherwise your results will be depend on your mesh settings directly.

**Comment by saket411** [comment]
@**thinklikeanarchitect** Thank you for the prompt reply. 
I read briefly about [mesh independency](https://www.quora.com/What-is-a-mesh-independent-solution/answer/Ssheshan-Pugazhendhi-1) just now.
So in your experience how does one make sure that the results are correct. Say I did not have the ansys results for this case. How am I suppose to deduce which of the two patterns (w or w/o downdraft) is the correct one?
As per my understanding, the meshing has to be done (by hit and trial or following the rules of thumb) such that the wind pattern remains more or less the same irrespective of the ref lvl.

Thanks!!

**Comment by TheodoreGalanos** [comment]
@saket411 Yes that is correct. Usually you need around three meshes at different qualities to assure mesh independency.

If the results change by a large margin then you increase quality thresholds I believe.

Additionally, in your comparisons you should make sure you are using the same case setup in both models. Afaik, Fluent has a different wall boundary treatment and applies a wall boundary to the ground that we haven't introduced in BF. Additionally, you should check the solvers used, solver accuracy, and if you are using 1st or 2nd order schemes.

Kind regards,
Theodore.

**Comment by thinklikeanarchitect** [comment]
Hi Saket, there is no easy way to achieve mesh independency, however you may try to increase ref.levels step by step until to see minor changes in the results, thats it. In further cases, you will gain experience on this:)

**Comment by saket411** [comment]
@**thinklikeanarchitect** @**TheodoreGalanos** Thank you very much for your input. Really appreciate it. 

I understand that the case setup has to be similar in order to compare ansys and bf results. At the moment the motto of this run was to demonstrate my piers that BF can yield similar results to ansys. I will redefine the grading and cell sizes and see if things get resolved. 

If I come across such issues in future how do I deal with it? I understand its highly case dependent but some basic guidelines would really help beginners like me.

Thanks all for your valuable input.

**Comment by TheodoreGalanos** [comment]
@saket411 Looking at your example pictures, I think you might have refined the area around the building too abruptly (I can tell there's a big difference by the number of arrows near that tower). I would start simple. Only refine surfaces in both software and play with the background mesh size accordingly. Region refinement can happen at later iterations.

For helpful references, I think the Urban CFD best practice guidelines developed by Franke et al. is an excellent place to start ( see http://theairshed.com/pdf/COST%20732%20Best%20Practice%20Guideline%20May%202007.pdf).

Some of my own rules of thumb for outdoor cases are:

- cell size for far field: 5-10m
- cell size around whole urban context: 2m
- cell size near area of interest: ~1m
- cell size inside buildings (if modelled): ~0.1m
- cell size (Z direction) for the first 10m: 1m (grading=1)
- cell size (Z direction) for 10m-Hmax: maximum 3-5m  (use gradient to reduce cell count)
- always use gradient meshing to increase quality near the context without increasing cell count, keep maximum jumps between cells below 1.2x

Hope this helps.


Kind regards,
Theodore.

**Comment by saket411** [comment]
Thank you very much @**TheodoreGalanos** for the guidelines.
I should avoid abrupt refinement even if it is a test run and always make it a practice to follow the guidelines. I was wondering if it is possible to have multiple refinement boxes in the same model.

Heartiest Congratulations on the first release of Butterfly!!!

**Comment by TheodoreGalanos** [comment]
@saket411 you can indeed have as many refinement zones as you want in OF and they can be of any shape.

I STRONGLY suggest you only use rectangle boxes that are parallel to the wind flow to avoid meshing problems. Also, refinement regions in refinement regions (to progressively refine smaller zones inside larger areas) can usually cause problems with snapping the mesh. In these cases using the distance mode of a single refinement zone might be easier.

Kind regards,
Theodore.
