### ISSUE TITLE
Solution Parameters Error

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/butterfly#214]
Hi,
I got this running before and now got this warning when updated Butterfly,

![image](https://cloud.githubusercontent.com/assets/14005893/24530850/abdd6980-15ac-11e7-844d-e39c4e1d2ce9.png)

![image](https://cloud.githubusercontent.com/assets/14005893/24530845/9c8d1ac0-15ac-11e7-91b1-cb5a9ee59c43.png)

**Comment by mostaphaRoudsari** [comment]
Hello @mdengusiak! Based on the error Butterfly fails to parse the dict. Check the controlDict file and see what's going wrong. An easy fix is to rewrite `controlDict`.

**Comment by mdengusiak** [comment]
File looks 

/*--------------------------------*- C++ -*----------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  v1612+                                |
|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
/* Butterfly 0.0.4                https://github.com/ladybug-tools/butterfly *\
\*---------------------------------------------------------------------------*/
FoamFile
{
	version		4.0;
	format		ascii;
	class		dictionary;
	location	"system";
	object		controlDict;
}

application		simpleFoam;

startFrom		latestTime;

startTime		0;

stopAt		endTime;

endTime		1000;

deltaT		1;

writeControl		timeStep;

writeInterval		100;

purgeWrite		0;

writeFormat		ascii;

writePrecision		7;

writeCompression		off;

timeFormat		general;

timePrecision		6;

runTimeModifiable		true;

functions{}


I will try to delete folder and start again  but I think I did it before,

**Comment by mdengusiak** [comment]
@mostaphaRoudsari  I tested and still the same, I can see folder is re-created with same file and values and same error

**Comment by mdengusiak** [comment]
OK, I removed a node and added new and it worked now.
this step is working,
it is not running but I guess should log new issue as seperate

![image](https://cloud.githubusercontent.com/assets/14005893/24627732/d5ee1e0a-18ad-11e7-9e44-08db52942cf7.png)
