### ISSUE TITLE
Auto-calculate total number of cells based on blockMesh size

### ISSUE THREAD

**Issue by TheodoreGalanos** [ladybug-tools/butterfly#215]
I think this might be marginally useful and a good safety valve for new users.

We can either do it at the blockMesh component or at the create Windtunnel/case components if the mesh properties are set there. Total number of cells in the blockMesh: 

`x_number_of_cells * y_number_of_cells * z_number_of_cells`

Regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
This is already there but we just need to expose it. Do you think as this as an output of `blockMesh` component itself? The challenge to do it beforehand is that the value can change based on `_cellSizeXYZ_`.

**Comment by TheodoreGalanos** [comment]
Yes I think it's fine to do it in the blockMesh. It's mostly a heads up to the user in case they put some very small value that leads to a very large mesh.

**Comment by mostaphaRoudsari** [comment]
Done!

![image](https://user-images.githubusercontent.com/2915573/53279712-f73c2900-36e0-11e9-8e3d-64a57feeafb2.png)
