### ISSUE TITLE
Creators update for windows 10

### ISSUE THREAD

**Issue by MikkiSeidenschnur** [ladybug-tools/butterfly#222]
Hi everyone

Just an FYI - If you install the update to windows 10 "Creators update" going from "Anniversary update" you will have issues running VirtualBox version that goes with the standard OpenFOAM installation package. Make sure to update VirtualBox [here](http://download.virtualbox.org/virtualbox/5.1.18/VirtualBox-5.1.18-114002-Win.exe)  (version 5.1.18). Just run everything with standard settings and you should be golden. 

It seems to be a standard issue with the newest windows update and virtual box, but don't know if I'm the only using an older version of VirtualBox. You may go ahead and close this issue, just thought it'd be good to inform people.

Best regards
Mikki Seidenschnur

**Comment by mostaphaRoudsari** [comment]
Thanks @MikkiSeidenschnur! I added OpenFOAM installation issues label to this. Hopefully it makes it easier to find. Cheers.
