### ISSUE TITLE
MeshParams "SimpleGrading" object has no attribute 'X'"

### ISSUE THREAD

**Issue by MikkiSeidenschnur** [ladybug-tools/butterfly#223]
Just sitting with a minor issue, don't know if this is a version thing, but when I'm trying make a multigrading with the segment grading tools I get this error: 

0. Runtime error (MissingMemberException): 'SimpleGrading' object has no attribute 'X'
1. Traceback:
  line 42, in script
![ms_meshparams_v1](https://cloud.githubusercontent.com/assets/20814326/25089916/bab94abe-2380-11e7-895d-215b1d7daa74.PNG)

When I look at the script at version 0.0.4 in a python module for meshParams I get the following code:

""" create blockMeshDict based on BBox """
`if _gradXYZ_:
    _gradXYZ_ = _gradXYZ_.X, _gradXYZ_.Y, _gradXYZ_.Z

meshParams = MeshingParameters(
    _cellSizeXYZ_, _gradXYZ_, _locationInMesh_, _globRefineLevel_)`

Anyways, I just remove the part with 
`if _gradXYZ_:
    _gradXYZ_ = _gradXYZ_.X, _gradXYZ_.Y, _gradXYZ_.Z`

And all of a sudden I have no issue anymore, and it takes the simplegrading no problem. Don't know whether I have some version issues of what it is, just wanted to report it

Best regards
Mikki Seidenschnur

**Comment by MikkiSeidenschnur** [comment]
Sorry about the format of the code, can't really get it to work. Hope it's understandable

**Comment by mostaphaRoudsari** [comment]
Hi @MikkiSeidenschnur, [This is already fixed](https://github.com/ladybug-tools/butterfly-plus/commit/bbaae1570f5153452f340f2c3ae49c4cd6873747#diff-4ace9607c93a065ab237bf1f04442173) but I haven't updated the component in the example file. Try to insert a new component from butterfly tab.

**Comment by MikkiSeidenschnur** [comment]
@mostaphaRoudsari Alright, thank you for checking in. I must not have the newest update of Butterfly
