### ISSUE TITLE
Running butterfly on cluster

### ISSUE THREAD

**Issue by saket411** [ladybug-tools/butterfly#224]
Hello all,

Its not an issue but more of a how to do or feature request. I want to ask if we can use butterfly to log a simulation on a remote machine.

Any input will help.
Thank you very much!!

Regards
Saket

**Comment by TheodoreGalanos** [comment]
Hi @saket411 This is not currently available within Butterfly but it is a readily available option for OF itself.

I am not sure if this works in Windows/Docker type of installation, but in Linux you can use a machine file to identify the IPs of the computers in question, along with the cores that they will be using, and distribute your case like that.

However, if you do not have **_high_** bandwith transfer (typical 10gb LAN or w/e doesn't cut it, probably need fiber to see proper speed) in your network I would recommend you just batch create cases and run each case in a different machine.

Kind regards,
Theodore.

**Comment by saket411** [comment]
Thanks for the detailed reply @**TheodoreGalanos** 
I was hoping I can push BF simulations on the cluster. Not so easy I guess.

Will resort to using OpenFOAM on linux and try to push it from there. 

Thanks!!
