### ISSUE TITLE
Error: failed to start containers: of_plus_1612

### ISSUE THREAD

**Issue by L-Thomes** [ladybug-tools/butterfly#225]
Hello,
I'm trying to install OpenFOAM and I'm having some errors according to the following images. Can anybody help me?
![capturar1](https://cloud.githubusercontent.com/assets/28121916/25530051/2558eb9a-2bfb-11e7-826c-ad96689129ec.PNG)
![capturar2](https://cloud.githubusercontent.com/assets/28121916/25530052/255b2a36-2bfb-11e7-8483-63ae9166b390.PNG)

Thanks

**Comment by mostaphaRoudsari** [comment]
Hi @L-Thomes. The username has a white space. See this [one](https://github.com/ladybug-tools/butterfly/issues/194).
