### ISSUE TITLE
Windows 7, Installation issue, VM

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/butterfly#227]
Hi,

I installed Open foam on my Windows 7 machine,

I run VM as admin, then openfoam as admin,
I can see all running...then when I start external wind example in step 2 

fter while is disconnecting, closing  and got this VM
any idea why?

![image](https://cloud.githubusercontent.com/assets/14005893/25568419/6f3b279a-2dfa-11e7-9c11-ac08b7f2a76e.png)

![image](https://cloud.githubusercontent.com/assets/14005893/25568430/accb567a-2dfa-11e7-9a61-e430868054a1.png)

I run openfoam again and can see this it must be to do with not correctly running and not have access this powershell file... is there any chance to get it running ?

![image](https://cloud.githubusercontent.com/assets/14005893/25568501/0c0ce2d8-2dfc-11e7-825c-f4e50a240149.png)

**Comment by mostaphaRoudsari** [comment]
The solution was to [remove the default](https://github.com/docker/toolbox/issues/453#issuecomment-199250953) and [load it back afterwards](https://github.com/ladybug-tools/butterfly/wiki/Windows-10-Installation-Notes#installing-openfoam-on-a-pc-using-windows-10).

Also if you're using VPN turn off the VPN, and see if that will solve the issue.
