### ISSUE TITLE
Windows 10, indoor case, Cannot find patchField entry for boundingbox

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/butterfly#228]
Hi,

I set up indoor case and all seems to be well set up but struggling with running my case,
what is patchField entry?

My simpleFoam.err says:

```
--> FOAM FATAL IO ERROR: 
Cannot find patchField entry for boundingbox

file: /home/ofuser/workingDir/butterfly/Revit_study1_Office_Simple_00_2/0/p.boundaryField from line 29 to line 45.   

    From function void Foam::GeometricField<Type, PatchField, GeoMesh>::Boundary::readField(const  
 Foam::DimensionedField<TypeR, GeoMesh>&, const Foam::dictionary&) [with Type = double; PatchField = Foam::fvPatchField; GeoMesh = Foam::volMesh]
    in file /home/buzz2/pawan/OpenFOAM/OpenFOAM-v1612+/src/OpenFOAM/lnInclude/GeometricBoundaryField.C at line 191.
```

FOAM exiting

![image](https://cloud.githubusercontent.com/assets/14005893/25568786/ea14af9c-2e02-11e7-945b-c872a03b9074.png)

![image](https://cloud.githubusercontent.com/assets/14005893/25568793/13683b52-2e03-11e7-9f8e-cb8966f313a4.png)

**Comment by mdengusiak** [comment]
Is it sth to do with how windows are meshed?

![image](https://cloud.githubusercontent.com/assets/14005893/25568847/24b70c8e-2e04-11e7-8b4f-a47a3b986806.png)

![image](https://cloud.githubusercontent.com/assets/14005893/25568856/464c8ffe-2e04-11e7-9d7a-45ad40e1c612.png)

**Comment by TheodoreGalanos** [comment]
Hi @mdengusiak 

This is always an issue of meshing. In fact, the boundingbox is the name we gave to the artificial background mesh that is always created around a closed geometry (i.e. a room) in indoor studies. This is to give SHM something to work with for meshing. 

I remember this being an issue in older versions but perhaps it might still be on in Dynamo. I can see, I think, that the geometries are architectural, meaning polysurfaces for walls. Make sure that there is no gap between them. If there is a gap, which is 99% what happened here, then SHM will mesh inside the and outside the room keeping the background mesh patch called boundingbox. If your geometry is completely closed and your locationInMesh is inside it then boundingbox will go away.

Another very quick solution you can try, that might work depending on how your geometry is configured, is to go to  /case/constant/polyMesh, open the boundary dictionary, delete the boundingbox patch, and change the number of patches at the top to one less than it is (it's a sole number right before the patches block starts. You can then try running the case.

Hope this helps.

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
This is always because the mesh has touched the boundingbox that is created by butterfly. It can happen in 2 cases:

1. The `locationInMesh` is set outside the room. In that case the mesh will be generated between the room and the boundingbox. In this case you need to set the location for `locationInMesh`.

2. The geometry is not closed and so `snappyHexMesh` generates the mesh for the whole domain including the boundingbox. In this case you need to revisit the quality of the geometry.

**Comment by MikkiSeidenschnur** [comment]
Just a note on this:

If you're setting the "expandBlockMesh" to "false", ("True" is default) you have issues with this generated boundingBox. In my knowledge I tend to have more issues when setting the "expandBlockMesh". 

And the error is the same as the original mentioned in this case. 

Best regards
Mikki Seidenschnur
