### ISSUE TITLE
error Visualising case, Dynamo, Windows 10

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/butterfly#230]
Hi,

I could simulate case but I am struggling to visualise results vector,
Any idea how to get it running?

![image](https://cloud.githubusercontent.com/assets/14005893/25614377/9a3c8ba2-2f29-11e7-8d17-0b7ade64f84c.png)

**Comment by mostaphaRoudsari** [comment]
This was happening because there was no results in the folder. For the future reference OpenFOAM write the results to the folder based on `writeIntervals` input. For instance if the value is set to 100, It will save the results to folder for Time = 100, 200 and so on.
