### ISSUE TITLE
#231 How to adjust the numerical factors?

### ISSUE THREAD

**Issue by Elarqitecto68** [ladybug-tools/butterfly#231]
Hi, is there any tutorial for the numerical adjusments and basic aerodynamic rules which define the needed numbers in the algorithm? 
In fact when I replace the breps defined in the butterfly samples with new ones, I have problem running the algorithm and I'm not that much familiar with the numerical adjustments.
could you possibly help me find the right way on this case?

**Comment by TheodoreGalanos** [comment]
Hi @Elarqitecto68 Can you be a bit more specific as to which values? Do you mean the values in the numerical schemes (fvSchemes)?

The best place to start is always the openfoam user guide: https://cfd.direct/openfoam/user-guide/

**Comment by Elarqitecto68** [comment]
Hi @TheodoreGalanos 
When I run the butterfly sample entitled outdoor airflow, I see the result in the viewport, but as soon as I replace the breps with other ones even in the approximately same dimensions, It'll have no solution. I thought that it may be related to the refine level number, but again I didn't get any result from the analysis. 
You know I'm trying simple examples, in order to learn how step by step it could become complicated, so that I could enter my project case and make a simulation on it, but even on the similar objects, it doesn't work properly. 
Is there anything I forgot to do in the brep replacement?
I'll be really glad having your comments.

**Comment by Elarqitecto68** [comment]
![img_20170503_234740](https://cloud.githubusercontent.com/assets/28222015/25677403/105e7ca0-305b-11e7-809e-bbb084cafa10.jpg)

**Comment by Elarqitecto68** [comment]
![img_20170503_234742](https://cloud.githubusercontent.com/assets/28222015/25677432/2c1d69f6-305b-11e7-9a57-d4fa63c26b94.jpg)

**Comment by DambronOlivier** [comment]
Hi @Elarqitecto68 ,

the mesh generated from blockmesh + snappyhexmesh is the computational domain holding a certain number of cells.
The values of the fields U, p, etc are calculated for each cells.
Butterfly allows to display a projection of the calculated values onto the test surface for which you have set the grid size. If that test surface happens to be overlapping with geometries then the location of the probes are not found. 
Make sure that your units are in meters in Rhino and also that your test surface is either split, trimmed, or booleandifferenced with the geometries. To be safe, once you have trimmed your test surface, you should offset the contour of the surface of a distance of at least the grid size.

Additionally it is important to note that openfoam considers to mesh the side of the computationaldomain+geometries that is marked by a point as the locationinMesh input of the snappy hex mesh component. Please set a point that is within your computational domain and outside any geometry. I usually make use of the Volume function in grasshopper to obtain the center of the bounding box of the geometries which I move out of the geometries if needed.

I hope this makes sense, good luck and have fun.

Olivier

**Comment by Elarqitecto68** [comment]
Hi, @DambronOlivier 
I think this will work, I'll check it.
Thanks alot.

**Comment by Elarqitecto68** [comment]
Hi, @DambronOlivier 
It worked, the problem was solved by making an offset on the contour.
Thanks alot.
![431838999_46841](https://cloud.githubusercontent.com/assets/28222015/25692574/ff9ac672-30b8-11e7-8548-23948af32636.jpg)

**Comment by TheodoreGalanos** [comment]
That is excellent! Glad to hear it's fixed. This is something that comes up a lot and I will try to include in future videos / tutorials for BF.

Thanks @DambronOlivier for your inputs.

Kind regards,
Theodore.
