### ISSUE TITLE
 swak4Foam installation problem in Windows (Allwmake, /bin/bash^M)

### ISSUE THREAD

**Issue by L-Thomes** [ladybug-tools/butterfly#234]
Hello,
I'm using OpenFoam for Windows and I'm having some trouble with the swak4Foam installation.
First of all, I used the git command

_git clone https://github.com/Unofficial-Extend...-swak4Foam.git swak4Foam_ 

saving the swak4Foam files in the _workingDir_ folder (C:\Users\adm).
Then, the next step would be to go into swak4Foam's main source folder and use the command

_./Allwmake > log.make 2>&1_

That's the problem. The first time I did this, the following error message came up:

_bash: ./Allwmake: /bin/bash^M: bad interpreter: No such file or directory_

Then I found in the internet that I would have to convert the Allwmake file to UNIX. So I did so, but a new error message appeared:

_Previously compiled for OpenFOAM v1612+
No file 'swakConfiguration'. Python etc won't work. See README for details
Try 'ln -s swakConfiguration.automatic swakConfiguration' for automatic configuration. BEWARE: this does not work on some systems
theFiles.sh: line 2: 
: command not found
theFiles.sh: line 18: 
: command not found
theFiles.sh: line 41: syntax error: unexpected end of file
Checking swak4Foam-version and generating file
/usr/bin/env: python
: No such file or directory
/opt/OpenFOAM/OpenFOAM-v1612+/wmake/wmake: ./Allwmake: /bin/bash^M: bad interpreter: No such file or directory

Requirements for Library not satisfied. I see no sense in going on
Check the README before you go on to ask. And search: Most likely your problem occured to 5 other people before and has been solved on the MessageBoard_

Can anybody help me?

Thanks in advance

**Comment by mostaphaRoudsari** [comment]
@L-Thomes this is the wrong repository to send this question. Try https://bitbucket.org/bgschaid/swak4foamandpyfoamdockerfile
