### ISSUE TITLE
OpenFOAM installation problem in a new user's account

### ISSUE THREAD

**Issue by L-Thomes** [ladybug-tools/butterfly#236]
Hello,
I have already installed the OpenFOAM in the Administrator's account and it's working fine. Now, I'm trying to install it in an another account (in the same PC), however, I'm having serious trouble with it.
At first, I runned the OF_Env_Create file as Administrator, but I'm having the following error:

![error-adm](https://cloud.githubusercontent.com/assets/28121916/26110801/bf52ec0a-3a29-11e7-94ca-612afd2ab308.PNG)

Is it possible to have OpenFOAM installed in an account different from the Adm? What could I do?

Thanks in advance

(Sorry for the serveral posts about installation, I'm just a beginner)

**Comment by MikkiSeidenschnur** [comment]
From the looks of the error message, I'd say that you are already running a container on the computer. My guess is, that if you can rename the container created by the new user in some way, then you'd have a working container :). 

Can't really offer support based on empirical knowledge, since I haven't encountered this problem before.

Best regards
Mikki Seidenschnur

**Comment by MikkiSeidenschnur** [comment]
Have you tried running the OpenFOAM_Start as admin, and see if it works without creating a new environment ?

**Comment by L-Thomes** [comment]
Thanks for your reply. I removed all the existing containers using the command `docker rm -f $(docker ps -a -q)` in the docker, and I guess it worked, the following figure shows the OF_Env_Create window:
![depois de remover containers](https://cloud.githubusercontent.com/assets/28121916/26153663/cc9d602a-3ae2-11e7-976e-7b811072da53.PNG)
But the OpenFOAM_Start gives the following error (I can't run as admin right now, but I will be able to do that in a few hours):
![openfoam start](https://cloud.githubusercontent.com/assets/28121916/26153699/fa0993c6-3ae2-11e7-81c9-696a9d2e1900.png)

**Comment by L-Thomes** [comment]
I runned the OpenFOAM_Start as admin and another error appeared:
![openfoam start adm](https://cloud.githubusercontent.com/assets/28121916/26157219/10685204-3aef-11e7-96e0-5f70f7039a16.PNG)
"O sistema no pode encontrar o arquivo especificado" = "The system cannot find the specified file"

**Comment by L-Thomes** [comment]
I just rebooted the pc and runned it again and it worked =). But, unfortunatly, the "workingDir" folder is the "adm" folder. Is there any way i could set the workingDir to be my "new account" folder?

**Comment by MikkiSeidenschnur** [comment]
Glad to see the that you found a solution. I have to honest here - it's not really my speciality, but I seem to remember that someone requested the same thing, somewhere. @mostaphaRoudsari might know this.

**Comment by mostaphaRoudsari** [comment]
Thanks @MikkiSeidenschnur. @L-Thomes check this issue: https://github.com/ladybug-tools/butterfly/issues/176#issuecomment-278668360 for a similar problem.

**Comment by L-Thomes** [comment]
@mostaphaRoudsari , as I understood from that issue, there's no way I could change the shared _workingDir_ folder. Is that right? The problem is that I don't have access to the _admin_ folder anymore =(
