### ISSUE TITLE
Is it possible to run OpenFOAM with different users of the same PC or in a Cluster?

### ISSUE THREAD

**Issue by L-Thomes** [ladybug-tools/butterfly#240]
Greetings,
I would like to know if there is anyway I could run OpenFOAM with different users of the same PC. **Or run OpenFOAM in a cluster**.
For example, I installed OpenFOAM using the _User1_ account and it's working fine. So the OpenFOAM's _workingDir_ is shared with the _C:/Users/User1_ folder. Now, I want to run OpenFOAM using another user, e.x., the _admin_. 
But, I can't find I way to do so. Everytime I run the OpenFOAM_Start using _admin_ account, this error message appears:
![foam error](https://cloud.githubusercontent.com/assets/28121916/26381179/3bfb3850-3ff9-11e7-8f0b-78b299c87e1c.png)
And if I run the OF_Env_Create, it gives:
![error create](https://cloud.githubusercontent.com/assets/28121916/26381178/3bf4a3dc-3ff9-11e7-94a0-1e6e7cdec683.PNG)

P.S.: The user _Test2_ has admin rights, and I shared the _C:/Users/User1_ folder with all users.

Could anyone help me, please?

**Comment by mostaphaRoudsari** [comment]
The error is because the user variable for docker is not set in the environment.

![image](https://cloud.githubusercontent.com/assets/2915573/26532075/e0659e74-43c5-11e7-8254-61c7d7a734d6.png)
