### ISSUE TITLE
unalbe to complete my installion

### ISSUE THREAD

**Issue by accesstopuru** [ladybug-tools/butterfly#242]
Upon start of openFOAM software is shows me the error like
Error response from daemon: No such container: of _plus_1612
Error: failed to start containers: of_plus_1612

**Comment by mostaphaRoudsari** [comment]
@accesstopuru can you provide us more info. Did you follow the installation process from [this video](https://www.youtube.com/watch?v=e90FyyfVbe0&list=PLkjfDmSc5OrxwNaf7xmPJ5lpmF11J7kuE).

**Comment by accesstopuru** [comment]
Dear,
Yes I am follow this one only.. It shows that same error..

**Comment by mostaphaRoudsari** [comment]
What is the error? When does it show up? Can you share a screenshot?
Are you running on Windows 10? Have you followed [directions here](https://github.com/ladybug-tools/butterfly/wiki/Windows-10-Installation-Notes).

**Comment by mostaphaRoudsari** [comment]
I'm closing this issue assuming the problem is solved. You can also try the newest version of OpenFOAM and butterfly.
