### ISSUE TITLE
Floating issue when running 'HVAC.gh'

### ISSUE THREAD

**Issue by MarkJIN18** [ladybug-tools/butterfly#243]
Dear butterfly experts,

I have a floating issue when running buoyantBoussinesqSimpleFoam (prototype 'HVAC.gh') through grasshopper. Can anyone help tell how can I solve it? 

Many thanks.
Mark

/*---------------------------------------------------------------------------*\
| ========= | |
| \\ / F ield | OpenFOAM: The Open Source CFD Toolbox |
| \\ / O peration | Version: v1612+ |
| \\ / A nd | Web: www.OpenFOAM.com |
| \\/ M anipulation | |
\*---------------------------------------------------------------------------*/
Build : v1612+
Exec : buoyantBoussinesqSimpleFoam -parallel
Date : May 22 2017
Time : 10:18:58
Host : "default"
PID : 2839
Case : /home/ofuser/workingDir/butterfly/simple_hvac
nProcs : 4
Slaves : 
3
(
"default.2840"
"default.2841"
"default.2842"
)

Pstream initialized with:
floatTransfer : 0
nProcsSimpleSum : 0
commsType : nonBlocking
polling iterations : 0
sigFpe : Enabling floating point exception trapping (FOAM_SIGFPE).
fileModificationChecking : Monitoring run-time modified files using timeStampMaster (fileModificationSkew 10)
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Create time

Create mesh for time = 0

SIMPLE: convergence criteria
field nut	tolerance 0.0001
field p_rgh	tolerance 0.0001
field k	tolerance 0.0001
field U	tolerance 0.0001
field T	tolerance 0.0001
field epsilon	tolerance 0.0001
field alphat	tolerance 0.0001

Reading thermophysical properties

Reading field T

Reading field p_rgh

Reading field U

Reading/calculating face flux field phi

Selecting incompressible transport model Newtonian
Creating turbulence model

Selecting turbulence model type RAS
Selecting RAS turbulence model RNGkEpsilon
RNGkEpsilonCoeffs
{
Cmu 0.0845;
C1 1.42;
C2 1.68;
C3 -0.33;
sigmak 0.71942;
sigmaEps 0.71942;
eta0 4.38;
beta 0.012;
}

Reading field alphat

Reading g

Reading hRef
Calculating field g.h

No MRF models present

Radiation model not active: radiationProperties not found
Selecting radiationModel none
No finite volume options present

Starting time loop

Time = 1

smoothSolver: Solving for Ux, Initial residual = 1, Final residual = 0.06427477, No Iterations 4
smoothSolver: Solving for Uy, Initial residual = 1, Final residual = 0.06226344, No Iterations 4
smoothSolver: Solving for Uz, Initial residual = 1, Final residual = 0.03950103, No Iterations 3
smoothSolver: Solving for T, Initial residual = 1, Final residual = 0.03671111, No Iterations 2
DICPCG: Solving for p_rgh, Initial residual = 1, Final residual = 0.008356878, No Iterations 86
DICPCG: Solving for p_rgh, Initial residual = 0.07888434, Final residual = 0.0006831407, No Iterations 9
DICPCG: Solving for p_rgh, Initial residual = 0.007053905, Final residual = 6.211827e-05, No Iterations 71
time step continuity errors : sum local = 3777.266, global = 3.22967, cumulative = 3.22967
smoothSolver: Solving for epsilon, Initial residual = 0.9994728, Final residual = 0.0532353, No Iterations 4
smoothSolver: Solving for k, Initial residual = 1, Final residual = 0.05640973, No Iterations 4
ExecutionTime = 2.65 s ClockTime = 3 s

Time = 2

smoothSolver: Solving for Ux, Initial residual = 0.5142984, Final residual = 0.02186577, No Iterations 2
smoothSolver: Solving for Uy, Initial residual = 0.5242573, Final residual = 0.02244622, No Iterations 2
smoothSolver: Solving for Uz, Initial residual = 0.5106874, Final residual = 0.02933279, No Iterations 2
smoothSolver: Solving for T, Initial residual = 0.3832824, Final residual = 0.01046751, No Iterations 2
DICPCG: Solving for p_rgh, Initial residual = 0.9825413, Final residual = 0.009757923, No Iterations 799
DICPCG: Solving for p_rgh, Initial residual = 0.04390194, Final residual = 0.000303611, No Iterations 9
DICPCG: Solving for p_rgh, Initial residual = 0.0073043, Final residual = 7.259574e-05, No Iterations 45
time step continuity errors : sum local = 1883567, global = 2227.205, cumulative = 2230.435
smoothSolver: Solving for epsilon, Initial residual = 0.08647006, Final residual = 0.000113174, No Iterations 1
smoothSolver: Solving for k, Initial residual = 0.1579946, Final residual = 0.01115579, No Iterations 2
ExecutionTime = 9.56 s ClockTime = 10 s

Time = 3

smoothSolver: Solving for Ux, Initial residual = 0.8070853, Final residual = 0.07865708, No Iterations 3
smoothSolver: Solving for Uy, Initial residual = 0.8145663, Final residual = 0.03882168, No Iterations 4
smoothSolver: Solving for Uz, Initial residual = 0.5761609, Final residual = 0.0390739, No Iterations 4
smoothSolver: Solving for T, Initial residual = 0.1644957, Final residual = 0.006771158, No Iterations 2
DICPCG: Solving for p_rgh, Initial residual = 0.7802636, Final residual = 0.006709539, No Iterations 13
DICPCG: Solving for p_rgh, Initial residual = 0.04575494, Final residual = 0.0004415382, No Iterations 130
DICPCG: Solving for p_rgh, Initial residual = 0.005830491, Final residual = 5.648426e-05, No Iterations 78
time step continuity errors : sum local = 6.68889e+12, global = -4.053656e+11, cumulative = -4.053656e+11
smoothSolver: Solving for epsilon, Initial residual = 1, Final residual = 0.08337707, No Iterations 1
smoothSolver: Solving for k, Initial residual = 1, Final residual = 0.08762031, No Iterations 2
ExecutionTime = 11.24 s ClockTime = 11 s

Time = 4

smoothSolver: Solving for Ux, Initial residual = 0.1870785, Final residual = 0.008250987, No Iterations 2
smoothSolver: Solving for Uy, Initial residual = 0.1039591, Final residual = 0.003633928, No Iterations 2
smoothSolver: Solving for Uz, Initial residual = 0.003344756, Final residual = 0.0001428352, No Iterations 2
smoothSolver: Solving for T, Initial residual = 0.0360337, Final residual = 0.0008781286, No Iterations 2
DICPCG: Solving for p_rgh, Initial residual = 0.9999995, Final residual = 0.7505781, No Iterations 1001
DICPCG: Solving for p_rgh, Initial residual = 2.097918e-11, Final residual = 2.097918e-11, No Iterations 0
DICPCG: Solving for p_rgh, Initial residual = 2.097918e-11, Final residual = 2.097918e-11, No Iterations 0
time step continuity errors : sum local = 9.100777e+16, global = -1.152626e+15, cumulative = -1.153031e+15
smoothSolver: Solving for epsilon, Initial residual = 0.006323925, Final residual = 0.0002800085, No Iterations 1
smoothSolver: Solving for k, Initial residual = 0.9999998, Final residual = 0.08579136, No Iterations 4
ExecutionTime = 15.48 s ClockTime = 16 s

Time = 5

smoothSolver: Solving for Ux, Initial residual = 0.6268107, Final residual = 0.01889084, No Iterations 2
smoothSolver: Solving for Uy, Initial residual = 0.5691313, Final residual = 0.02593386, No Iterations 2
smoothSolver: Solving for Uz, Initial residual = 0.525286, Final residual = 0.01999095, No Iterations 2
smoothSolver: Solving for T, Initial residual = 0.1776883, Final residual = 0.004896742, No Iterations 2
DICPCG: Solving for p_rgh, Initial residual = 0.8409992, Final residual = 0.008296552, No Iterations 25
DICPCG: Solving for p_rgh, Initial residual = 8.57445e-13, Final residual = 8.57445e-13, No Iterations 0
DICPCG: Solving for p_rgh, Initial residual = 8.57445e-13, Final residual = 8.57445e-13, No Iterations 0
time step continuity errors : sum local = 3.230307e+23, global = -5.044393e+14, cumulative = -1.657471e+15
smoothSolver: Solving for epsilon, Initial residual = 4.732135e-05, Final residual = 1.311093e-10, No Iterations 1
bounding epsilon, min: -1.103807e+26 max: 1.972571e+51 average: 2.670218e+47
smoothSolver: Solving for k, Initial residual = 0.04771126, Final residual = 0.002285774, No Iterations 2
ExecutionTime = 16.44 s ClockTime = 17 s

Time = 6

smoothSolver: Solving for Ux, Initial residual = 0.9995642, Final residual = 0.04432588, No Iterations 4
smoothSolver: Solving for Uy, Initial residual = 0.9996968, Final residual = 0.04761556, No Iterations 4
smoothSolver: Solving for Uz, Initial residual = 0.9858131, Final residual = 0.06924769, No Iterations 3
smoothSolver: Solving for T, Initial residual = 0.01200576, Final residual = 0.0002952721, No Iterations 2
DICPCG: Solving for p_rgh, Initial residual = 0.9446084, Final residual = 0.005339222, No Iterations 6
DICPCG: Solving for p_rgh, Initial residual = 0.08971123, Final residual = 0.0008218812, No Iterations 6
DICPCG: Solving for p_rgh, Initial residual = 0.02323654, Final residual = 0.0002319251, No Iterations 193
time step continuity errors : sum local = 4.926861e+44, global = -1.110593e+37, cumulative = -1.110593e+37
smoothSolver: Solving for epsilon, Initial residual = 1, Final residual = 0.002671469, No Iterations 2
bounding epsilon, min: -2.219668e+47 max: 1.75779e+78 average: 3.182358e+73
smoothSolver: Solving for k, Initial residual = 1, Final residual = 0.0501481, No Iterations 2
bounding k, min: -3.660183e+25 max: 9.966186e+62 average: 8.53815e+58
ExecutionTime = 18.1 s ClockTime = 18 s

Time = 7

smoothSolver: Solving for Ux, Initial residual = 8.069155e-09, Final residual = 8.069155e-09, No Iterations 0
smoothSolver: Solving for Uy, Initial residual = 5.382338e-08, Final residual = 7.473481e-09, No Iterations 1
smoothSolver: Solving for Uz, Initial residual = 2.092083e-08, Final residual = 2.077615e-09, No Iterations 1
smoothSolver: Solving for T, Initial residual = 0.1619372, Final residual = 0.003564584, No Iterations 2
DICPCG: Solving for p_rgh, Initial residual = 1, Final residual = 46631.37, No Iterations 1001
DICPCG: Solving for p_rgh, Initial residual = 1.64537e-26, Final residual = 1.64537e-26, No Iterations 0
DICPCG: Solving for p_rgh, Initial residual = 1.64537e-26, Final residual = 1.64537e-26, No Iterations 0
time step continuity errors : sum local = 1.468529e+53, global = 5.868436e+40, cumulative = 5.867326e+40
smoothSolver: Solving for epsilon, Initial residual = 0.07343377, Final residual = 2.828068e-19, No Iterations 1
bounding epsilon, min: -2.257804e+66 max: 8.093947e+109 average: 1.184346e+105
smoothSolver: Solving for k, Initial residual = 0.5212037, Final residual = 0.02939162, No Iterations 2
ExecutionTime = 22.26 s ClockTime = 22 s

Time = 8

smoothSolver: Solving for Ux, Initial residual = 0.6924604, Final residual = 0.01784756, No Iterations 2
smoothSolver: Solving for Uy, Initial residual = 0.3637153, Final residual = 0.005737122, No Iterations 2
smoothSolver: Solving for Uz, Initial residual = 0.2793264, Final residual = 0.00626238, No Iterations 2
smoothSolver: Solving for T, Initial residual = 0.07790577, Final residual = 0.002676894, No Iterations 2
DICPCG: Solving for p_rgh, Initial residual = 0.8911507, Final residual = 0.008688155, No Iterations 18
DICPCG: Solving for p_rgh, Initial residual = 1.957294e-52, Final residual = 1.957294e-52, No Iterations 0
DICPCG: Solving for p_rgh, Initial residual = 1.957294e-52, Final residual = 1.957294e-52, No Iterations 0
time step continuity errors : sum local = 8.548233e+90, global = -3.056251e+75, cumulative = -3.056251e+75
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 2840 on node default exited on signal 8 (Floating point exception).
--------------------------------------------------------------------------
[1] #0 Foam::error:rintStack(Foam::Ostream&)[0] #0 Foam::error:rintStack(Foam::Ostream&) in "/opt/OpenFOAM/OpenFOAM-v1612+/platforms/linux64GccDPInt32Opt/lib/libOpenFOAM.so"
[0] #1 Foam::sigFpe::sigHandler(int) in "/opt/OpenFOAM/OpenFOAM-v1612+/platforms/linux64GccDPInt32Opt/lib/libOpenFOAM.so"
[1] #1 Foam::sigFpe::sigHandler(int) in "/opt/OpenFOAM/OpenFOAM-v1612+/platforms/linux64GccDPInt32Opt/lib/libOpenFOAM.so"
[0] #2 ? in "/opt/OpenFOAM/OpenFOAM-v1612+/platforms/linux64GccDPInt32Opt/lib/libOpenFOAM.so"
[1] #2 ? in "/lib64/libc.so.6"
[0] #3 Foam::multiply(Foam::Field<double>&, Foam::UList<double> const&, Foam::UList<double> const&) in "/lib64/libc.so.6"
[1] #3 Foam::multiply(Foam::Field<double>&, Foam::UList<double> const&, Foam::UList<double> const&) in "/opt/OpenFOAM/OpenFOAM-v1612+/platforms/linux64GccDPInt32Opt/lib/libOpenFOAM.so"
[0] #4 Foam::tmp<Foam::GeometricField<double, Foam::fvPatchField, Foam::volMesh> > Foam:perator*<Foam::fvPatchField, Foam::volMesh>(Foam::tmp<Foam::GeometricField<doub le, Foam::fvPatchField, Foam::volMesh> > const&, Foam::GeometricField<double, Foam::fvPatchField, Foam::volMesh> const&) in "/opt/OpenFOAM/OpenFOAM-v1612+/platforms/linux64GccDPInt32Opt/lib/libOpenFOAM.so"
[1] #4 void Foam::multiply<Foam::fvPatchField, Foam::volMesh>(Foam::GeometricField<double, Foam::fvPatchField, Foam::volMesh>&, Foam::GeometricField<double, Foam::fvPatchField, Foam::volMesh> const&, Foam::GeometricField<double, Foam::fvPatchField, Foam::volMesh> const&) in "/opt/OpenFOAM/OpenFOAM-v1612+/platforms/linux64GccDPInt32Opt/lib/libincompressibleTurbulenceModels.so"
[1] #5 Foam::tmp<Foam::GeometricField<double, Foam::fvPatchField, Foam::volMesh> > Foam:perator*<Foam::fvPatchField, Foam::volMesh>(Foam::GeometricField<double, Foam::fvPatchField, Foam::volMesh> const&, Foam::tmp<Foam::GeometricField<double, Foam::fvPatchField, Foam::volMesh> > const&) in "/opt/OpenFOAM/OpenFOAM-v1612+/platforms/linux64GccDPInt32Opt/lib/libincompressibleTurbulenceModels.so"
[1] #6 Foam::RASModels::RNGkEpsilon<Foam::IncompressibleT urbulenceModel<Foam::transportModel> >::correct() in "/opt/OpenFOAM/OpenFOAM-v1612+/platforms/linux64GccDPInt32Opt/lib/libincompressibleTurbulenceModels.so"
[1] #7 ? in "/opt/OpenFOAM/OpenFOAM-v1612+/platforms/linux64GccDPInt32Opt/bin/buoyantBoussinesqSimpleFoam"
[1] #8 __libc_start_main in "/lib64/libc.so.6"
[1] #9 ? in "/opt/OpenFOAM/OpenFOAM-v1612+/platforms/linux64GccDPInt32Opt/bin/buoyantBoussinesqSimpleFoam"
[default:02840] *** Process received signal ***
[default:02840] Signal: Floating point exception (8)
[default:02840] Signal code: (-6)
[default:02840] Failing at address: 0x1f400000b18
[default:02840] [ 0] /lib64/libc.so.6(+0x32660)[0x7f516d4f4660]
[default:02840] [ 1] /lib64/libc.so.6(gsignal+0x35)[0x7f516d4f45e5]
[default:02840] [ 2] /lib64/libc.so.6(+0x32660)[0x7f516d4f4660]
[default:02840] [ 3] /opt/OpenFOAM/OpenFOAM-v1612+/platforms/linux64GccDPInt32Opt/lib/libOpenFOAM.so(_ZN4Foam8multiplyERNS_5FieldIdEERKN S_5UListIdEES6_+0xd5)[0x7f516e7bfd55]
[default:02840] [ 4] /opt/OpenFOAM/OpenFOAM-v1612+/platforms/linux64GccDPInt32Opt/lib/libincompressibleTurbulenceModels.so(_ZN4Foam8mult iplyINS_12fvPatchFieldENS_7volMeshEEEvRNS_14Geomet ricFieldIdT_T0_EERKS6_S9_+0x41)[0x7f5172705861]
[default:02840] [ 5] /opt/OpenFOAM/OpenFOAM-v1612+/platforms/linux64GccDPInt32Opt/lib/libincompressibleTurbulenceModels.so(_ZN4FoammlINS _12fvPatchFieldENS_7volMeshEEENS_3tmpINS_14Geometr icFieldIdT_T0_EEEERKS7_RKS8_+0x15b)[0x7f5172784afb]
[default:02840] [ 6] /opt/OpenFOAM/OpenFOAM-v1612+/platforms/linux64GccDPInt32Opt/lib/libincompressibleTurbulenceModels.so(_ZN4Foam9RASM odels11RNGkEpsilonINS_29IncompressibleTurbulenceMo delINS_14transportModelEEEE7correctEv+0x2d0)[0x7f51727d5ec0]
[default:02840] [ 7] buoyantBoussinesqSimpleFoam[0x481a7d]
[default:02840] [ 8] /lib64/libc.so.6(__libc_start_main+0xfd)[0x7f516d4e0d1d]
[default:02840] [ 9] buoyantBoussinesqSimpleFoam[0x42db51]
[default:02840] *** End of error message ***

**Comment by mostaphaRoudsari** [comment]
I think I have already answered this question on the Grasshopper forum. Most probably the units of your document is set to mm and you haven't adjust the size of the geometry. Feel free to re-open this issue if it's otherwise.
