### ISSUE TITLE
Alternatives to running Revit as administrator for Butterfly in Dynamo?

### ISSUE THREAD

**Issue by bce5** [ladybug-tools/butterfly#244]
Are there any alternatives to running Revit as an Administrator as described in the the "Getting Started with Butterfly in Dynamo" page? My IT department has told me that they will not allow us non-IT folks to run Revit as admins. What specifically does Butterfly need to access that requires Admin privileges, and would there potentially be a way for IT to just add the proper rights for what Butterfly needs to do without handing over full admin privileges? Or other workarounds? Thanks!

**Comment by mostaphaRoudsari** [comment]
Hi @bce5, Butterfly is using [docker](http://docker.com/) to run OpenFOAM in Windows which needs administrative privileges to run successfully. [We tried to find an alternate solution but there was none](https://github.com/ladybug-tools/butterfly/issues/142).

One possible solution in the future is to use [OpenFOAM installation for Windows 10](https://openfoam.org/download/windows-10/) which apparently doesn't need docker but then it will only work for Windows 10 users. :|
