### ISSUE TITLE
Cannot run OpenFOAM on windows 7 after installation

### ISSUE THREAD

**Issue by anusarns** [ladybug-tools/butterfly#246]
Hi,

So I have installed OpenFOAM 1612+ on Windows 7 using following link.

http://www.openfoam.com/download/ins...ry-windows.php

This is my first time trying to run OpenFOAM on Windows, so according to instruction, I just went straight to OF_Env_Create after installation. Then I got the error as shown in pic1. I tried to run OpenFOAM_Start afterwards but obviously, it did not work, the terminal showed up for short time with some red sentences then disappeared as shown in pic2. Please note that the program was installed under admin account and was run under admin account as well.

I checked VirtualMachine installed on Desktop, it turns out that the default system (Ubuntu 32-bit) is not running, so I tried to start manually but got error code as below, please also see log file as attached for more details. 

Result Code: 
E_FAIL (0x80004005)
Component: 
ConsoleWrap
Interface: 
IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

However, this error only occurs when I run VM as a normal user, if I log in to admin, there is no error on VM, but error in pic1 and pic2 still persists.

Please kindly advise if I have done anything wrong or if I miss anything.

![pic2](https://user-images.githubusercontent.com/29470552/27206482-9107f8c2-51fd-11e7-9634-4d4749744653.jpg)
[Logfile.txt](https://github.com/ladybug-tools/butterfly/files/1079367/Logfile.txt)
![pic1](https://user-images.githubusercontent.com/29470552/27206483-910dd5e4-51fd-11e7-97e5-b2719205311d.jpg)

**Comment by mostaphaRoudsari** [comment]
@anusarns sorry for the delayed reply. I suggest you to watch [this video](https://www.youtube.com/watch?v=e90FyyfVbe0&index=1&list=PLkjfDmSc5OrxwNaf7xmPJ5lpmF11J7kuE) and follow the instructions there. Most of the time it will only work if you use an admin account.

**Comment by mostaphaRoudsari** [comment]
Any updates on this issue?

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
