### ISSUE TITLE
Meshing for a model with a great amount of buildings

### ISSUE THREAD

**Issue by yoanngoma** [ladybug-tools/butterfly#247]
Hi @mostaphaRoudsari,

I watched both of your videos on youtube covering both the outdoor and airdoor airflow, as well as the  slides on snappyHexMesh. The problem I am having at the moment is that I would like to run an outdoor analysis both of the air pressure as well as the heat transfer on a city district, which has around 1200 buildings. In order to do so I would like to decrease my mesh’s density, both for the block mesh and the snappyHexMesh around the buildings. After reading the PDF you recommended I understand that I would have to do that in the blocks part for the BlockMesh (see figure below) as well as the castellatedMeshControls for the snappy HeshMesh (and decreasing the variable maxGlobalCell) to do so.  
 
![1](https://user-images.githubusercontent.com/29441191/27406648-2699a81c-569b-11e7-9979-5c23c4a5998a.JPG)

Since you didn’t really have the time to explain it in your video I was wondering if there is an easy way to change that in the models you gave. I tried to change the values of the variables concerning _gradXYZ_ in meshParams for blockMesh and thought that both _percentageLentgh_ and _percentageCells_ have something to do with the function MeshGrading in blockMesh (see figure below).
 
![2](https://user-images.githubusercontent.com/29441191/27406653-2b8fca36-569b-11e7-99db-b55db64557e4.JPG)

Could you please let me know what setGrading works and if possible if that’s the right way to change the mesh? Also, is there a simple way to do the same for snappyHexMesh? 

Thank you very much for your help.

**Comment by mostaphaRoudsari** [comment]
Hi @yoanngoma,

For outdoor analysis Butterfly creates a single block but you can use the components that are shown in your image to generate a [Multi-grading](https://cfd.direct/openfoam/user-guide/blockmesh/#x25-1800005.3.1.4). You can read more about it in the link. It basically allows you to set the distribution of the cells based on % length in X, Y and Z directions.

snappyHexMesh generates the mesh based on blockMesh. Once you set it up correctly in blockMesh you will see the effect in the final mesh.

**Comment by mostaphaRoudsari** [comment]
I'm closing this issue for now. Also see this: https://github.com/ladybug-tools/butterfly/issues/96
