### ISSUE TITLE
Butterfly doesn't work with the new release of OpenFOAM v1706+

### ISSUE THREAD

**Issue by GuanYue0213** [ladybug-tools/butterfly#250]
Hi guys,

I have installed OpenFOAM v1709+ on Windows 10 home version. All the processes seem like OK. 
However, when I tested Butterfly by using the example file I got an error below.

_Runtime error (AssertionException): Failed to find container id.Do you have the OpenFOAM container running?
You can initiate OpenFOAM container by running start_OF.bat:
C:\Program Files (x86)\ESI\OpenFOAM\1612\\Windows\Scripts\start_OF.bat
1. Traceback:
  line 263, in _RunManager__command, "C:\Users\47010\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 215, in command, "C:\Users\47010\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 316, in run, "C:\Users\47010\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 716, in command, "C:\Users\47010\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\case.py"
  line 748, in blockMesh, "C:\Users\47010\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\case.py"
  line 47, in script_

![image](https://user-images.githubusercontent.com/23726533/27907894-57d1dd4e-6241-11e7-8e95-b6dda6051e3a.png)
![image](https://user-images.githubusercontent.com/23726533/27907921-6f0c31f8-6241-11e7-9059-dbe2d68ca3f7.png)

Can I ask for some advice on how to solve the problem? Thanks very much!

**Comment by mostaphaRoudsari** [comment]
Hi @GuanYue0213,

Thanks for reporting this issue. The current version of butterfly works with an older version of OpenFOAM however it's quite straight forward how to update the version.

You can change the version of OpenFOAM to v1706+ by changing [this line](https://github.com/ladybug-tools/butterfly/blob/771fd4049a6c795233bca725e0e9bd526b6f5b57/butterfly/version.py#L12) in `version.py`.

Here is the step by step process.

1. Find where butterfly is installed.
![image](https://user-images.githubusercontent.com/2915573/27915103-42dcd690-6233-11e7-97c5-3c85af0a9fad.png)

2. Close **both** Rhino and Grasshopper if you have them open.
3. Open version.py and change line 12 to:
```python
OFFullVer = "v1706+"
```
4. Save the file.
5. Open Rhino and then Grasshopper and it should work fine.

Let me know if it didn't solve the problem.

**Comment by GuanYue0213** [comment]
Really appreciate your reply. I have changed the script, but it's still not
working and give me the same error information. So, if this issue is
related to the version of openfoam. Can I just install an old version like
v1612+ to solve it?

[image: Inline images 1]
[image: Inline images 2]
[image: Inline images 3]

**Comment by mostaphaRoudsari** [comment]
I can't see the images but yes this is an issue with the path. Did you restart Rhino and Grasshopper? Grasshopper caches the library once you import them. Updating the file without restarting both Rhino and Grasshopper won't solve the problem.

**Comment by GuanYue0213** [comment]
Yes, I have restarted Rhino and Grasshopper many times.

Runtime error (AssertionException): Failed to find container id.Do you have
the OpenFOAM container running?
You can initiate OpenFOAM container by running start_OF.bat:
C:\Program Files (x86)\ESI\OpenFOAM\1706\\Windows\Scripts\start_OF.bat
1. Traceback:
  line 263, in _RunManager__command,
"C:\Users\Administrator\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 215, in command,
"C:\Users\Administrator\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 316, in run,
"C:\Users\Administrator\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 716, in command,
"C:\Users\Administrator\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\case.py"
  line 748, in blockMesh,
"C:\Users\Administrator\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\case.py"
  line 47, in script

**Comment by GuanYue0213** [comment]
Really grateful for your advice Mostapha. The main reason maybe some
compatible problems existed between butterfly 0004 and OpenFoam v1706. So,
I install v1612 instead of the latest version and run the simulation
successfully. Thank you, Mostapha! Looking forward the new development of
Ladybugs and Butterfly!

Best Wishes!

**Comment by mostaphaRoudsari** [comment]
Thank you for the update. Something must have changed for docker settings then. I have yet to install the new version but if anybody else beat me on solving this issue please let us know.

**Comment by mgrimm84** [comment]
I am also having this problem - where can you find v1612 of OpenFOAM? Thanks.

**Comment by GuanYue0213** [comment]
I think you can find it via this link
http://www.openfoam.com/download/release-history.php

**Comment by AmyKoshy** [comment]
I had the same issue and changing the script did not work. I am going back to installing older version.

**Comment by freddiefrederick** [comment]
Hi All - I installed OpenFOAM v1709 and am having the same issues as others.  My meshing components wont run.  Error:
            {0;0}
0. Runtime error (AssertionException): Failed to find container id.Do you have the OpenFOAM container running?
You can initiate OpenFOAM container by running start_OF.bat:
C:\Program Files (x86)\ESI\OpenFOAM\1612\\Windows\Scripts\start_OF.bat
1. Traceback:
  line 263, in _RunManager__command, "C:\Users\22828\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 215, in command, "C:\Users\22828\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 316, in run, "C:\Users\22828\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 716, in command, "C:\Users\22828\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\case.py"
  line 748, in blockMesh, "C:\Users\22828\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\case.py"
  line 47, in script

When I go to modify the version in the  "__init__.py" file as suggested above the "__init__.py" file is empty.  No code inside to modify?  Is current solution to this to make sure you install v1612 of open foam?  

Thanks!

**Comment by mostaphaRoudsari** [comment]
I try to take a look at this soon. Meanwhile use the older version.

> When I go to modify the version in the "init.py" file as suggested above the "init.py" file is empty. No code inside to modify? Is current solution to this to make sure you install v1612 of open foam?

It's not `version.py` and not `__init__.py`

**Comment by saket411** [comment]
Sharing this in case it helps...
I tried the new version on a spare machine and in my case the error was different. After running the VM when I ran the OpenFOAM_Start as admin (as usual) it said:
![image](https://user-images.githubusercontent.com/1322619/28671783-73469882-7310-11e7-8792-20e0ddcf7a15.png)

I reverted back to older version and now I always get this error when meshing. 
![image](https://user-images.githubusercontent.com/1322619/28681201-3eb4ff26-732b-11e7-8ca1-47381bfa752e.png)
Reinstalled everything a couple of times. Tried both 1606 and 1612. Cannot seem to make it work.
Runs perfectly on my laptop though but not on my pc anymore.

Any comments what I can try to fix this?

Thanks!!

**Comment by mostaphaRoudsari** [comment]
Hi @saket411, from the screenshot I assume your username is not the same the folder under users. Is this a case similar to [this one](https://github.com/ladybug-tools/butterfly/issues/176#issuecomment-278668360)?

**Comment by saket411** [comment]
Hello **@mostaphaRoudsari** 
Thank you for the prompt reply. I tried the additional py component mentioned in the comment you linked above with username as Saket.Sarupria only.
Works perfectly. Thanks a lot!!

**Comment by mostaphaRoudsari** [comment]
Resolved via https://github.com/ladybug-tools/butterfly/commit/917b50c83043456d6304dd28561991557820dba9

Update butterfly installation using the update component and it should be good to go!
