### ISSUE TITLE
OpenFOAM installation issues in unable to start the VM

### ISSUE THREAD

**Issue by thefreya** [ladybug-tools/butterfly#251]
Hi.
As running OpenFOAM_start at the installation process I find the error text below. 
Can anyone help me out please?

![image](https://user-images.githubusercontent.com/29972551/28007356-0dec066e-658e-11e7-96c2-53c53ebf1750.png)

**Comment by thefreya** [comment]
Problem solved. it was because of the user name.

**Comment by mostaphaRoudsari** [comment]
Thank you for letting us know.

**Comment by fginevra** [comment]
Hi I got the same issue. my username is fginevra, no spaces. What should i do? thanks!!!
