### ISSUE TITLE
BlockMesh Error- Failed to find container ID

### ISSUE THREAD

**Issue by natahein** [ladybug-tools/butterfly#254]
I'm working through the Outdoor Airflow example file, and cannot seem to resolve the warning under BlockMesh.  Here is the error I'm getting:
<img width="955" alt="170712_gh solution_blockmesh error" src="https://user-images.githubusercontent.com/30128433/28137577-a9671550-6702-11e7-9989-67856b7a8316.PNG">

I've installed OpenFOAM successfully, and am running all programs as an admin. Everything seems to be working fine. OpenFOAM tells me that it is already running:
<img width="430" alt="openfoam start" src="https://user-images.githubusercontent.com/30128433/28137694-fa809db2-6702-11e7-83ad-ba61aaeb3508.PNG">

Any advice on how to resolve this issue? Thanks!

**Comment by mgrimm84** [comment]
I am having the same issue - how did you resolve this?
