### ISSUE TITLE
Large values and no visualization

### ISSUE THREAD

**Issue by AmyKoshy** [ladybug-tools/butterfly#255]
Hi, creating a new issue from previous issue posted. I have large values and i am guessing it is causing it to have no visualization. Not sure how to go about fixing it. Thank you for your help~
![28171204-f4992df2-67e7-11e7-8678-533fc9ca09ee](https://user-images.githubusercontent.com/30070811/28171920-43d700fe-67ea-11e7-8a89-a6dc101f386c.png)
Any recommendations for this?
![28171261-1941a558-67e8-11e7-8679-2106796531d6](https://user-images.githubusercontent.com/30070811/28171934-4ec31818-67ea-11e7-9f6f-1f5bf9e0eae6.png)

**Comment by mostaphaRoudsari** [comment]
@AmyKoshy, Do you have a number of probes inside the test geometries / buildings? That is most likely the reason for such results.

**Comment by AmyKoshy** [comment]
Hi Mostapha, thank you for your reply. I do not see any inside my buildings, they may be close to the geometry? Should I adjust the probes to be further away from the edges and buildings?
![image](https://user-images.githubusercontent.com/30070811/28305221-1b6446fe-6b9b-11e7-9099-ad769c37955a.png),

**Comment by TheodoreGalanos** [comment]
Hi @AmyKoshy I think a few of them are quite close to the building boundaries to be considered inside. Especially if we factor in mesh quality and size, the center of the cell (where the calculation of the probe is usually done) will be inside the building. 

So two options (probably should try them concurrently):

1. Offset the calculation surface by a length at least equal to half your blockMesh size (background mesh)
2. Increase mesh quality (by first decreasing background mesh cell size).

Kind regards,
Theodore.

**Comment by AmyKoshy** [comment]
Hi @TheodoreGalanos 
I have been trying to resolve this and I am having no luck. I am trying the two options above but I am stuck at a new issue now, which I have tried to find a solution too, in closed and open issues, iv seen a few like this but no real solution?  At the moment the example file is not even working (it use to before). Any ideas? 

![image](https://user-images.githubusercontent.com/30070811/28364444-c46ef0d4-6c84-11e7-968c-f22d6a934b9e.png)

**Comment by AmyKoshy** [comment]
Wow, i just realized that this error is normal. Sorry about that! and the offset of the surface grid points is working! thank you so so much :) will close this now

![image](https://user-images.githubusercontent.com/30070811/28410743-e3a45bd2-6d3e-11e7-93fd-9f028a191669.png)

**Comment by PompeyLiang** [comment]
Hi @AmyKoshy 
Would you mind share your gh file to me ? 
I am have the same problem with you and I have also done what TheodoreGalanos suggested . However , it seen I still can't solve the problem . 
So I want to know more details about your case .

**Comment by shu-toz** [comment]
@AmyKoshy 
How did you offset the surface?? I'm getting the exact same error

**Comment by AmyKoshy** [comment]
Hi There,

I can't remember it was so long ago but I will ask my office for the file i documented the how to.
give me 1 or 2 days

Regards,
Amy

________________________________

**Comment by shu-toz** [comment]
Hey @AmyKoshy ,

Did you manage to find the example?
