### ISSUE TITLE
Large value results

### ISSUE THREAD

**Issue by thefreya** [ladybug-tools/butterfly#256]
Hi,

Thank you for the program and the example files.
As trying out the indoor airflow example, I just changed the geometries to fit my work which is single-sided natural ventilation but I'm getting large value results.

![image](https://user-images.githubusercontent.com/29972551/28399176-6a7edfd6-6d46-11e7-85cc-96f6b11b42be.png)
![image](https://user-images.githubusercontent.com/29972551/28399216-bbe7e8ae-6d46-11e7-855b-f407d114297d.png)

The pressure values seams too high and the velocity seems okay but not sure.

Can you see what is causing this problem? 

Also to set the wind direction, is it right to use the windvector component? The values seem high also. Should I change the mesh settings? Please advise.

Thank you in advance.

[indoor_airflow_test.zip](https://github.com/ladybug-tools/butterfly/files/1161057/indoor_airflow_test.zip)

**Comment by mostaphaRoudsari** [comment]
Hi @thefreya, I can't check your file now but do you let the air to somehow get out of the space or just have a single inlet?

**Comment by thefreya** [comment]
The inlets and outlets are set at same openings..like the room with one sided windows.

**Comment by mostaphaRoudsari** [comment]
@thefreya,  You can't assign inlet and outlet to the same surface. The inlet should be a different surface from the outlet.
