### ISSUE TITLE
Error message "of_create_container.exe has stopped working" at first attempt of setting up environment variables

### ISSUE THREAD

**Issue by johnmartingodo** [ladybug-tools/butterfly#259]
Hi
Being completely new to OpenFOAM for Windows and the docker technology I hope you might forgive me in case of trivial questions. 

I have just installed OpenFOAM 1612+ following the instructions on this GitHub-page, apparently with no issues. However, attempting to run the file OF_Env_Create I get a windows error message saying that "of_create_container.exe has stopped working". 

![errormessage1](https://user-images.githubusercontent.com/16979895/28838001-2ae03174-76ef-11e7-989d-b882fe057d36.PNG)

As I hoped it might help I tried to follow the Windows 10-specific installation instructions involving starting Docker Quickstart and running some commands directly in this before starting OF_Env_Create, without this making any difference.  

If I attempt to run OpenFOAM_Start this gives a slightly different error message: "of_create_container.exe has stopped working".
![errormessage2](https://user-images.githubusercontent.com/16979895/28838093-7b042304-76ef-11e7-905e-621971f20cee.PNG)

I have tried re-installing the whole package of Docker, VirtualBox, OpenFoam and Git, and naturally also tried rebooting the computer, without any luck. All running of files has been done by right-clicking and choosing "Run as administrator". I'm running on an updated 64-bit version of Windows 7.

Any kind of help would be highly appreciated

**Comment by johnmartingodo** [comment]
Just for your information: I performed a workaround for this issue and installed Windows 10 on the computer in question, instead of attempting to make it work with Windows 7. The issue i encountered in Windows 7 seems to be related to some kind of user profile corruption. I'll leave the post open for some more days to see if anyone has anything more to add, in case others encounter the same problem in the future.

By the way: When installing OpenFoam on an updated version of Windows 10 it seems vital to note what @MikkiSeidenschnur pointed out here: https://github.com/ladybug-tools/butterfly/issues/222

**Comment by mostaphaRoudsari** [comment]
@johnmartingodo thank you for posting the issue and the update. I'm going to close the issue for now. Added a label so people can find it easier in the future.
