### ISSUE TITLE
meshing+probes issue

### ISSUE THREAD

**Issue by grifang** [ladybug-tools/butterfly#260]
Hi,

I'm trying to run an outdoor simulation on a closed brep that is the boolean union of 30 boxes and a base.
The test geometry is given as a split surface that doesn't include the building boundaries lifted of 0.4 m from the base and the wind blows from south-west.

As first I've got issues in meshing as the mesh preview shows that the SnappyHexMesh doesn't consider the boxes volumes and the simulation runs as empty.

Secondly the probes are all excluded but I don't know why.

I attach some screenshots with the geometry , the mesh preview and the simulation outcomes.

Please let me know

Thank you!

![geometry](https://user-images.githubusercontent.com/30264796/28839273-00a92ef0-76eb-11e7-9429-0136cf757c7e.JPG)

![testing mesh](https://user-images.githubusercontent.com/30264796/28839282-08d1a8a0-76eb-11e7-9cc8-a8bf43701f49.JPG)

![mesh preview](https://user-images.githubusercontent.com/30264796/28839289-1068a410-76eb-11e7-84b6-9b19273a68fe.JPG)

![mesh preview 2](https://user-images.githubusercontent.com/30264796/28839300-17b82f92-76eb-11e7-9544-9f82e9214345.JPG)

![results](https://user-images.githubusercontent.com/30264796/28839315-1f60b020-76eb-11e7-8d29-973aa39a173e.JPG)

**Comment by mostaphaRoudsari** [comment]
Solved here: https://github.com/ladybug-tools/butterfly/issues/258
