### ISSUE TITLE
Error : Fail to read simpleFoam.log 

### ISSUE THREAD

**Issue by HBLHBL** [ladybug-tools/butterfly#266]
Hello,

I'm trying to run my first outdoor simulation based on the exemple file but with my own geometry. Blockmesh and Snappyhexmesh seem to work ok. But when I run the solution, I get the following error : 

```
Preparing OpenFOAM CASE: V1_30_6 for SteadyIncompressible study...
docker-machine env
docker-machine env
Butterfly is running simpleFoam. PID: None
Failed to read C:\Users\Hugo\butterfly\V1_30_6\log\simpleFoam.log:
	[Errno 2] Le fichier 'C:\Users\Hugo\butterfly\V1_30_6\log\simpleFoam.log' est introuvable.: C:\Users\Hugo\butterfly\V1_30_6\log\simpleFoam.log
Failed to read C:\Users\Hugo\butterfly\V1_30_6\log\simpleFoam.err:
	[Errno 2] Le fichier 'C:\Users\Hugo\butterfly\V1_30_6\log\simpleFoam.err' est introuvable.: C:\Users\Hugo\butterfly\V1_30_6\log\simpleFoam.err
done!
```

So simpleFoam.log and simpleFoam.err are apparently missing. At what stage should those files being created ? I was able to run the example file with its included geometry without getting that error.

Any idea ?

**Comment by mostaphaRoudsari** [comment]
We just released a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

**Comment by bgabriela** [comment]
Error : Fail to read simpleFoam.log 

Hello,

I'm trying to run a outdoor simulation based on the exemple file with my own geometry. Blockmesh and Snappyhexmesh worked ok,  i checked the mesh in Paraview. But when I run the solution, I get the following error :

Solution exception:Failed to parse C:\Users\.....\log\simpleFoam.log:
	[Errno 2] Could not find file 'C:\Users\.....\log\simpleFoam.log'.: C:\Users\....\log\simpleFoam.log

I have bluecfd installed, and i ran the simulation on multiple CPUs, it just went until 20 and then gave me this error in the residuals plots report. I installed and running everyting on a bootcamp windows.

Any ideas? thank you very much.

**Comment by nasrin-balaghi** [comment]
hi, I have the same problem. could you solve it?
