### ISSUE TITLE
Modifying WindTunnel dimensions

### ISSUE THREAD

**Issue by lucadvn** [ladybug-tools/butterfly#267]
Hello

I am trying to run an analysis over an airplane wing but I am facing a challenge. 
The problem is that I need to be able to define a parameter for the ground location of the wing tunnel. I want to define the ground face of the tunnel by mirroring the top face, or something similar. 
I have been reading thru your code and I found that you define each face of the tunnel in wingtunnel by selecting a set of vertices and then applying some transformations. I also found that on the boundaryconditions script you define the ground as wall together with the inlet but the other faces are set as "patch". I also found that to define the wind vector you are defining something like 
WV = [wind[0], wind[1], 0] and I need to have a vertical component of the wind to simulate the wing flying with an angle of attach. 

So I went into each script and try to manually redifine the ground location, boundary condition and wind vector, but when I then try to run butterfly on GH I get some erros refering to the lines where the libraries get imported. I believe it has something to do with the way I modify the scripts but I have gone back at it and cant see where the problems are

I know is too much to ask but hoppefully you can guide me to a way of fixing/modifying this settings. 

Luca

**Comment by mostaphaRoudsari** [comment]
Hi @lucadvn,

I'm not sure if I understand what are you exactly trying to do here but sounds like in this case you can create the wind tunnel similar to an interior case which will give you the freedom of changing the boundary condition for each and every surface.

If that won't help, can you share a little bit more information with some graphics and links to the lines of the code that should be modified?  For instance [these are the lines](https://github.com/ladybug-tools/butterfly/blob/master/butterfly/windtunnel.py#L87-L108) that calculate the coordinates for the wind tunnel.

**Comment by lucadvn** [comment]
Hi Mostapha,
Thanks for getting back to me and for all your help and support

We are running a simulation on a box wing
![boxwing](https://user-images.githubusercontent.com/30696787/29784144-d48a95c8-8bd7-11e7-8953-c8e9b5479287.JPG)

One of the first concerns is that the initial wind velocities seem to vary as we move away from the ground. We believe this is because of the ground bounday condition. We are trying to fix that but this is a visual of what it is happening
![wechat image_20170828101529](https://user-images.githubusercontent.com/30696787/29784894-898f991c-8bda-11e7-98b4-959820dc42d0.png)
![wechat image_20170828101525](https://user-images.githubusercontent.com/30696787/29784906-911eb6cc-8bda-11e7-8120-8d619e884195.png)



So far working with the outdoor case has lead to the following results. There is a lot of variability on the results from simulation to simulation and was wondering if you can give us some insight into what may be happening. 
Also it seems OpenFoam is calculating some really high values at some points which then blows the color scale and the visualization of the results become really hard. 
![wechat image_20170828101515](https://user-images.githubusercontent.com/30696787/29784824-54ec289c-8bda-11e7-874d-5c2c808e5fc1.png)
![wechat image_20170828101535](https://user-images.githubusercontent.com/30696787/29784835-5c071b14-8bda-11e7-8a26-c8de32fb560d.png)


Also when importing the results to Paraview the mesh which gets imported looks more like a low resolution block mesh even tho we ran our simulation using fine snappymesh. 
![temp](https://user-images.githubusercontent.com/30696787/29785608-126809ac-8bdd-11e7-8022-fab3cf875e32.jpg)

We are currently trying to work with the interior case and see if we get better results.

Thanks

**Comment by Vinc83** [comment]
Any news about this point? I have the same problem too.

**Comment by mostaphaRoudsari** [comment]
Try update blockMeshDict component. It will let you to define the blockMesh with 8 points:

![image](https://user-images.githubusercontent.com/2915573/53279816-a2e57900-36e1-11e9-8c7b-dca7ad431cd7.png)
