### ISSUE TITLE
Failed to load probes

### ISSUE THREAD

**Issue by NallaV** [ladybug-tools/butterfly#268]
Hi there,

I am using Butterfly to run a medium scale urban simulation. I manage to run it and get results but I cannot load the probes. I opened the case in Paraview and the results definitely exist but Butterfly fails to find the probes and gives the following error:

"Solution exception:Failed to load values: Failed to find probes folder folder at C:\Users\nala.ber\butterfly\x5\postProcessing\probes"

When I check the case folder there is no "PostProcessing\probes" directory. Anyone ever run into this problem or any ideas what might be wrong? Thank you!

**Comment by TheodoreGalanos** [comment]
Hi @NallaV the postProcessing folder is the one OF creates when the probes (or other) function object is used during run time. If the folder is not there it would seem that your probe function object was not run correctly or not run at all.

Are you certain you included it when you were setting up the case? Could you re-run the BF definition you used, in another folder(name), and double-check it is creating the probes function object?

Kind regards,
Theodore.

**Comment by NallaV** [comment]
Hi Theodore. Thank you for the quick reply.  I added the probes after the simulation run the first time. It looked like it re-run when I connected the probes but as you say probably it didn't run properly. 
I though it is possible to add different sets of probes later and check different results but I guess this is not the case. Anyway, I wanted to avoid deleting 40G of data and re-run the case clean but this is what I am doing now and the Postoprocessing folder is there. Thank you for the help.

**Comment by TheodoreGalanos** [comment]
Hi @NallaV I am sorry you have to re-run. Actually, these are run-time function objects so you can still add them to the simulation later, but they will only output values of times that are run (depending on the frequency you put). 

Good luck with your study!
