### ISSUE TITLE
Writing solution should be possible even if the docker is not installed

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/butterfly#272]
This is useful for workflows that someone only wants to export the case and run it somewhere else.

**Comment by TheodoreGalanos** [comment]
Yes, this is very good and would help a lot of users running thins in Linux. Additionally, if possible, we need a way to write blockMeshDict, snappyHexMeshDict, decomposeParDict, surfaceFeatureExtractDict (whole system folder maybe) without the user needing to actually run blockMesh and snappyHexMesh components. I'm currently running/canceling when I only want to extract to linux.

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos see https://github.com/ladybug-tools/butterfly/issues/273

**Comment by mostaphaRoudsari** [comment]
This has been already addressed by adding a write only option to the workflow.
