### ISSUE TITLE
Show the streamlines in Rhino or Paraview

### ISSUE THREAD

**Issue by lamlvo** [ladybug-tools/butterfly#276]
Could anyone know how to show the streamlines in Rhino or Paraview. I try to follow many tutorial with the paraview. But It's like the result from butterly cannot show that. Do I need to put the command line in butterfly or what I need to do?
![streamline](https://user-images.githubusercontent.com/30365572/29936531-cb60384a-8eac-11e7-920f-f88291d64b74.PNG)
![streamline2](https://user-images.githubusercontent.com/30365572/29936532-cb606220-8eac-11e7-8289-189cee7992ca.PNG)

Thank you,

**Comment by mostaphaRoudsari** [comment]
@lamlvo we doesn't have the functionality to create such visualization inside Rhino but it's totally possible to do in ParaView. What's the error that you get in ParaView.

**Comment by lamlvo** [comment]
Hi @mostaphaRoudsari ,
Thank you for your reply. Yes, this was my mistake. When I loaded the Openfoam into the paraview. I deseleted the inner mesh, (only selected 3D model). So It can not show the result. After read your comment and I try again. Now everything is great now.
Thank you,
![streamline](https://user-images.githubusercontent.com/30365572/29953213-6d0f6f76-8ef8-11e7-823a-ce07c6965ae6.PNG)
