### ISSUE TITLE
Rhino will crash when running the outdoor airflow simulation with BF

### ISSUE THREAD

**Issue by silentbell** [ladybug-tools/butterfly#278]
Hi, Guys!
I tried to run an outdoor airflow simulation with Butterfly. My GH file was created based on the case file, and the case file could run correctly on my computer. When I run my GH file, several iterations were calculated and the Rhino crashed. 
If the size of my model is too big to be calculated? Any advice will be appreciated.
Roy
My GH file is attached on this link
http://www.grasshopper3d.com/group/ladybug/forum/topics/rhino-will-crash-when-running-the-outdoor-airflow-simulation-with

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
