### ISSUE TITLE
SnappyHexMesh Error- wrong token type

### ISSUE THREAD

**Issue by krockwell1110** [ladybug-tools/butterfly#279]
I am able to run snappyhexmesh in the indoor airflow example without an error but when running the outdoor airflow example I get the attached error message:

wrong token type - expected int32_t, found on line 107 the word 'L'

I am running Butterfly with OpenFoam 1706, docker is running correctly. I am hoping for some feedback on what this error could be related to. Thanks
[SHM_Error.txt](https://github.com/ladybug-tools/butterfly/files/1344854/SHM_Error.txt)

**Comment by TheodoreGalanos** [comment]
Hi @krockwell1110 

It seems that somehow instead of the level of refinement in your refinement regions you have the letter 'L'. Can you please check the input of the refinement region levels in GH and make sure it is a number?

After that, please try deleting the folder completely and starting over.

Let us know if there is still an issue, and please share the GH file if possible.

Kind regards,
Theodore.

**Comment by krockwell1110** [comment]
[01_0_outdoor_airflow_KR.zip](https://github.com/ladybug-tools/butterfly/files/1344912/01_0_outdoor_airflow_KR.zip)
I believe the refinement region inputs are all numbers, here is my GH file.

**Comment by lamlvo** [comment]
I had the same issue. It automaticly adds "L". As you see:
   refinementRegions
    {

        around_buildings_area
        {

            levels		((1000000000000000L  3) );

            mode		inside;

        }

    }

What I did to solve it. Just pull the update butterfly component and run it. Or you can re-install butterfly.
I don't know how but it can fix it in my case. Hope it works in your case.

Best,

**Comment by mostaphaRoudsari** [comment]
This is the difference between long and integer in Python: https://stackoverflow.com/a/2104947/4394669

Do you really need such a large number for refinement levels? Your input value is larger than `sys.maxint` which is equal to 2,147,483,647 on my machine.

**Comment by TheodoreGalanos** [comment]
Hi @mostaphaRoudsari I believe this was BF's value. OF doesn't really care about the first value, so it assigns a large placeholder value which is usually set at 1E15. Could this be leading to issues? Not sure why now though.

**Comment by krockwell1110** [comment]
@lamlvo I get an error when I try to update my butterfly, maybe it is because I am already using the most up to date version 0.0.04 so unfortunately I could not try your solution. see error below:
![image](https://user-images.githubusercontent.com/32395001/31093495-833e4d3e-a777-11e7-94bf-fb2eadd7cf62.png)
@mostaphaRoudsari I did not change anything in the provided outdoor airflow example file and am not sure what input is defining the large number of refinement levels, what I have found is that I cannot use the locationRefMode for my refinement region that was part of the original example file; by swapping the locationRefMode with distanceRefMode I was able to run snappyhexmesh without the error initially reported, so I guess that is the workaround I found.

Thanks!

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos thanks! Yes. [It's my own input](https://github.com/ladybug-tools/butterfly/blob/75af51a20fb219a6b39102c34f960de2fed0ad51/butterfly/refinementRegion.py#L116) and I don't know why it only shows up on some systems.

@krockwell1110 look [here](http://discourse.ladybug.tools/t/got-error-while-updating-butterfly/2136/2) for the solution. Your workaround is not really a  workaround but a different method for creating a refinement region. Let me know if updating didn't solve the issue.

**Comment by krockwell1110** [comment]
After updating successfully I am still seeing my original issue. If I manually edit the snappyHesMeshDict file in my case's system folder to delete the 'L' that appears then I can continue with the simulation

**Comment by mostaphaRoudsari** [comment]
@krockwell1110 for now you can open the refinementRegion.py file and change line 116 to `_RefinementMode.__init__(self, ((1000000, int(level)),))`. Then close both Rhino and Grasshopper and start over. It should fix the problem.

**Comment by krockwell1110** [comment]
I did make the change to the script, restarted my computer and tried again but am getting the same error. Just to double check, the location where I edited the refinementRegion.py file  was C:\Users\krockwell\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly

**Comment by mostaphaRoudsari** [comment]
@krockwell1110 did you close both Rhino and Grasshopper and created a new case folder?

What if you change the input to a string like this: `_RefinementMode.__init__(self, (('1e15', int(level)),))`

I can't recreate this error to test it on my machine.

**Comment by krockwell1110** [comment]
Yes, I have tried after closing Rhino/Grasshopper and shutting down my machine entirely with a new case name/folder. Changing the input to a string '1e15' also does not fix it

**Comment by TheodoreGalanos** [comment]
@krockwell1110 

Can you please update Butterfly, reload Rhino/Gh and try again?

I believe this should be fixed by now.

Please let us know.

Kind regards,
Theodore.

**Comment by krockwell1110** [comment]
Yes, the new update fixed the error. Thanks for the troubleshooting!

**Comment by TheodoreGalanos** [comment]
@krockwell1110 No problem! Thanks for reporting back.

Regards,
Theodore.
