### ISSUE TITLE
Residual Control not working

### ISSUE THREAD

**Issue by gamemakerh** [ladybug-tools/butterfly#282]
I've try to constrain residuals to have quicker convergence but this approach is not working for me
I'm using 2D simulation approach. this is not working maybe of this ?

Maybe someone can guide me because I'm have no idea what should I do...

![residual_control_solving_block](https://user-images.githubusercontent.com/4093017/31496881-cbb8645a-af65-11e7-8ee4-735789242e22.PNG)
![residual_control_residula](https://user-images.githubusercontent.com/4093017/31496907-e13b80d2-af65-11e7-823f-e7f92977da11.PNG)

**Comment by TheodoreGalanos** [comment]
Hi @gamemakerh 

Can you post the contents of the case's fvSolution file? It's in your system folder. Also, I'm not sure you need to include nut/alpha

Kind regards,
Theodore.

**Comment by gamemakerh** [comment]
@TheodoreGalanos 
/*--------------------------------*- C++ -*----------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  v1706+                                |
|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
/* Butterfly 0.0.4                https://github.com/ladybug-tools/butterfly *\
\*---------------------------------------------------------------------------*/
FoamFile
{
	version		4.0;
	format		ascii;
	class		dictionary;
	location	"system";
	object		fvSolution;
}

solvers
{

    U
    {

        relTol		0.1;

        tolerance		1e-8;

        nSweeps		1;

        smoother		GaussSeidel;

        solver		smoothSolver;

    }

    k
    {

        relTol		0.1;

        tolerance		1e-8;

        nSweeps		1;

        smoother		GaussSeidel;

        solver		smoothSolver;

    }

    epsilon
    {

        relTol		0.1;

        tolerance		1e-8;

        nSweeps		1;

        smoother		GaussSeidel;

        solver		smoothSolver;

    }

    p_rgh
    {

        relTol		0.01;

        solver		PCG;

        preconditioner		DIC;

        tolerance		1e-08;

    }

    T
    {

        relTol		0.1;

        tolerance		1e-8;

        nSweeps		1;

        smoother		GaussSeidel;

        solver		smoothSolver;

    }

}

SIMPLE
{

    nNonOrthogonalCorrectors		2;

    residualControl
    {

        nut		0.001;

        p_rgh		1e-4;

        k		0.001;

        U		0.001;

        T		0.001;

        p_rhg		0.001;

        epsilon		0.001;

        alphat		0.001;

    }

    pRefValue		0;

    pRefPoint		(-6.700436475707639 -2.3008366515174576 0.5);

}

relaxationFactors
{

    p_rgh		0.3;

    k		0.7;

    U		0.7;

    T		0.5;

    epsilon		0.7;

}

**Comment by gamemakerh** [comment]
And this is  solver output. you  can see that residual control is 0.001 and not 1e-05 but solution do not stopping at these values.
-----------------

/*---------------------------------------------------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  v1706                                 |
|   \\  /    A nd           | Web:      www.OpenFOAM.com                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
Build  : v1706
Arch   : "LSB;label=32;scalar=64"
Exec   : buoyantBoussinesqSimpleFoam
Date   : Oct 12 2017
Time   : 12:34:23
Host   : "default"
PID    : 21316
Case   : /home/ofuser/workingDir/butterfly/Duct_Simulation430oclock
nProcs : 1
sigFpe : Enabling floating point exception trapping (FOAM_SIGFPE).
fileModificationChecking : Monitoring run-time modified files using timeStampMaster (fileModificationSkew 10)
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Create time

Create mesh for time = 0


SIMPLE: convergence criteria
    field nut	 tolerance 0.001
    field p_rgh	 tolerance 0.0001
    field k	 tolerance 0.001
    field U	 tolerance 0.001
    field T	 tolerance 0.001
    field p_rhg	 tolerance 0.001
    field epsilon	 tolerance 0.001
    field alphat	 tolerance 0.001

Reading thermophysical properties

Reading field T

Reading field p_rgh

Reading field U

Reading/calculating face flux field phi

Selecting incompressible transport model Newtonian
Creating turbulence model

Selecting turbulence model type RAS
Selecting RAS turbulence model RNGkEpsilon
RAS
{
    RASModel        RNGkEpsilon;
    turbulence      on;
    printCoeffs     on;
    Cmu             0.0845;
    C1              1.42;
    C2              1.68;
    C3              0;
    sigmak          0.71942;
    sigmaEps        0.71942;
    eta0            4.38;
    beta            0.012;
}

Reading field alphat


Reading g

Reading hRef
Calculating field g.h

No MRF models present

Radiation model not active: radiationProperties not found
Selecting radiationModel none
No finite volume options present


Starting time loop

**Comment by TheodoreGalanos** [comment]
Seems like the p_rgh value is twice there, pretty sure OF will use the 10-4. Can you show your final residual again? You can do that by re-running the final case and increasing end time by 1.

**Comment by gamemakerh** [comment]
I am pretty sure that OF waiting for 1e-05 residuals, but not 1e-03 or 1e-04. 
Maybe do you know  where I could find manual for this block ? 
I'm advanced user on CFD, but I'm new in BF.

**Comment by TheodoreGalanos** [comment]
OF seems to have gotten your BF settings right, as you can see in the start of your run log:

```
SIMPLE: convergence criteria
field nut	tolerance 0.001
field p_rgh	tolerance 0.0001
field k	tolerance 0.001
field U	tolerance 0.001
field T	tolerance 0.001
field p_rhg	tolerance 0.001
field epsilon	tolerance 0.001
field alphat	tolerance 0.001SIMPLE: convergence criteria
field nut	tolerance 0.001
field p_rgh	tolerance 0.0001
field k	tolerance 0.001
field U	tolerance 0.001
field T	tolerance 0.001
field p_rhg	tolerance 0.001
field epsilon	tolerance 0.001
field alphat	tolerance 0.001
```

Notice the double p_rgh value, guessing here it smallest one (10e-4) wins?

**Comment by gamemakerh** [comment]
ok I'm idiot.  I made typo. 

p_rgh ---> p_rhg

**Comment by TheodoreGalanos** [comment]
Aha! I totally missed that too!

Good to know. I'll close this one if it is working now. Please feel free to re-open if you rerun the case and you see it recurring.

Thanks!

Kind regards,
Theodore.

**Comment by gamemakerh** [comment]
everything is fine. I've made various tests. working flawlessly ;]
