### ISSUE TITLE
Error: Failed to import butterfly

### ISSUE THREAD

**Issue by massimoromanato** [ladybug-tools/butterfly#287]
Hello! I installed OpenFOAMv1612 succesfull, then i installed butterfly with the .gh installation file, but when i use any butterfly component it gives me this error:

1. Solution exception: Failed to import butterfly: no module named version

I tried to reinstall butterfly 4-5 times, I also tried to copy manually the userobjects but it still doesn't work.
Anyone know how to fix it? thanks

![immagine](https://user-images.githubusercontent.com/26818493/32045730-4c1a98b2-ba41-11e7-928f-afa312ae43bc.png)

**Comment by devngc** [comment]
Hi, 
Can you please post this on discourse.ladybug.tools?

**Comment by mostaphaRoudsari** [comment]
@massimoromanato, did you solve this issue? I second @devngc's suggestion to post this to discourse.

**Comment by FULADLU** [comment]
Hello, i face with same problem i use Open_Form 1712
i cant start butterfly its always tell me 
Solution exception: Failed to import butterfly: no module named version
![untitled](https://user-images.githubusercontent.com/38980883/39627784-36d10df4-4fbc-11e8-91a4-d6f9f777654d.png)

Any idea for that?

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
