### ISSUE TITLE
openFOAM start_error   #openFOAM installation

### ISSUE THREAD

**Issue by sajjadsaeedi** [ladybug-tools/butterfly#288]
hi
I faced this error . how can I get rid of that?
thank you all
sajjad
![untitled](https://user-images.githubusercontent.com/31283604/32159287-1769d936-bd0a-11e7-817b-d53965f6509b.png)

**Comment by sajjadsaeedi** [comment]
how can we get rid of this error : Host does not exist : "default "

**Comment by mostaphaRoudsari** [comment]
See here: https://github.com/ladybug-tools/butterfly/wiki/Windows-10-Installation-Notes#installing-openfoam-on-a-pc-using-windows-10
It's not installed correctly and you need to install the image manually.

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.

**Comment by sajjadsaeedi** [comment]
thank you so much.....
    On Saturday, February 23, 2019, 4:49:43 AM GMT+3:30, Mostapha Sadeghipour Roudsari <notifications@github.com> wrote:  
 
 
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.
   
   - Try downloading the newer version 0.0.05 from Food4Rhino. Use the installer file to remove the old version and install the new one.
   - Install BlueCFD-core following this link.
   - Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly installation package.

Feel free to open a new issue if it didn't solve the problem.
