### ISSUE TITLE
refinement region

### ISSUE THREAD

**Issue by RehabZakria** [ladybug-tools/butterfly#289]
Hello all,
i am starting a butterfly outdoor airflow analysis using the example file ( 01_0_outdoor_airflow) ... 
everything was going as well , 

i  defined new breb - changing wind speed & wind vector 
Runing ( BLOCKMESH) , (VISUILSEMESH) && (SNAPPYHEXMESH) everything good no errors, but the analysis done in a small region as shown in the picture , i can't find my mistake.

![capture](https://user-images.githubusercontent.com/33383827/32411309-2479fa0e-c1e0-11e7-8e95-f4dd93fb59f0.jpg)

Thank you in advance.

**Comment by gamemakerh** [comment]
Check is all your geometries are transformed to butterfly geometries and connected to case from geometries block.

**Comment by RehabZakria** [comment]
Hello Gamemakerh , 
Thank you for your replay but its my first time to use Rhino&Grasshopper , really i can't catch you ,can you tell me how can i transform geometries  to butterfly geometries?

**Comment by mostaphaRoudsari** [comment]
@RehabZakria, did you watch the introduction to butterfly videos? In any case, this question should be posted to discourse (discourse.ladybug.tools) not here on GitHub.
