### ISSUE TITLE
A new mobile software

### ISSUE THREAD

**Issue by thinklikeanarchitect** [ladybug-tools/butterfly#291]
Hi,

I have developed a mobile software for wind-building interaction analyses. It's based on Navier Stokes equations which is solved on distinct particles. Actually, a flow of particles emitted from a source like in the wind tunnel, then these particles interact with each-other and the solid surfaces based on the equations. 

![urbananalyses](https://user-images.githubusercontent.com/22752273/32536935-94cd935e-c471-11e7-9771-d6db08c47acf.PNG)

ArchPLUS (Architecture Plus) is an architectural modelling and analyses tool with too many modules. The term "plus" denotes for wind, solar and fire evacuation (AI based) simulations.

You may easily model basic architectural geometries in 2D and 3D. Augmented reality (AR) based drawing mode makes the "3D modelling" process much more enjoyable with real shadows and real physics. **It is possible to import any 3D model (*.obj) to this app and then run all of the simulations.**

![3d](https://user-images.githubusercontent.com/22752273/32536947-a3fe3d42-c471-11e7-998e-7960ddbeb7a6.JPG)

This app can be even used solely to view 3D models in your mobile phone in 2D and 3D AR environment. However, ArchPlus has a bunch of extra features. You may conduct wind analyses, and also "Solar Study" with specifying latitude, longitude and other parameters. Moreover, it is also possible to conduct "Fire Evacuation Simulations" based on AI (artificial intelligence).

![importfunction](https://user-images.githubusercontent.com/22752273/32536968-bfc3673c-c471-11e7-964f-9f1caaf1a79d.PNG)

The unique 3D modelling algorithm works very fast and easy to be get adapted. The Graphical User Interface is very easy to get which button makes what, besides the help screen is interactively shows button functions.

![helpscreen](https://user-images.githubusercontent.com/22752273/32536984-d52d1b90-c471-11e7-9b83-88606210d96f.PNG)

Real-time airflow can be visualised with streamlines changing in size and color in adaptation with speed. This app is developed for wind engineers, mechanical engineers and architects desire to solve fluid - solid interaction with Navier - Stokes equations. The airflow around 3D geometries can be seen in high resolution thanks to faster convergence technics and cutcell mesh type. Multiple storey buildings can be modelled and analysed. For analysis of different storeys, cut plane slider tool is developed to move wind tunnel analysis plane. This tool change the wind tunnel plane to horizontal or vertical, as well. In brief, this app make the user understand Computational Fluid Dynamics basics and nature of the wind in real-time with the virtual geometries cast on the real surfaces.

**Comment by gamemakerh** [comment]
very nice indeed.  the newest version is 6.1.1 ?
I would like to try this out.

**Comment by thinklikeanarchitect** [comment]
Thx a lot, newest version is 7.1. There are lots of changes after 6.1.1.

**Comment by thinklikeanarchitect** [comment]
https://itunes.apple.com/tr/app/archplus/id1294661346?mt=8

Actually I couldn't make it free but its sold in a very affordable price. Because I should pay to Apple for developer account every year. So, as an academician I don't aim to earn money from this, but at least I am trying to pay Apple to make the software available on the Appstore. Thanks for your support.

https://itunes.apple.com/tr/app/archplus/id1294661346?mt=8

https://play.google.com/store/apps/details?id=com.ituwind.realtimeairflowpro

**Comment by mostaphaRoudsari** [comment]
@thinklikeanarchitect I'm going to close this for now. Feel free to open a new issue if you have new version/announcement
