### ISSUE TITLE
Can not run wind tunnel

### ISSUE THREAD

**Issue by bhz19970224** [ladybug-tools/butterfly#294]
I try to run wind tunnel in grasshopper , but it says" Solution exception:In order to run OpenFOAM using butterfly you must use an admin account or run the program as administrator." So i close rhino and grasshopper and run Rhino as administrator , and now i can't open document in grasshopper , and it says "1. Solution exception:list.index (item): item not in list！" Somebody help me please , i really need it in my architecture design program .

![default](https://user-images.githubusercontent.com/33739932/32926189-cb6a66e2-cb80-11e7-9750-dd2cfa02f06f.PNG)

**Comment by mostaphaRoudsari** [comment]
You need to post more information for us to being able to help. What did you change in the model? Did you check all your inputs? Can you connect a panel to the readMe! output and post the full error message?

**Comment by bhz19970224** [comment]
I already run openForm as administrator . And i open the document (01_0_outdoor_airflow) in examplefiles without change anything .Then i click the button in wind tunnel to run it , and it turn into red .
![_20171117105848](https://user-images.githubusercontent.com/33739932/32927219-514bf802-cb86-11e7-82ba-4682138fdbd5.jpg)

![_20171117105658](https://user-images.githubusercontent.com/33739932/32927230-671d27c8-cb86-11e7-9c1d-d569b4cd0954.jpg)
error:Solution exception:In order to run OpenFOAM using butterfly you must use an admin account or run the program as administrator . 
So i close rhino and grasshopper and run Rhino as administrator . And now i can't open document in grasshopper .
![_20171117110159](https://user-images.githubusercontent.com/33739932/32927301-c10d2378-cb86-11e7-81d9-da901ed06ffa.jpg)

**Comment by bhz19970224** [comment]
![_20171117113026](https://user-images.githubusercontent.com/33739932/32928028-ef661bf4-cb8a-11e7-8e0e-fc9ed488c1b4.jpg)

**Comment by gamemakerh** [comment]
you can just copy all the logs without making screens.  (use panel tool)

**Comment by bhz19970224** [comment]
Hi~ @gamemakerh , thanks for your advice, but when i use panel tool to open the document , it all turn to red .
error:1. Solution exception:list.index(item): item not in list

![_20171117164017](https://user-images.githubusercontent.com/33739932/32938279-9f173f1c-cbb6-11e7-8d9d-218a4c881279.jpg)

![_20171117164009](https://user-images.githubusercontent.com/33739932/32938283-a385021e-cbb6-11e7-9e05-58e103142021.jpg)

**Comment by mostaphaRoudsari** [comment]
@bhz19970224, we understand that you're having an issue with the component. To help you with the problem we need to see the full error report and not the partial error message. You can use Grasshopper `Panel` component to get the full error message. It's located under Params > Input.

![image](https://user-images.githubusercontent.com/2915573/32955342-acef662e-cb83-11e7-8536-6fd2b3413399.png)

**Comment by bhz19970224** [comment]
@mostaphaRoudsari Hi~ 
![2](https://user-images.githubusercontent.com/33739932/32989029-33a9b0b6-cd4b-11e7-9c0f-97a3319489a6.PNG)

This is the full error report while i run rhino without as a administrator

![default](https://user-images.githubusercontent.com/33739932/32989072-929c278e-cd4b-11e7-869d-e5d88c5d2806.PNG)

And this is the full error report while i run rhino as a administrator.

**Comment by mostaphaRoudsari** [comment]
@bhz19970224 the second image is what we need. Thanks.
The error message doesn't tell us much about the issue. It seems there is something wrong before this component. Why all the input wires are empty? They are orange. Do you get an error from the components before this one?

**Comment by bhz19970224** [comment]
@mostaphaRoudsari  Thanks for your help ,in second image, while i run rhino as administrator ,all the component's error message are same.
![3](https://user-images.githubusercontent.com/33739932/32998917-cb6cb072-cdd9-11e7-8cb1-27807fa0ff0f.PNG)

**Comment by architortoise** [comment]
I am also having a problem running Wind Tunnel. The installation of OpenFoam was a bit hectic, but I just got it to work. I tried running the Outdoor Sample file and the Block Mesh component threw an error. I closed Rhino and GH then I fixed the error using the edits to the scripts shown [here](https://github.com/ladybug-tools/butterfly/commit/917b50c83043456d6304dd28561991557820dba9). 
I re-opened Rhino (as Admin) and gh but now it's throwing the attached errors regarding the wind tunnel. 
![capture](https://user-images.githubusercontent.com/34125754/33425314-5c695f80-d58c-11e7-8b0c-f801e519e262.JPG)

Any help you can provide would be awesome.

**Comment by mostaphaRoudsari** [comment]
@architortoise, you have made a mistake in editing the file in line 6 of `case.py`. I will push a new version of Butterfly to master soon which has all these issues already fixed.

**Comment by omidali82** [comment]
salam rozeton bekhyer man har kari mikonam nemitonam  algoritm amade ro kar koonam nemidonam chera?mamnon misham komakam konin
![01](https://user-images.githubusercontent.com/40669516/42448100-51f555e6-8391-11e8-9db9-77549effb424.jpg)

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
