### ISSUE TITLE
Docker Install

### ISSUE THREAD

**Issue by cbothma** [ladybug-tools/butterfly#307]
Hi, we run enterprise edition of Win 10. We can get OpeFoam to run in Win 10 environment (outside of Docker install, using the Linux Bash Shell - https://openfoam.org/download/windows-10/) but cannot get it to run with default Docker/OpenFOAM installer. Admin rights, etc all set. Bellow the error message. Any thoughts?

Thank you 

![docker_error](https://user-images.githubusercontent.com/29097130/33433009-f3076e10-d5d1-11e7-9013-9ba33cd074c5.JPG)

**Comment by mostaphaRoudsari** [comment]
Based on the error the image is not successfully downloaded during the installation. Follow [this link](https://github.com/ladybug-tools/butterfly/wiki/Windows-10-Installation-Notes#installing-openfoam-on-a-pc-using-windows-10) to download it manually.

**Comment by cbothma** [comment]
Thanks Mostapha, I think there's an issue with VirtualBox...trying to resolve that...

**Comment by chrisdmp** [comment]
Hi cbothma, did you manage to overcome the problem with virtual box and how?

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
