### ISSUE TITLE
Large neighborhood CFD simulation

### ISSUE THREAD

**Issue by AlphaArsano** [ladybug-tools/butterfly#308]
Butterfly creators thank you for the amazing work!
I am working on a neighborhood study for the prediction of natural ventilation potential. I have a land size of about 2km by 1km. Do you think it is possible to use butterfly for such size? Or do you recommend to work with a scaled model?

**Comment by mostaphaRoudsari** [comment]
Hi @AlphaArsano, if you have the computing power to handle millions of cells butterfly/openfoam has no limitation size.
Also keep in mind the Butterfly creates an ABL condition for inlet which is set for a real scale model. If you're going to use an scaled model you need to modify several settings including the inlet boundary condition.

**Comment by AlphaArsano** [comment]
Thank you @mostaphaRoudsari. This is helpful.
