### ISSUE TITLE
Failed to find container id WITH openFOAM V1706 and butterfly 0004

### ISSUE THREAD

**Issue by Farzad67** [ladybug-tools/butterfly#309]
Hello Guys and @mostaphaRoudsari ,
I faced this error when running Blockmesh, I read about it on other issues but couldn't fix it (I think they were related to V16 open foam not 17).
My windows is 10 and I am using openfoam v1706 with butterfly 0004. I run all of them as administrator.
can anyone help me? 
Thanks.
![img_0703](https://user-images.githubusercontent.com/34173991/33506749-cec87a22-d6b6-11e7-8eed-bc14b237e9ef.jpg)

![screen shot 12-01-17 at 04 38 pm](https://user-images.githubusercontent.com/34173991/33506633-60bbc49e-d6b6-11e7-9cd2-7fe5a1f6a182.PNG)

![screen shot 12-01-17 at 04 47 pm](https://user-images.githubusercontent.com/34173991/33506906-6e2e3444-d6b7-11e7-9f87-c9ee30549e36.PNG)

**Comment by Farzad67** [comment]
![screen shot 12-01-17 at 04 47 pm](https://user-images.githubusercontent.com/34173991/33506884-4b14a402-d6b7-11e7-8360-2b330992104b.PNG)

**Comment by mostaphaRoudsari** [comment]
You need to update butterfly installation to work with OpenFOAM1706.

**Comment by Farzad67** [comment]
Dear @mostaphaRoudsari 
Thanks for your response. I already installed this version (Butterfly 0.0.04) that I assumed is the latest one. Please let me know if there is any more updated version.
![screen shot 12-01-17 at 10 28 pm](https://user-images.githubusercontent.com/34173991/33511777-6c671858-d6e7-11e7-9e9f-ccb2446f0784.PNG)

**Comment by Farzad67** [comment]
Dear @mostaphaRoudsari 
I am still waiting for you to tell me how should I update butterfly installation while I already installed version 0.0.04. I assumed that was the latest one.
Thanks,

**Comment by mostaphaRoudsari** [comment]
@Farzad67, Sorry for the delayed reply. See here. You can use Butterfly component to update the installation. You may need to remove the current installation manually before the update.
http://discourse.ladybug.tools/t/got-error-while-updating-butterfly/2136

**Comment by mostaphaRoudsari** [comment]
I assume this is solved by using the update component. Feel free to reopen if there is still an issue with updating.
