### ISSUE TITLE
error Docker_Quickstart_Terminal 

### ISSUE THREAD

**Issue by hamedsangin** [ladybug-tools/butterfly#310]
![a](https://user-images.githubusercontent.com/34301946/33665399-0fcf630c-daac-11e7-82b1-41e4cb877365.jpg)
OF_Env_Create error " host does not exist :"default  "

**Comment by mostaphaRoudsari** [comment]
@hamedsangin, have you seen this: https://github.com/ladybug-tools/butterfly/wiki/Windows-10-Installation-Notes#installing-openfoam-on-a-pc-using-windows-10
