### ISSUE TITLE
OpenFOAM installtion error

### ISSUE THREAD

**Issue by hamedsangin** [ladybug-tools/butterfly#311]
![b](https://user-images.githubusercontent.com/34301946/33678508-280e6aec-dad1-11e7-99ef-1696c2ed209e.jpg)
when i run OpenFOAM_Start , this window open and close automatically

**Comment by mostaphaRoudsari** [comment]
Already replied here: https://github.com/ladybug-tools/butterfly/issues/310#issuecomment-349996458

**Comment by mostaphaRoudsari** [comment]
Duplicate with #312
