### ISSUE TITLE
Docker Quickstart Terminal error

### ISSUE THREAD

**Issue by hamedsangin** [ladybug-tools/butterfly#312]
hi mostapha
i do step by step this https://github.com/ladybug-tools/butterfly/wiki/Windows-10-Installation-Notes
but it still doen't work 
i check my virtualization and it was okey
![photo_ - - _ - -](https://user-images.githubusercontent.com/34301946/33760734-ee8f5172-dc1b-11e7-913e-3da9368d88a8.jpg)

**Comment by mostaphaRoudsari** [comment]
@hamedsangin,
If you read the outputs you can see the error messages. In window number remove the version 1612 which is a comment. The command should be `docker load -i of_v1612plus_centos66.tar`

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
