### ISSUE TITLE
Reconstruction of decomposed calculations

### ISSUE THREAD

**Issue by AlphaArsano** [ladybug-tools/butterfly#314]
I was wondering if there is a component already implemented in butterfly to reconstruct (same as reconstructpar) to combine results from multiple processors. This is especially useful for final visualizations such as in Paraview.

**Comment by TheodoreGalanos** [comment]
@AlphaArsano This is already integrated to Butterfly. It will reconstruct automatically your results upon finishing meshing and/or simulation runs.
