### ISSUE TITLE
Update Butterfly gives WindowsError

### ISSUE THREAD

**Issue by gamemakerh** [ladybug-tools/butterfly#316]
I had to reinstall rhino on my machine but now I'm getting error

OF - 1706
BF - 0.0.4

I've reinstalled Rhino
then installed grasshopper
and then installed BF.  Updated to newest version using update component.

Getting this error

![image](https://user-images.githubusercontent.com/4093017/33941553-b9578f7a-e01b-11e7-990b-baccf86dccce.png)

Maybe anyone can help me ? out of ideas.

**Comment by gamemakerh** [comment]
thanks. I solved this problem. Maybe it was because Windows 10 Enterprise.

**Comment by mostaphaRoudsari** [comment]
Great! No. It's a reoccurring issue and we have to find a better solution to avoid it.
