### ISSUE TITLE
another problems with update component

### ISSUE THREAD

**Issue by gamemakerh** [ladybug-tools/butterfly#317]
Hi. I'm literally thinking that my PC is broken. I have one after another issues regarding BF.

I.ve tried to download butterfly-master.zip and butterfly-plus-master.zip and using  BF update component update from local hard drive but all blocks used to appear RED.  every one have different  error messages.

This message I get very after I reinstalled BF using installer.gh (after install I get error regarding old version of OF)

to deal this problem I have to install newest version using update component, but I can't do that...

![image](https://user-images.githubusercontent.com/4093017/34049541-750ced78-e1c0-11e7-8134-89eb3fdf63d4.png)

**Comment by gamemakerh** [comment]
BTW this is what I get when  unzipping file manually  and copy pasting into scripts folder

![image](https://user-images.githubusercontent.com/4093017/34050403-7039a860-e1c3-11e7-97e8-0dafa5a4059a.png)

**Comment by mostaphaRoudsari** [comment]
You need to also remove the old user-objects and copy the new ones. Sorry for all the random issues. I will create an installer soon.

**Comment by dbriels** [comment]
I think I have the same issue. I downloaded the butterfly master zip. But which folder do I need to copy into the scripts folder and do I have to replace or delete anything? And where do i get the new user-objects? Thanks a lot!

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
