### ISSUE TITLE
In ceateCaseFromTunnel, error xyz_to_point failed to import

### ISSUE THREAD

**Issue by Chebrosky** [ladybug-tools/butterfly#318]
I believe that the definition in the .geometry is actually called xyzToPoint, editing the component's python call fixed the issue, just thought i'd report it

**Comment by mostaphaRoudsari** [comment]
Hi @Chebrosky, If you update the components as well as the source code it's actually called xyz_to_points:
https://github.com/ladybug-tools/butterfly-plus/blob/d887d677f989d009390633a6fed635b05ec287e6/butterfly_grasshopper/geometry.py#L210

**Comment by Chebrosky** [comment]
what is the process for updating? Sorry, I'm just getting started.
Thank you!

**Comment by TheodoreGalanos** [comment]
@Chebrosky You can attach a boolean toggle to the BF/BF component and set it to true. I would make sure I'm in admin use of Rhino while doing it. After that, restart Rhino, GH, and maybe OF, and you should have an updated installation working.

**Comment by Chebrosky** [comment]
Oh yes I tried that but it says windows error (I was running as an admin).
In the end, I circumvented that by using the downloaded zips and manually
distributing the updated files. Thanks for the help!
