### ISSUE TITLE
Link Butterfly to other OpenFOAM installation

### ISSUE THREAD

**Issue by rueckertch58521** [ladybug-tools/butterfly#319]
Dear Butterfly community,

i have a question. Is there a way to link butterfly to another OpenFOAM version, by manipulating the code?

In detail, i installed OpenFOAM for Windows 10 without a virtuel box, but using the developer tool "bash on ubuntu on Windows" (Installation Link "https://www.youtube.com/watch?v=xj0dB_PsElg"). So is there a way to manipulate the Butterfly code to link to this OpenFOAM version?

It would be nice if you could tell me in generall if this is possible. I also installed OpenFOAM using a virtual box, but in my opinion the process to run this version was really hard.

Best greedings

Christian

**Comment by gamemakerh** [comment]
I'm interested in this one too.

**Comment by mostaphaRoudsari** [comment]
See this: https://github.com/ladybug-tools/butterfly/issues/271

**Comment by etse1** [comment]
Hello, everyone.
I'm also interested. I had a lot of troubles installing OpenFOAM with VirtualBox on bootcamp (Windows 10 Fall Creators Update). I read and follow all the steps with no success. So I have successfully installed OpenFOAM inside Windows using bash, but now I don't get how to link Butterfly with this workaround. Any advice will be appreciated.

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
