### ISSUE TITLE
createcasefromtunnel component error

### ISSUE THREAD

**Issue by hamedsangin** [ladybug-tools/butterfly#320]
hi dear mostapha 
i run 01_0_outdoor_airflow example file and i got this problem :
![photo_ - - _ - -](https://user-images.githubusercontent.com/34301946/34279279-3ec712de-e6c5-11e7-8a83-664c88c99e5e.jpg)
p.s : my unite is set meters before open the file

**Comment by mostaphaRoudsari** [comment]
see this: https://github.com/ladybug-tools/butterfly/issues/318
