### ISSUE TITLE
Issue trying to install Openfoam: "The virtual machine 'default' has terminated unexpectedly during startup with exit code - 1073741819 (0xc0000005)"

### ISSUE THREAD

**Issue by Dorotheu** [ladybug-tools/butterfly#322]
Hello!

I'm having trouble trying to install openfoam on my PC (windows 10). 
Followed the tutorial in the youtube video: https://www.youtube.com/watch?v=e90FyyfVbe0&t=570s
I have downloaded the file OpenCFD-OpenFOAM4WindowsInstaller_v1612+ from the official website. 
During installation, it says "Error creating machine: error in driver during machine creation: unable to start the VM (...) The virtual machine 'default' has terminated unexpectedly during startup with exit code - 1073741819 (0xc0000005)"

I'm also sending the pics with errors during installation, during env_create and openfoam_start.

Does anyone know how to proceed with this?
Thank you very much in advance!

![erro instalacao](https://user-images.githubusercontent.com/35492317/34990455-4e3fe410-faad-11e7-90a5-565fcca8b387.JPG)
![erro start](https://user-images.githubusercontent.com/35492317/34990456-4e5f069c-faad-11e7-9ba7-b06ee1d7b337.JPG)
![erro env create](https://user-images.githubusercontent.com/35492317/34990457-4e7cf9c2-faad-11e7-847d-c6ebb72adfd2.JPG)

**Comment by etse1** [comment]
I had the same problem and solve it by updating VBox as suggested here:
http://discourse.ladybug.tools/t/openfoam1612-installation-challenges/1981/6?u=estebanagueero 
Try uninstalling OpenFOAM and then install first the last version of VirtualBox, next install OpenFOAM as usual.

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
