### ISSUE TITLE
OpenFOAM installation issue 0x80004005

### ISSUE THREAD

**Issue by qxiaowei** [ladybug-tools/butterfly#324]
Hello!
l am an architecture student and have been  frustrated by it for month.
In the first l got trouble with the step “get the latest Boot2Docker Iso release version”
then I download the file myself and put it in the specific place then cut the internet during the process.
That seems to be good but still got problem in the following step.
![snipaste_20180128_183207](https://user-images.githubusercontent.com/35943918/35545116-71a06f3c-05a8-11e8-983e-40e7fe3e4e1d.png)

Thank you all very much！

**Comment by ymg2007** [comment]
This error has prompted me to appear before. I suggest you try the following solution:
        1, reinstall OpenFOAM. 
        2, install the latest version of VirtualBox. 
        3, Baidu search for this error, try to find the results show that the solution.

Good luck to you.

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
