### ISSUE TITLE
Missing 'default' in the VMBox while installing the 1612ver

### ISSUE THREAD

**Issue by leeyuan123** [ladybug-tools/butterfly#325]
Hey guys, 
I've been trying to install OP for a couple of days, unfortunately, it doesn't went well. So I reinstall windows and tried it again. My main issue would be Missing 'default' in the VMBox  and I can't open my Docker Quickstart Terminal cause the system can't not find bash.exe. 
![missing default](https://user-images.githubusercontent.com/29521335/35781092-5e2e4880-0a20-11e8-8eaa-977d2d884e42.PNG)
![docker path value](https://user-images.githubusercontent.com/29521335/35781151-0f9fa3de-0a21-11e8-8816-baec7cb3ccbc.PNG)

Additional info:
I'm running on win 10 home version 1706
User name: Santabueno as an admin

Any kind of help would be appreciated, thank you very much.

**Comment by mostaphaRoudsari** [comment]
Hi @leeyuan123, Try this: https://github.com/ladybug-tools/butterfly/wiki/Windows-10-Installation-Notes

Hopefully for the next release we will get rid of the whole crazy process of installing VM and just use Docker itself.

**Comment by leeyuan123** [comment]
Thank you very much @mostaphaRoudsari , you have always been very kind and helpful. Can I ask if it is possible to interact BF and opencfd directly to avoid vm and linux?

**Comment by mostaphaRoudsari** [comment]
Hi @leeyuan123, You can't avoid linux but you can avoid VM. See this: https://github.com/ladybug-tools/butterfly/issues/271

**Comment by kelsworth** [comment]
Hi @mostaphaRoudsari , I am also hitting the same error (missing bash.exe) but I followed the instructions on for Windows 10 download. I downloaded OpenFoam 1602+ and installed VB 5.5.22 after uninstalling the version that came with OpenFoam. When running the Docker Start Terminal (as admin) I get the messages:
![docker terminal_01](https://user-images.githubusercontent.com/31259364/51326725-c7449a80-1a3d-11e9-9ce9-812f6db4057a.PNG)
![docker terminal](https://user-images.githubusercontent.com/31259364/51326727-c9a6f480-1a3d-11e9-9c4e-ab6c66d1f860.PNG)

Not sure if its related but there is also this difference between your installation video and my install-
![inkeddocker istall_li](https://user-images.githubusercontent.com/31259364/51326898-168acb00-1a3e-11e9-9b2c-49e55d6d33dd.jpg)

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
