### ISSUE TITLE
Negative value troubleshooting questions

### ISSUE THREAD

**Issue by ichephe** [ladybug-tools/butterfly#326]
What could be the possible reason to extra large negative value?

I am using default gh definition for outdoor 2d. I did a modification on z plane for the mesh instead of the x.
I have run the solver, and the result shows me 7000 list of values. There are 24 values that are negatives, -10000000.......

They are in order, which means located near to each other or possibly in the same row or collumn.

I am assuming the mesh is out of the boundary area.

The vector directions shows fine result in the preview, the problem is the color coding and pressure value shows

‹0 to -100000... in increments
I think of a work arround for this data by just replace these values to lowest value, but I hope to be able to find a more accurate values instead of going for a workaround.

**Comment by mostaphaRoudsari** [comment]
Hi @ichephe, a number of probes are outside the meshed volume. See this: https://github.com/ladybug-tools/butterfly/issues/255
