### ISSUE TITLE
OpenFOAM installation error

### ISSUE THREAD

**Issue by TiagoXR** [ladybug-tools/butterfly#328]
Hi, I'm not been able to install OpenFOAM in windows 10. Can you help me? I tried to follow the installation notes for Windows 10, but I get this error in the Docker:

<img width="679" alt="error3" src="https://user-images.githubusercontent.com/36269063/35977324-f6d110da-0cc9-11e8-9ebc-bd32b2dd4de2.PNG">

Any idea what I can do here?

Thanks!! #

**Comment by mostaphaRoudsari** [comment]
Most likely you need to update your VM and install the latest version.

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
