### ISSUE TITLE
Installation OpenFOAM_VM_ VirtualBox

### ISSUE THREAD

**Issue by houdalichiheb** [ladybug-tools/butterfly#330]
Hi, 
I  installed OpenFOAM (pic.1) but when I try to modify the configuration of VM, an error message is displayed (pic.2). It is the same problem occurred in the installation video but for this case, it does not work.
Thank you
![e1](https://user-images.githubusercontent.com/36425195/36259549-cfec4e2c-125e-11e8-9879-34d76f0a88f2.JPG)
![e1](https://user-images.githubusercontent.com/36425195/36259583-ea0820ba-125e-11e8-8193-dbb81fed4545.png)

**Comment by dbriels** [comment]
I had the same issue. I managed it by uninstalling everything, installing the latest VM virtual box myself and then repeating the installation process of open foam but I disabled the integrated function for installing VM virtual box. 
Good luck!

**Comment by houdalichiheb** [comment]
I thank you for your answer.
I uninstalled everything several times but it doesn't work.
So I changed the machine and it's ok !

**Comment by CharlesCollin91** [comment]
Which version of VM virtual box are you using ? I tryied the lastest without success (5.2.12).. any chances that the version is too recent ?

**Comment by dbriels** [comment]
Hi, 

I have the following constellation running and it works: 

Virtual Box 5.2.8
openFoam 1612

(Rhino 5.8
Grasshopper 0.9
Butterfly 0.0.04)

Cheers
David

**Comment by CharlesCollin91** [comment]
thanks david ! Looks like Virtual Box 5.2.8 was the solution !

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
