### ISSUE TITLE
Windows 10 (1709) - OpenFOAM v1712 - is it possible to put in one post all the installation issues?

### ISSUE THREAD

**Issue by albesaca** [ladybug-tools/butterfly#331]
Hello to everybody, i absolutely don't want to look inappropriate or in some way too selfish, but i'm an architecture student and i clearly have some limits when i find myself involved in this kind of subjects.
By the way, reading issues reported by other users, i'm happy to understand i'm not alone.
https://github.com/ladybug-tools/butterfly/issues/324
https://github.com/ladybug-tools/butterfly/issues/322
http://discourse.ladybug.tools/t/openfoam1612-installation-challenges/1981/13
https://github.com/ladybug-tools/butterfly/issues/307

All these posts have no exactly solution unfortunately.

In my case the openfoam installer does its job in the correct way. Problems start when i have to create the enviroment. 

First try (load docker image)

The first time i tried (i mean the first time after i reset my computer), i loaded the image as the "windows 10 installation's notes" sayis, and the result has been the expected one.
![1](https://user-images.githubusercontent.com/36915860/36781291-bd7cef8c-1c75-11e8-953c-ad470f50e9e2.jpg)
But then..
![2](https://user-images.githubusercontent.com/36915860/36781309-d1818038-1c75-11e8-9f01-5b6af476f187.jpg)
And..
![3](https://user-images.githubusercontent.com/36915860/36781325-db9cdd06-1c75-11e8-8ba8-1f7a088e00e2.jpg)

Second try (do not load docker image)

At the second time, i tried to not load the image.
Creating enviroment:
![1b](https://user-images.githubusercontent.com/36915860/36781429-24e81994-1c76-11e8-8d79-ab58a102e05d.jpg)
Starting:
![2b](https://user-images.githubusercontent.com/36915860/36781445-2d0943c8-1c76-11e8-9ada-60a4dca8ef51.jpg)

Third try (skip the enviroment part)

As my introduction explain, most of the things i do are totally out of my knownledge. Explained this, for the third time i tried to assume that the enviroment creation has gone fine, and i tried to start from the OpenFOAM_start batch.
![1c](https://user-images.githubusercontent.com/36915860/36781606-a058e0b8-1c76-11e8-9bb0-94b5f2185730.jpg)

As final informations, i specify that between every test i've clearly done a reboot, and also that, as i read in a thread i linked up, my virtualbox version is the last one, not the one who comes from the openfoam installer.

Thanks in advance for the attention, my thesis will appreciate very much.

**Comment by ymg2007** [comment]
Followed the guide https://docs.docker.com/engine/reference/commandline/rm/#options ,you can delete the container of v1712 in docker. Then restart the openfoam create and start.

**Comment by albesaca** [comment]
thanks for the suggestion @ymg2007 

i deleted the container and this seemed to affect in a good way the enviroment creation.

i made three tries again:

1) delete the container, load the image
enviroment creation:
![1e](https://user-images.githubusercontent.com/36915860/36784526-fe56f5f2-1c7f-11e8-8da7-a92d14342acd.jpg)
starting:
![2d](https://user-images.githubusercontent.com/36915860/36784517-f3bfd208-1c7f-11e8-9030-cbe19c6b033a.jpg)

2)delete the container, do not load the image
enviroment creation:
![1d](https://user-images.githubusercontent.com/36915860/36784541-108787b4-1c80-11e8-8480-4706e0eabcad.jpg)
starting: same as before

3) delete container, load image, reboot
starting: 
![1f](https://user-images.githubusercontent.com/36915860/36784568-30ba6588-1c80-11e8-845a-86fe83bd3eb5.jpg)

something changes, but i still can't start openfoam in the right way.

**Comment by albesaca** [comment]
Hello everybody. I'm sorry for the delay.

The suggestion of updating virtualbox worked for the openfoam part. I don't know exactly why it didn't work at the first tries, but it's for sure because of some errors of mine,

Anyway, now i understand much better the problem. Until now i was focused on making openfoam works and i didn't pay attention on the version of it. 
https://github.com/ladybug-tools/butterfly/commit/917b50c83043456d6304dd28561991557820dba9
This opened my eyes :) I have not tried to let v1712 works, but i guess it will not be a big deal for someone who knows how to do to adapt the linked file.

It's all my fault, i apologie with you all.
