### ISSUE TITLE
Windows 10 OpenFoam 1712 Rhino 6 BlockMesh Error

### ISSUE THREAD

**Issue by aminigam92** [ladybug-tools/butterfly#332]
Hello Everyone,
I'm a fairly experienced GH user but new to CFD and Honeybee, I've been trying to install OpenFoam & Butterfly for a couple days and haven't managed to crack it yet. Following Mostapha's Outdoor Airflow Modelling tutorial, I manage to get up until wind tunnel but as soon as I toggle Blockmesh, I get the following error 
 
![image](https://user-images.githubusercontent.com/37090281/37006988-6aee64e8-20db-11e8-88f2-5880e19dc0b4.png)

![image](https://user-images.githubusercontent.com/37090281/37007002-7d564b78-20db-11e8-90da-71805e0192bd.png)

{
0. SET DOCKER_TLS_VERIFY=1&SET DOCKER_HOST=tcp://192.168.99.100:2376&SET DOCKER_CERT_PATH=C:\Users\Admin\.docker\machine\machines\default&SET DOCKER_MACHINE_NAME=default&SET COMPOSE_CONVERT_WINDOWS_PATHS=true&docker ps
1. SET DOCKER_TLS_VERIFY=1&SET DOCKER_HOST=tcp://192.168.99.100:2376&SET DOCKER_CERT_PATH=C:\Users\Admin\.docker\machine\machines\default&SET DOCKER_MACHINE_NAME=default&SET COMPOSE_CONVERT_WINDOWS_PATHS=true&docker ps
2. SET DOCKER_TLS_VERIFY=1&SET DOCKER_HOST=tcp://192.168.99.100:2376&SET DOCKER_CERT_PATH=C:\Users\Admin\.docker\machine\machines\default&SET DOCKER_MACHINE_NAME=default&SET COMPOSE_CONVERT_WINDOWS_PATHS=true&docker ps
3. SET DOCKER_TLS_VERIFY=1&SET DOCKER_HOST=tcp://192.168.99.100:2376&SET DOCKER_CERT_PATH=C:\Users\Admin\.docker\machine\machines\default&SET DOCKER_MACHINE_NAME=default&SET COMPOSE_CONVERT_WINDOWS_PATHS=true&docker ps
4. SET DOCKER_TLS_VERIFY=1&SET DOCKER_HOST=tcp://192.168.99.100:2376&SET DOCKER_CERT_PATH=C:\Users\Admin\.docker\machine\machines\default&SET DOCKER_MACHINE_NAME=default&SET COMPOSE_CONVERT_WINDOWS_PATHS=true&docker ps
5. SET DOCKER_TLS_VERIFY=1&SET DOCKER_HOST=tcp://192.168.99.100:2376&SET DOCKER_CERT_PATH=C:\Users\Admin\.docker\machine\machines\default&SET DOCKER_MACHINE_NAME=default&SET COMPOSE_CONVERT_WINDOWS_PATHS=true&docker ps
6. SET DOCKER_TLS_VERIFY=1&SET DOCKER_HOST=tcp://192.168.99.100:2376&SET DOCKER_CERT_PATH=C:\Users\Admin\.docker\machine\machines\default&SET DOCKER_MACHINE_NAME=default&SET COMPOSE_CONVERT_WINDOWS_PATHS=true&docker ps
7. SET DOCKER_TLS_VERIFY=1&SET DOCKER_HOST=tcp://192.168.99.100:2376&SET DOCKER_CERT_PATH=C:\Users\Admin\.docker\machine\machines\default&SET DOCKER_MACHINE_NAME=default&SET COMPOSE_CONVERT_WINDOWS_PATHS=true&docker ps
8. SET DOCKER_TLS_VERIFY=1&SET DOCKER_HOST=tcp://192.168.99.100:2376&SET DOCKER_CERT_PATH=C:\Users\Admin\.docker\machine\machines\default&SET DOCKER_MACHINE_NAME=default&SET COMPOSE_CONVERT_WINDOWS_PATHS=true&docker ps
9. SET DOCKER_TLS_VERIFY=1&SET DOCKER_HOST=tcp://192.168.99.100:2376&SET DOCKER_CERT_PATH=C:\Users\Admin\.docker\machine\machines\default&SET DOCKER_MACHINE_NAME=default&SET COMPOSE_CONVERT_WINDOWS_PATHS=true&docker ps
10. SET DOCKER_TLS_VERIFY=1&SET DOCKER_HOST=tcp://192.168.99.100:2376&SET DOCKER_CERT_PATH=C:\Users\Admin\.docker\machine\machines\default&SET DOCKER_MACHINE_NAME=default&SET COMPOSE_CONVERT_WINDOWS_PATHS=true&docker ps
11. SET DOCKER_TLS_VERIFY=1&SET DOCKER_HOST=tcp://192.168.99.100:2376&SET DOCKER_CERT_PATH=C:\Users\Admin\.docker\machine\machines\default&SET DOCKER_MACHINE_NAME=default&SET COMPOSE_CONVERT_WINDOWS_PATHS=true&docker ps
12. SET DOCKER_TLS_VERIFY=1&SET DOCKER_HOST=tcp://192.168.99.100:2376&SET DOCKER_CERT_PATH=C:\Users\Admin\.docker\machine\machines\default&SET DOCKER_MACHINE_NAME=default&SET COMPOSE_CONVERT_WINDOWS_PATHS=true&docker ps
13. SET DOCKER_TLS_VERIFY=1&SET DOCKER_HOST=tcp://192.168.99.100:2376&SET DOCKER_CERT_PATH=C:\Users\Admin\.docker\machine\machines\default&SET DOCKER_MACHINE_NAME=default&SET COMPOSE_CONVERT_WINDOWS_PATHS=true&docker ps
14. SET DOCKER_TLS_VERIFY=1&SET DOCKER_HOST=tcp://192.168.99.100:2376&SET DOCKER_CERT_PATH=C:\Users\Admin\.docker\machine\machines\default&SET DOCKER_MACHINE_NAME=default&SET COMPOSE_CONVERT_WINDOWS_PATHS=true&docker ps
15. SET DOCKER_TLS_VERIFY=1&SET DOCKER_HOST=tcp://192.168.99.100:2376&SET DOCKER_CERT_PATH=C:\Users\Admin\.docker\machine\machines\default&SET DOCKER_MACHINE_NAME=default&SET COMPOSE_CONVERT_WINDOWS_PATHS=true&docker ps
16. docker-machine env
17. Runtime error (AssertionException): Failed to find container id.Do you have the OpenFOAM container running?
You can initiate OpenFOAM container by running start_OF.bat:
C:\Program Files (x86)\ESI\OpenFOAM\171\\Windows\Scripts\start_OF.bat

Traceback:
  line 263, in _RunManager__command, "C:\Users\Admin\AppData\Roaming\McNeel\Rhinoceros\6.0\scripts\butterfly\runmanager.py"
  line 215, in command, "C:\Users\Admin\AppData\Roaming\McNeel\Rhinoceros\6.0\scripts\butterfly\runmanager.py"
  line 316, in run, "C:\Users\Admin\AppData\Roaming\McNeel\Rhinoceros\6.0\scripts\butterfly\runmanager.py"
  line 716, in command, "C:\Users\Admin\AppData\Roaming\McNeel\Rhinoceros\6.0\scripts\butterfly\case.py"
  line 748, in blockMesh, "C:\Users\Admin\AppData\Roaming\McNeel\Rhinoceros\6.0\scripts\butterfly\case.py"
  line 47, in script
}

![image](https://user-images.githubusercontent.com/37090281/37007156-42cc088e-20dc-11e8-89d6-de04e0d6d04e.png)

![image](https://user-images.githubusercontent.com/37090281/37007185-5f3af94e-20dc-11e8-95cb-f134cb46383c.png)

I've already tried several times purging and reloading the case but I have very little idea of what could be causing this? Could it be version issues? Because a lot of people seem to be running it with OpenFoam 1612+? I've also changed the version.py file to reflect the version I'm using.

Any help will be greatly appreciated.
Thanks

**Comment by aminigam92** [comment]
After debugging more, I've tried following the last step and substeps on the FAQ [here](https://www.openfoam.com/download/install-binary-windows.php),  I am able to reach the scripts folder but when I try to load [load -i of_v1712_centos73.tar] or [load -i of_v1712_centos73_win.tar] as the file is called on my computer , it tells me bash : load : command not found. I'm really stuck trying to install this.

![image](https://user-images.githubusercontent.com/37090281/37029181-c4407ce2-2136-11e8-8370-d878a492eb0d.png)


Again
Any help with much appreciated

**Comment by thp44** [comment]
same problem.. did you find a solution? :-)

**Comment by devngc** [comment]
Do you run Openfoam as Administrator? Are you using Openfoam version 1612? Which version of Butterfly are you using? Is it the public release version downloaded from food4Rhino or the latest version from Github?

**Comment by thp44** [comment]
- RH6
- GH 1.xx
- Butterfly 0.0.04
- OpenFOAM tried the newest version and 1612
- Win10
Both RH and OpenFOAM was run as administrator.

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
