### ISSUE TITLE
Meshing problems Windows 10 VM 5.2.8 openFoam 1706

### ISSUE THREAD

**Issue by dbriels** [ladybug-tools/butterfly#334]
Hello everyone! 
First of all thanks Mostapha for all your work and support. 
I´m trying to get butterfly and openFoam working for quite a long time now. I´m working on Windows 10 with VM 5.2.8 (the older one didn´t work). I tried openFoam 1612, 1706 and 1712 with and without the updated butterfly files. But even if everything seems to be running, at least there is a problem with the meshing functions: 

_> 0. Updating cell size in blockMeshDict.
> 1. Updating grading in blockMeshDict.
> 2. Saved changes to blockMeshDict to:
> C:\Users\Administrator\butterfly\outdoor_airflow\system\blockMeshDict
> 3. container id: bb6682953dc8
> 4. Butterfly is running blockMesh. PID: None
> 5. Failed to read C:\Users\Administrator\butterfly\outdoor_airflow\log\blockMesh.log:
> 	[Errno 2] Die Datei "C:\Users\Administrator\butterfly\outdoor_airflow\log\blockMesh.log" konnte nicht gefunden werden.: C:\Users\Administrator\butterfly\outdoor_airflow\log\blockMesh.log
> 6. Failed to read C:\Users\Administrator\butterfly\outdoor_airflow\log\blockMesh.err:
> 	[Errno 2] Die Datei "C:\Users\Administrator\butterfly\outdoor_airflow\log\blockMesh.err" konnte nicht gefunden werden.: C:\Users\Administrator\butterfly\outdoor_airflow\log\blockMesh.err_

Is there maybe a problem with my user account? I allways run everything as admin as mentioned. I have two users: "Administrator" and "DBR", both have admin rights. The docker and butterfly folder are saved in "Administrator". 

Can anyone help me? 

Thanks a lot!

![blockmesh2](https://user-images.githubusercontent.com/37077597/37143084-5d06fefe-22ba-11e8-95b9-7e0c00f9500f.PNG)

**Comment by dbriels** [comment]
I finally could manage it on my own: i uninstalled everything and deleted all files and folders. Then I followed once more all the installation guidelines (except the new VW version). And now it works. I´m using the following versions: 
Windows 10 enterprise
openFOAM 1612+
Virtual Box 5.2.8
Butterfly 0.0.4

I guess my main problem was the user name. In the past I changed the user name manually. Now before installing everything new, I changed the user name back to the default name which the laptop had, when I got it from university.

**Comment by liaochenxi** [comment]
Hello! I got the same problem as your post. I saw that you were using V1706+ before. Did you get this problem after you updated your butterfly in python? like this
[https://github.com/ladybug-tools/butterfly/commit/917b50c83043456d6304dd28561991557820dba9#diff-030bae7d56449880656d865dde8f4091](url)

**Comment by dbriels** [comment]
Hey! I´m sorry but I can´t open the link. But no, I don´t think I tried this method.
