### ISSUE TITLE
wind_direction

### ISSUE THREAD

**Issue by houdalichiheb** [ladybug-tools/butterfly#335]
Hello,
I am an architect and my programming skills are very limited.
I start working with the outdoor example of butterfly but I tried to calculate them by changing the wind direction. But unfortunately it doesn't work. 

" failed to copy snappyHexMesh floder"

Do you have the solution?
Thx
![1](https://user-images.githubusercontent.com/36425195/37412399-1c561a12-27a5-11e8-95a7-64cd3c8d5743.PNG)
![2](https://user-images.githubusercontent.com/36425195/37412400-1cc237d8-27a5-11e8-860b-00e4b76b544d.PNG)

**Comment by mostaphaRoudsari** [comment]
@houdalichiheb, This is a Grasshopper question. You should repost this question to the forum.
