### ISSUE TITLE
Installation Issue: "Runtime error (AssertionException): Failed to find container id"

### ISSUE THREAD

**Issue by pablogomezrodriguez** [ladybug-tools/butterfly#337]
Hi everyone!
First of all, thanks the creators (and specially Mostapha) for makings these tools possible.
I've read all the posts with installations issues but I guess I might be missing something.
My OpenFoam version is 1712+ and I haven't been able to run it properly with butterfly. 
When I try to run BlockMesh it shows this error (please see the image for further information):

Runtime error (AssertionException): Failed to find container id.Do you have the OpenFOAM container running?
You can initiate OpenFOAM container by running start_OF.bat:
C:\Program Files (x86)\ESI\OpenFOAM\1712\\Windows\Scripts\start_OF.bat
Traceback:
  line 263, in _RunManager__command, "C:\Users\USER\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 215, in command, "C:\Users\USER\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 316, in run, "C:\Users\USER\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 716, in command, "C:\Users\USER\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\case.py"
  line 748, in blockMesh, "C:\Users\USER\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\case.py"
  line 47, in script

![blockmesh issue](https://user-images.githubusercontent.com/20504631/37869017-80e43d0c-2fb0-11e8-8a28-936362f71521.PNG)

I've installed and re-installed openFoam several times, both OpenFoam and virtualBox seem to be running ok. 
![openfoamrunning](https://user-images.githubusercontent.com/20504631/37869020-815a7f3a-2fb0-11e8-9689-ef77cbde44c5.PNG)
![virtual box](https://user-images.githubusercontent.com/20504631/37869021-81801696-2fb0-11e8-80ad-0a074b686c59.PNG)

I've tried to change the version issue( like here  #250  https://github.com/ladybug-tools/butterfly/issues/250) and see if there's an access problem but that seems to work fine too...any ideas??
![check access true](https://user-images.githubusercontent.com/20504631/37869018-8107a4e0-2fb0-11e8-863e-82ad4c5f6439.PNG)
![inkedversion_li](https://user-images.githubusercontent.com/20504631/37869019-81305dae-2fb0-11e8-9417-c2c2858cb57b.jpg)

Thank you all very much and please keep with the good work!
Pablo

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
