### ISSUE TITLE
Open FOAM installation issues - Cannot obtain IP from Powershell, Host is not running

### ISSUE THREAD

**Issue by jirehdagdag06** [ladybug-tools/butterfly#339]
I have windows10 and I have installed it multiple times but I can't get through the "powershell stage"
![error](https://user-images.githubusercontent.com/38096112/38352043-80b02bba-38e4-11e8-9962-422c83cabcd4.jpg)

From your installation video, it should wait for an IP, but mine has appeared to be error.

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
