### ISSUE TITLE
Butterfly blockmesh problem!

### ISSUE THREAD

**Issue by Kilo-Tsai** [ladybug-tools/butterfly#340]
![image](https://user-images.githubusercontent.com/33201839/38849007-c0b8c71a-423c-11e8-9d31-ac68a5db33fc.png)
 I open rhino as administrator. Just tried the example file, and the blockmesh doesn't work.  And I has tried re-stalling OpenFOAM several times. It still doesn't work.
![image](https://user-images.githubusercontent.com/33201839/38849151-56a18cf8-423d-11e8-8bfa-e047142756d1.png)
So I follow the final step of OpenFOAM FAQs suggestion to do this. And find the problem that open of_v1712_centos73.tar: The system cannot find the file specified.  

Anyone has idea how to fix it?
Please give me help. Thank you.

**Comment by albesaca** [comment]
The latest release of Butterfly is developed to work with openFoam v1612. You need to use this version to let Butterfly work properly.

**Comment by Kilo-Tsai** [comment]
Albesaca , thanks for your advise.
But I try it again. Both openFOAM v1612 and v1706 are failed installing, and I don't know how to fix it, either. 
![image](https://user-images.githubusercontent.com/33201839/39084256-f7e82738-45a4-11e8-8ded-eda03e6a6e56.png)

**Comment by albesaca** [comment]
Take my advices as the ones which come from a newbie please. Anyway, my suggestion is to start again by uninstalling everything (openFoam, docker, virtualbox). Then download the latest version of virtualbox from virtualbox site. After this, install again openFoam and uncheck "install virtualbox" from the installation panel. Follow closely the instructions for windows 10.

**Comment by Kilo-Tsai** [comment]
![image](https://user-images.githubusercontent.com/33201839/39094701-65c6d9b8-4666-11e8-8138-a2c71b501363.png)
Because the latest Virtualbox doesn't release now, I use the 5.2.8 version to install. Is it OK?
After installing Virtualbox , I keep stalling OpenFOAM v1612. Finally I success to finish it. 
![image](https://user-images.githubusercontent.com/33201839/39094824-9fedcb68-4668-11e8-802f-9fc50ec9cf13.png)
![image](https://user-images.githubusercontent.com/33201839/39095050-74425c5a-466c-11e8-9837-b82955b5484f.png)
![image](https://user-images.githubusercontent.com/33201839/39095055-897fb748-466c-11e8-8990-b36604841e8f.png)
![image](https://user-images.githubusercontent.com/33201839/39095066-cb4a9486-466c-11e8-9f0d-a4698b4732b7.png)
![image](https://user-images.githubusercontent.com/33201839/39095088-582fb976-466d-11e8-8925-33787d63855f.png)

Albesaca, thank you again. I follow the step you give me. Glad that OpenFOAM v1612 installation is successful. However, the butterfly blockmesh is still wrong to work.

**Comment by CharlesCollin91** [comment]
Hi guys, 
I'm getting the same error ! Anyone find something ?
I'm also using OpenFOAM v1712 (is butterfly supporting it ?) (Can't manage to install v1612+)

thanks
C.C.

**Comment by devngc** [comment]
@CharlesCollin91,
You should try OpenFOAM 1706. This error will only go away if OpenFOAM is installed correctly and is running when you run the Blockmesh

**Comment by saket411** [comment]
After uninstalling everything I found it useful sometimes to delete the folders boot2docker, docker and virtualbox from program data, program files and C:/Users/username/ giving it a cleaner install.

**Comment by NavidAhmadi** [comment]
Hi. 
I have installed OpenFOAM 1806 and the latest version of butterfly in Rhino 6 and 5 but in both of them, I have the same problem with blockmesh component. (i installed OpenFOAM correctly with no error, and I am using win 10 )

**Comment by devngc** [comment]
This information is not enough to garner help. Please provide more information on error and if possible some screen shots

**Comment by NavidAhmadi** [comment]
![screenshot 13](https://user-images.githubusercontent.com/39538942/43685370-3e1d503c-98c7-11e8-90ad-fb48463b42b2.png)
![capture](https://user-images.githubusercontent.com/39538942/43685397-9b41405c-98c7-11e8-90f6-3fcdc986e7e6.PNG)
i have the same error mentioned by kilo-tasi above

**Comment by NavidAhmadi** [comment]
![screenshot 14](https://user-images.githubusercontent.com/39538942/43685505-89473792-98c9-11e8-9391-739093ff3c7e.png)

**Comment by NavidAhmadi** [comment]
- 
![screenshot 15](https://user-images.githubusercontent.com/39538942/43685524-ca7aa1f4-98c9-11e8-8069-0f0d6cc32d07.png)
i have the same problem in Rhino 5

**Comment by devngc** [comment]
Can you please share your openfoam start screenshot?

**Comment by NavidAhmadi** [comment]
![screenshot 14](https://user-images.githubusercontent.com/39538942/43685540-02eac366-98ca-11e8-8135-2034eb77f4a8.png)

**Comment by devngc** [comment]
Can you please power off the machine and then run openfoam start ao that it will start the machine itself?

**Comment by NavidAhmadi** [comment]
![screenshot 16](https://user-images.githubusercontent.com/39538942/43685564-8a04fd3a-98ca-11e8-86cc-cf386a62bf3b.png)

**Comment by NavidAhmadi** [comment]
![screenshot 17](https://user-images.githubusercontent.com/39538942/43685632-d90875b4-98cb-11e8-89a5-378a292db435.png)

I have even more errors in rhino 5 !!!

**Comment by devngc** [comment]
Can you please try OpenFOAM 1612 or 1706? and latest version of Butterfly from [here](https://discourse.ladybug.tools/t/installation-error-openfoam-windows-10/2366/19?u=devang)?

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
