### ISSUE TITLE
No visualize Mesh

### ISSUE THREAD

**Issue by Lainee03** [ladybug-tools/butterfly#342]
Hello, 

I recently started with Butterfly and i am coming accross an issue.
![no visualize mesh](https://user-images.githubusercontent.com/38813068/39398177-a1ba9574-4b0a-11e8-90c8-acb69e5b7684.JPG)
OpenFOAM works fine,  blockmesh seems to work but shows an error , and can not retrace to the blockmesh.log file
None of the files in C:\Users\EBD\butterfly\outdoor_airflow\log were created and C:\Users\EBD\butterfly\outdoor_airflow\constant\polyMesh is also empty. Consequently i can not visualize the Mesh.

Any advice on where can the issue be ? Thank you in advance for your time

**Comment by saket411** [comment]
Hi @Lainee03 ,
Can you pls share your gh definition. Thanks.

**Comment by Lainee03** [comment]
Hi @saket411 

I actually used the given definition and followed the tutorial.

**Comment by mostaphaRoudsari** [comment]
@Lainee03, try the new installer and blueCFD. Based on the error message your blockMesh command fails before running and that is why there is no log file.

We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
