### ISSUE TITLE
Stuck at Powershell "Running Pre-create checks..."

### ISSUE THREAD

**Issue by rainbowhat** [ladybug-tools/butterfly#343]
Hi all,

My installation is stuck as per the image for 5 hours. I need butterfly to work with openfoam so i only followed the tutorial that is on this wiki.

Please advice what went wrong as i tried reinstalling a few times and i still cant get it working , with & without hyper-v

https://i.imgur.com/1rWi9G9.png

Set-ExecutionPolicy : Windows PowerShell updated your execution policy successfully, but the setting is overridden by
a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective
execution policy of Bypass. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more
information please see "Get-Help Set-ExecutionPolicy".
At C:\Program Files (x86)\ESI\OpenFOAM\1612\Windows\Scripts\of_install_image.ps1:2 char:1
+ Set-ExecutionPolicy Unrestricted -Scope CurrentUser
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], SecurityException
    + FullyQualifiedErrorId : ExecutionPolicyOverride,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand
Num Args: 2
of_v1612plus_centos66.tar
C:\Program Files\Docker Toolbox\;C:\Program Files\Git\bin
Creating CA: C:\Users\806347\.docker\machine\certs\ca.pem
Creating client certificate: C:\Users\806347\.docker\machine\certs\cert.pem
Running pre-create checks...

It's stuck like this for the next 5 hours.

**Comment by devngc** [comment]
Hi @rainbowhat ,
Not able to open the image.  Are you the admin on your machine? Were you able to change the Execution policy?

**Comment by rainbowhat** [comment]
@devngc 
You mean you cant open https://i.imgur.com/1rWi9G9.png ?

Yes im administrator , i followe the tutorial too the tutorial had the same execution policy error but his was able to load and not get stuck like mine. 

I tried waiting 8hours its still stuck

**Comment by devngc** [comment]
Thanks for the image. I can see that now. To the best of my knowledge, this is the first time this issue is reported. Nevertheless, Can you please check if boot2docker.iso is there c:\Program Files\Docker Toolbox

**Comment by devngc** [comment]
Also, are you sure the path to the docker folder is added to the environment variables of your machine?

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
