### ISSUE TITLE
Open Foam start error : TLS connection 

### ISSUE THREAD

**Issue by SaraAghaC** [ladybug-tools/butterfly#344]
Does anyone know how can i get over this error:
 I installed step by step by the youtube video: How to install OpenFOAM for Windows.
Thanks in advance. 

![error](https://user-images.githubusercontent.com/20902155/39672580-4aa74280-5142-11e8-9315-0a0b48355516.JPG)

**Comment by devngc** [comment]
This is very common. Please power off the virtual box. And then start the OpenFOAM start again. Try this a few times. It should work.

**Comment by SaraAghaC** [comment]
I tried in this way several times. Every time I saw this error.

![error1](https://user-images.githubusercontent.com/20902155/39688088-55278db0-51e6-11e8-9918-c566387d1785.JPG)

**Comment by devngc** [comment]
Is virtual machine running without errors?

**Comment by SaraAghaC** [comment]
yes. It doesn't show any error.
After powering off the machine and with or without closing the Oracle VM VirtualBox Manager, the machine run by itself after running the OpenFoam Start. Is it right?

**Comment by devngc** [comment]
1. run Oracle VM as Administrator
2. Try to run turn the machine on
3. If it works successfully. Power it off
4. Now fire up OpenFOAM start as admin.

As another note, this same error happened to me just now. With the above mentioned steps I fixed it.

**Comment by SaraAghaC** [comment]
I did this step exactly as you mentioned but the same error happened.

**Comment by devngc** [comment]
Is docker added to the environment variables of your machine?

**Comment by SaraAghaC** [comment]
yeah of course

**Comment by devngc** [comment]
I suggest you post on the Forum please

**Comment by gamemakerh** [comment]
I had the same thing. Can't remember what I did. But long story short. try to uninstall virtual machine and install with different settings (some checkbox have to be chosen if I remember correctly. 
This part of docker/VM/OpenFOAM was driving me nuts. 

BTW Is this project still alive? I do not see any updates regarding this.

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
