### ISSUE TITLE
Docker Quickstart Terminal

### ISSUE THREAD

**Issue by SustainaBIMity** [ladybug-tools/butterfly#345]
Hi there,

I am trying to install OpenFORM, but there was an issue to go through the instruction. When I typed
**cd 'Program Files (x86)'** on the docker quickstart terminal, it didn't work - could you please advise me how to resolve this? 

Thanks,
So

![docker issue](https://user-images.githubusercontent.com/6792903/40172707-5eb3420a-59c7-11e8-9755-d96c57c92495.JPG)

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
