### ISSUE TITLE
openfoam installation issues----load image

### ISSUE THREAD

**Issue by yoyomooo** [ladybug-tools/butterfly#346]
hi,
I installed step by step by the user manual.But whenever I go to this step,it tells me like that——load image:of_1712_centos73_win:latest
![6t8ti80 nvoa2d t5ie9 8g](https://user-images.githubusercontent.com/39586415/40478545-ef5232da-5f7b-11e8-95bd-4827f35efd92.png)
how can i do next?

**Comment by devngc** [comment]
I am not sure if Butterly supports an OpenFOAM version higher than v1706

**Comment by yoyomooo** [comment]
Actually，I tried both OpenFOAM version v1612 and v1706. But,I got the same error.

**Comment by yoyomooo** [comment]
Actually，I tried both OpenFOAM version v1612 and v1706. But,I got the same error.

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
