### ISSUE TITLE
Failed to find container id

### ISSUE THREAD

**Issue by cyshimz** [ladybug-tools/butterfly#348]
Hi all,

I'm new to butterfly and GH, and spent some time today trying to get OpenFOAM to work with butterfly. I've been stuck on this for the whole afternoon while trying to run Blockmesh on the example file:

1. Solution exception:Failed to find container id.Do you have the OpenFOAM container running?
You can initiate OpenFOAM container by running start_OF.bat:
C:\Program Files (x86)\ESI\OpenFOAM\1612\\Windows\Scripts\start_OF.bat

I'm currently running OpenFOAM1712 and Rhino 6. I've spent some time here and figured out that I have to download butterfly-plus-master and butterfly-plus. Unfortunately I'm really confused what to do with these files in order to make the example file work properly, and would appreciate some advice on what to do from here.

Thank you so much!

**Comment by devngc** [comment]
Hi @cyshimz,

Please follow steps mentioned on [this](https://discourse.ladybug.tools/t/installation-error-openfoam-windows-10/2366/19?u=devang) post.

**Comment by cyshimz** [comment]
Hi @devngc,

Thanks for the head's up! Got to admit that since last week I've not been successful in installing 1712 and running it as per the tutorial Youtube videos. 

I've successfully installed 1612 on my Windows 10 PC, however, and it's working really well. Thanks again for replying!
