### ISSUE TITLE
Openfoam v1612+, v1706 or v1712 and VM virtualbox 5.x.xx ? how to manage it.

### ISSUE THREAD

**Issue by CharlesCollin91** [ladybug-tools/butterfly#349]
Hello guys, 
I don't know if its the appropriate place to post this, but here's how I finally manage this OpenFOAM to work.

Installing this OpenFOAM is a real pain... I've tried many things and read lots of issues posts here. Encounter all these issues : #337 #343 #344 #348 #333  #288 and more...

Give this a try:
1. _ Download Oracle virtual box version 5.2.8 [https://download.virtualbox.org/virtualbox/5.2.8/](url). Get the VirtualBox-5.2.8-121009-Win.exe    **(5.2 and lower didn't work for me, and not the last one eighter (5.2.12)) 
1.1 _ Install it
2. _ Download OpenFOAM v1706
2.1_ Install it and Uncheck virtualbox
3. _ Make sur to download last version of Butterfly and replace files following this post [https://discourse.ladybug.tools/t/installation-error-openfoam-windows-10/2366/19](url)

**P.S. I was using a VPN, and it was part of many issues. I simply disable it.

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
