### ISSUE TITLE
add_refinementRegion method in "caseFromGeos"

### ISSUE THREAD

**Issue by MingboPeng** [ladybug-tools/butterfly#350]
Hi @mostaphaRoudsari 

**add_refinement_Region** is used in "caseFromGeos", but it should be **add_refinementRegion**.

Thanks,
Mingbo

**Comment by mostaphaRoudsari** [comment]
Hi @MingboPeng! Thank you for the note. This is address in the newer version and is changed to `add_refinement_region`
