### ISSUE TITLE
How to Install Everything and save your thesis

### ISSUE THREAD

**Issue by Slater022** [ladybug-tools/butterfly#352]
After Spending a loooooong weekend having a lot of issue trying to solve the problem for someone in a master thesis I finnally found a solution to install and launch examples files : 

My PC is on Windows 10 all up to date ! 

First : 
Be sure to uninstall everything : 
-Virtual Box
-Docker Toolbox
-Openfoam
-Ubuntu installation ( for those who tried to use the native w10 version ) 
-Rhino
-EVERYTHING

Next : 
Be sure to delete all the folders in Programs Files / Program files x86 for everything in the top list . 
- C:\Program Files (x86)\ESI
- C:\Program Files\McNeel
- C:\Program Files\Oracle\VirtualBox
- C:\Program Files\Rhino 6

( if they don't exist it's good too ) 

Next : 
In C:\Users\<USERNAME> : 
Delete : the folders ".docker" & ".virtualbox"  --> If they don't appear just google how to make hidden folder appear :) 

Next : 
In %appdata% ( type it in the file explorer adress bar )  : 
Delete : 
- GrassHopper
- McNeel 
- DockerToolbox

Restart your PC , do  a Ccleaner cleanup ( that never hurt ) and then : 
Download : 
Docker toolbox : 
https://download.docker.com/win/stable/DockerToolbox.exe
Vbox ( the last version is this one when i'm writing that ) 
https://download.virtualbox.org/virtualbox/5.2.14/VirtualBox-5.2.14-123301-Win.exe
( OpenFoam 1612 ) 
https://sourceforge.net/projects/openfoamplus/files/v1612+/OpenCFD-OpenFOAM4WindowsInstaller_v1612+.exe
Rhino 6 with your licence : 
https://www.rhino3d.com/6
Butterfly 0.0.4 
https://www.food4rhino.com/app/ladybug-tools

When you have everything ready and cleaned you can start.

So : Install everything with Admin rights : ( this order is good :) )

- Install Docker toolbox from the exec file
- Install VirtualBox 
- Install OpenFoam  BUT close the docker toolbox windows DO NOT USE THE ONE INSIDE 
- Install Rhino 6
- Install Butterfly 

Launch VirtualBox as Admin & Rhino 6 As admin too.

Open the example File and put all the toggles at True and you are ready to go if there are No more bugs ! 

Sorry If it's not written properly but it's working on my PC like that :)

Hope it can help you guys !

**Comment by mostaphaRoudsari** [comment]
I'm very sorry that you had to go through all this. Here is hopefully a better solution for the future.

We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
