### ISSUE TITLE
Container id error

### ISSUE THREAD

**Issue by asisnatha** [ladybug-tools/butterfly#355]
I am having an error when i am running the simulation for outdoor flow. All the files have installed correctly. i am using butterfrly 0.0.04 and open foam 1806. Please help
![capture](https://user-images.githubusercontent.com/41608759/43120268-3a17d618-8f37-11e8-8d3e-4a7d89b000de.PNG)

the error says- 
1. Solution exception:Failed to find container id.Do you have the OpenFOAM container running?
You can initiate OpenFOAM container by running start_OF.bat:
C:\Program Files (x86)\ESI\OpenFOAM\1612\\Windows\Scripts\start_OF.bat

**Comment by ymg2007** [comment]
@asisnatha  You should run Docker Terminal firstly。Then run start_OF.bat.

**Comment by asisnatha** [comment]
@ymg2007  how can i do it can u please explain

**Comment by ymg2007** [comment]
@asisnatha  you should update butterfly to the latest version. I am using butterfly 2017-11-21 version.
![butterfly 2017-11-21](https://user-images.githubusercontent.com/24608776/43122568-1ea41186-8f54-11e8-8df6-d8b27c569fa8.jpg)

**Comment by asisnatha** [comment]
@ymg2007 Thanks for the reply. Can you share the link to update to latest version

**Comment by ymg2007** [comment]
@asisnatha  you can download the master zip and connect to butterfly folder. 
https://github.com/ladybug-tools/butterfly
![butterfly zip](https://user-images.githubusercontent.com/24608776/43124297-584e4712-8f59-11e8-9614-c8444cc38ca3.jpg)

**Comment by asisnatha** [comment]
@ymg2007 Thanks for the link... but how can i install the data to butterfly

**Comment by devngc** [comment]
Such issues can be better addressed at the [Forum](https://discourse.ladybug.tools/). You can do
[this](https://discourse.ladybug.tools/t/installation-error-openfoam-windows-10/2366/19?u=devang) get the latest version of Butterfly

**Comment by asisnatha** [comment]
Finally it worked...!!! thanks to all!!

**Comment by devngc** [comment]
Kindly close the issue if it is resolved
