### ISSUE TITLE
NOT ABLE TO VISUALISE REALTIME RESULTS FOR OUTDOOR SIMULATION EXAMPLE FILE

### ISSUE THREAD

**Issue by asisnatha** [ladybug-tools/butterfly#356]
![capture](https://user-images.githubusercontent.com/41608759/43179660-ad6b4770-8ff1-11e8-8329-e3fcf190e2ae.PNG)
![capturea](https://user-images.githubusercontent.com/41608759/43179661-ad9a7fea-8ff1-11e8-9f89-1e1ad4b3eeda.PNG)
![capturefd](https://user-images.githubusercontent.com/41608759/43179662-adcaceb6-8ff1-11e8-9a1e-510684fe6edc.PNG)

**Comment by TheodoreGalanos** [comment]
I wonder if you have turned turbulence off from the recipe. It seems that k (and I imagine epsilon) are not 'valid' values, meaning there are no residuals for it which is the case in laminar cases.

**Comment by devngc** [comment]
Kindly post on the [Forum](https://discourse.ladybug.tools/) if the issue persists

**Comment by asisnatha** [comment]
I am attaching my grasshopper defination
[01_0_outdoor_airflow.zip](https://github.com/ladybug-tools/butterfly/files/2282110/01_0_outdoor_airflow.zip)
I am using open foam 1806
and latest butterfly update

please help

**Comment by Myssterium** [comment]
Hi all,
it seems that I am running into the same problem here. Although butterfly is running the iterations normally, the residual values are both initial and as outcome 0. the vector lengths are also 0 and i am not able to visualise the results. Attached the snapshots. 
Can you please advise?

Thank you
![hack](https://user-images.githubusercontent.com/44472158/47647914-627d5080-db70-11e8-83fd-544119713c5d.PNG)
![capture](https://user-images.githubusercontent.com/44472158/47647921-65784100-db70-11e8-8aa5-d8b6dea945ac.PNG)

**Comment by TheodoreGalanos** [comment]
@Myssterium 

This isn't really a BF bug, this is OF and CFD related. My best guess is the mesh is too rough but it's hard to know without set up. The initial example, which is outdated and I apologize, run for around 560 iterations until it converged. Not sure what changed.

**Comment by mostaphaRoudsari** [comment]
Discourse is a better place to post this question if it is still a problem. Closing the issue here.
