### ISSUE TITLE
Weird results for Outdoor Airflow with OpenFOAM 1712 on Windows 10

### ISSUE THREAD

**Issue by kaymoa** [ladybug-tools/butterfly#357]
Thank you Ladybug peeps for putting together this amazing plugin, great job as always!

I've been struggling last 3 days to get Butterfly up and running. I am using:
Windows 10
Rhino 5 & 6
Grasshopper 0.9.0076
OpenFOAM v1712
Butterfly 0.0.04 (NOV_21_2017)

I started trying OpenFOAM v1612+ however I'd run into this problem:

![1](https://user-images.githubusercontent.com/41993129/43531427-05b2d2d6-95b0-11e8-9a28-993fdaa9c993.PNG)

Same problem persists up to v1712, so I assumed that'd be something with Windows 10, the reason why I installed v1712. I also manually updated Butterfly according to this: [https://discourse.ladybug.tools/t/got-error-while-updating-butterfly/2136/3](url). 

That made me use the new example file for outdoor airflow provided here: [https://discourse.ladybug.tools/t/meshparams-missing/3106](url)

Everything seems to work and I succeed running the simulation in Butterfly. However the results I get visualized in Rhino are nothing simillar to the ones I see on Mostapha's YouTube tutorial, as you see below:

![2](https://user-images.githubusercontent.com/41993129/43533416-0b976e8c-95b5-11e8-868b-6bc10876a317.PNG)
![3](https://user-images.githubusercontent.com/41993129/43532458-6d3ec156-95b2-11e8-85ae-b912b1391eea.JPG)
![4](https://user-images.githubusercontent.com/41993129/43532460-6d5ac888-95b2-11e8-9b85-a2be13afa3e9.JPG)
![5](https://user-images.githubusercontent.com/41993129/43532461-6d74aece-95b2-11e8-9631-89113f677eeb.JPG)

Any ideas what's going wrong and what I should do?
I am pretty nube in CFD and OpenFOAM...

Cheers,
Kay

GH file:

[01_0_outdoor_airflow_1712.zip](https://github.com/ladybug-tools/butterfly/files/2250180/01_0_outdoor_airflow_1712.zip)

**Comment by devngc** [comment]
[This](https://discourse.ladybug.tools/t/no-errors-but-also-no-vectors/3148?u=devang) issue is similar to yours. Offsetting analysis grid from the geometry should help. It is also recommended to post such issues at the forum

**Comment by kaymoa** [comment]
Thank you Devang! I'll give it a try and follow the discussion at the forum.

**Comment by kaymoa** [comment]
Okay, I am waiting to receive my login for LB forum. 
Meanwhile I tried to solutions in the link and still no correct results. I also tried Theodore's definition.
If I understand you correctly, the analysis grid already is offset:
![6](https://user-images.githubusercontent.com/41993129/43594513-ae6e359e-967a-11e8-838d-a790b6230748.JPG)

I also noticed the vectors are rotated in the front view, however parallel in the plan. Could that be something? I don't really know how to go further about this :/

Regards,
Kay

**Comment by devngc** [comment]
did you offset the analysis surface from the buildings?

**Comment by CharlesCollin91** [comment]
I updated the [topic](https://discourse.ladybug.tools/t/no-errors-but-also-no-vectors/3148/23) with solution to the vector direction error. If I remember this is how I solved it.

**Comment by kaymoa** [comment]
Thank you Charles, that did the trick! 👍

**Comment by mostaphaRoudsari** [comment]
It seems the problem is solved here. Thank you @CharlesCollin91!
