### ISSUE TITLE
OpenFoam Installation Issue Machine "default" is already stopped

### ISSUE THREAD

**Issue by slrusso** [ladybug-tools/butterfly#360]
Hi All,

I have installed open foam, and had success in all steps from the installation video. I rand OF_Env_Create before running OpenFoam, and it was successful. However when I fun the actual Open Foam application, the message I receive is as follows:

![openfoam](https://user-images.githubusercontent.com/40572021/45688359-2f7e8080-bb1f-11e8-80b5-638d34a4fcc8.PNG)

I am not a pro computer person, and don't know what the issue is. I am worried that perhaps my company computer defense software may have interfered. as the application OF_Env... and OpenFoam was blocked from running the first few times I tried (even when running as an administrator).

Any thoughts on this would be greatly appreciated!

**Comment by youli123** [comment]
I think you may have a conflict about container. If so ,please open docker and type in：
docker stop $(docker ps -a -q)
and then type in：
docker rm $(docker ps -a -q)

**Comment by chriswmackey** [comment]
You should try using blueCFD and the upcoming release of Butterfly posted at the end of this issue:
https://github.com/ladybug-tools/butterfly/issues/375#issuecomment-462976926
Basically all of our installation headaches have evaporated now that we are using blueCFD.  Once we do the new Butterfly release, we can close out this issue for good.

**Comment by alicialeeinchina** [comment]
hi did you solve this problem? When I opened OF_Env_Create, it showed the same error as yours.

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
