### ISSUE TITLE
docker icon not work

### ISSUE THREAD

**Issue by hamedsangin** [ladybug-tools/butterfly#364]
after instal openfoam 1806 and 1706
no one installed docker 
after I click on "Docker Quickstart Terminal" icon
this happend 
![image](https://user-images.githubusercontent.com/34301946/46667313-2fc9e300-cbd6-11e8-86db-a5a7889f3e5a.png)
in folder i can't find anything 
![image](https://user-images.githubusercontent.com/34301946/46667329-42441c80-cbd6-11e8-8b75-e5bf4c095360.png)

**Comment by jalayshukla** [comment]
you might have "git for windows" box unchecked while installing Docker Toolbox. Run the installation file again and it should resolve this issue.

**Comment by mostaphaRoudsari** [comment]
We just released a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.
