### ISSUE TITLE
OpenFOAM installation problems with Windows 10

### ISSUE THREAD

**Issue by jameswoodall** [ladybug-tools/butterfly#365]
Hi All,

I have been trying to install OpenFOAM v1612 on Windows 10, and cannot explain or troubleshoot the issues I'm having in completing the setup. 
I have followed the installation video posted by Mostapha [here](https://www.youtube.com/watch?v=e90FyyfVbe0&list=PLkjfDmSc5OrxwNaf7xmPJ5lpmF11J7kuE), and yet receive the following error message through OF_Env_Create when going through setup:

> Error checking TLS connection: Host is not running
Starting "default"...
(default) Check network to re-create if needed...
Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm default --type headless failed:
VBoxManage.exe: error: The virtual machine 'default' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\james\.docker\machine\machines\default\default\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine
/root/../c/Users/james:/root/../home/ofuser/workingDir
Error checking TLS connection: Host is not running
Error: Cannot run SSH command: Host "default" is not running

I noted the additional steps necessary in Windows 10 on the github, but Docker Quickstart Terminal is also reporting an error below:

> Starting "default"...
(default) Check network to re-create if needed...
Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm default --type headless failed:
VBoxManage.exe: error: The virtual machine 'default' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\james\.docker\machine\machines\default\default\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine
Looks like something went wrong in step ´Checking status on default´... Press any key to continue...

After running through the closed issues posted via github I have updated and installed the latest VirtualBox version, but this has not solved the issues experienced. Has anyone encountered this issue before? Grateful for any tips on how to resolve.

**Comment by Myssterium** [comment]
Hi,
i am having the same issue. Can someone please post any fixing advice?

thanks

**Comment by chriswmackey** [comment]
You should try using blueCFD and the upcoming release of Butterfly posted at the end of this issue:
https://github.com/ladybug-tools/butterfly/issues/375#issuecomment-462976926
Basically all installation headaches have now evaporated now that we are using blueCFD.  Once we do the new Butterfly release, we can close out this issue for good.

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.

**Comment by dradair** [comment]
It is confirmed  blueCFD doesn't work with Dynamo, so this is still an issue (sorry to cross post on issue). Windows 10, openFOAM v1612, Dynamo Revit (version?)
