### ISSUE TITLE
OpenFoam installation issue windows 10

### ISSUE THREAD

**Issue by enokenful** [ladybug-tools/butterfly#366]
I have completed the OpenFOAM installation but Clicking on the OF_Create_Env throws an error: unable to find the image”of_v1712_centos73:latest” locally 
Prerequisites: Right click on the Oracle Virtual Box shortcut and Open it as Administrator. If default is running, right click over it and select Close   PowerOff to close it
•	Click on the Docker Quickstart terminal shortcut on your desktop to open the terminal. Check for any error messages. If there are no error messages, go to the next step. In the case of errors, please address the particular error, referring to the other FAQs listed here.
•	Type the command, docker images in the terminal.If the output shows no errors, go to the next step. In the case of errors, please address the particular error, referring to the other FAQs listed here.
•	Go to the installation foldere.g./c/Program Files(x86)/ESI/OpenFOAM/v1806/Windows/scripts from the Docker Quickstart terminal using the change directory cd command as below:
cd /c/ 
cd *x86* 
cd ESI/OpenFOAM/v1806/Windows/scripts 
•	Type the command docker load -i of_v1712_centos73.tar in the terminal window - this might take a while to execute, depending on system memory. Please note that of_v1712_centos73.tar refers to version OpenFOAM-v1806. The name of the tar file will change depending on the version.

The terminal window in “Docker” does not load the needed scripts as it can’t seem to find it despite it being in the needed location.

May anyone advise?

Thank you,

**Comment by DambronOlivier** [comment]
Hi @enokenful ,

Go to the directory c/ Program File 86 / ESI / OpenFoam / yourversion/Windows / scripts . Look for the equivalent .tar file .

that is the one you will need to load using : docker load -i .....
sometimes there is the v1712, or it could also be just 1712, read carefully.

Good luck
Olivier

**Comment by fondexx** [comment]
Dear all, I hope you are doing well.


Recently I installed the OpenFoam for windows. I have a problem with the Storage capacity in C: (where the docker runs by default). I need to make the storage of the runing case files in D: how can I do it??

Thanks for your atention


Best regards


David

**Comment by chriswmackey** [comment]
You should try using blueCFD and the upcoming release of Butterfly posted at the end of this issue:
https://github.com/ladybug-tools/butterfly/issues/375#issuecomment-462976926
Basically all installation headaches have now evaporated now that we are using blueCFD.  Once we do the new Butterfly release, we can close out this issue for good.

**Comment by mostaphaRoudsari** [comment]
We just released a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.
