### ISSUE TITLE
Not able to visualise vectors (0 length and 0 residual values)

### ISSUE THREAD

**Issue by Myssterium** [ladybug-tools/butterfly#367]
Hi all,

I posted as a reply to another issue but i think is more appropriate to start a new one.

 After a lot of trial and error I finally managed to make latest version of butterfly working.
 The problem is, while running the recipe, the residual values come out 0, as well as vectors have 0 length subsequently.
 Units of model and scene are meters , so the issue is not scale. 

Can please someone advise?

I am using the example file of outdoor Airflow.

Attached you will find info screenshots related to the issue.

Thank you
![hack](https://user-images.githubusercontent.com/44472158/47648724-c0129c80-db72-11e8-9a9e-4295cfb2077c.PNG)
![capture](https://user-images.githubusercontent.com/44472158/47648725-c0129c80-db72-11e8-847a-0630de6574e5.PNG)

**Comment by sajmy** [comment]
I faced exactly the same issue and I'm not able to solve it for several days

**Comment by mostaphaRoudsari** [comment]
Can you try with the newer version and see if the issue persists?

We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.

**Comment by sajmy** [comment]
Thank you for the suggestion. I hope I'll find time for the new version testing next week. I'll let you know about the result after that.
