### ISSUE TITLE
Running Butterfly in Docker (not OpenFOAM for Windows)

### ISSUE THREAD

**Issue by BingWangUS** [ladybug-tools/butterfly#368]
Hi,

I think this question may fall in the improvement request category. 

After failed installing OpenFOAM for Windows, we would like to try running Butterfly with other OpenFOAM platform. We managed to have a OpenFOAM running in Docker, however, Butterfly cannot connect to it. The issue seems related to some initial setup, shown as below.

Runtime error (IOException): Error: No machine name(s) specified and no "default" machine exists
	
Traceback:
  line 100, in getShellinit, "C:\Users\etrinid\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 112, in getContainerId, "C:\Users\etrinid\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 69, in containerId, "C:\Users\etrinid\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 260, in _RunManager__command, "C:\Users\etrinid\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 215, in command, "C:\Users\etrinid\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 316, in run, "C:\Users\etrinid\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 716, in command, "C:\Users\etrinid\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\case.py"
  line 748, in blockMesh, "C:\Users\etrinid\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\case.py"
  line 47, in script

I cannot attach a image here but I have a cmd with running OpenFOAM opened and we can navigate to the case folder and run blockMesh manually. So the challenge is changing some settings in Butterfly to allow it sending commands.

Anyone have some experience on running Butterfly with other OpenFOAM platform? Thanks.

Best
Bing

**Comment by mostaphaRoudsari** [comment]
We just released a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.
