### ISSUE TITLE
Host is not running - Host "default" is not running

### ISSUE THREAD

**Issue by sinagozashte** [ladybug-tools/butterfly#370]
Hi

I tried to install the latest version of OpenFoam v1612.  I have some problem installing:
1. Error checking TLS connection: Host is not running
2.Error: Cannot run SSH command: Host "default" is not running
3.Failed to open a session for the virtual machine default.
![screenshot 2](https://user-images.githubusercontent.com/44946110/48314996-2fae7000-e5e6-11e8-9203-05dcb52e85d4.png)
![screenshot 3](https://user-images.githubusercontent.com/44946110/48314997-30470680-e5e6-11e8-95f7-a86202bef936.png)
![screenshot 4](https://user-images.githubusercontent.com/44946110/48314998-30470680-e5e6-11e8-8028-1ea9427e6b8c.png)

Although I tried to solve it online, my problem still remains the same. 
Note: My operting system is not "ubuntu" as I showed in the picture, it is "Linux 2.6".

Thank you for helping.

**Comment by Tomalwo** [comment]
I managed to fixed that issue for myself, and have updated the wiki accordingly.

**Comment by mostaphaRoudsari** [comment]
We just posted a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM installation. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.

Feel free to open a new issue if it didn't solve the problem.
