### ISSUE TITLE
OpenFOAM installation issue

### ISSUE THREAD

**Issue by sinagozashte** [ladybug-tools/butterfly#371]
Hi , in the process the of getting my error fixed (issue #370) i have found that in Powershell we can not connect to the URL that is showed in this picture.  
![screenshot 6](https://user-images.githubusercontent.com/44946110/48483584-177a6300-e829-11e8-8cce-5909f0794320.png)

Thank you for helping

**Comment by chriswmackey** [comment]
You should try using blueCFD and the upcoming release of Butterfly posted at the end of this issue:
https://github.com/ladybug-tools/butterfly/issues/375#issuecomment-462976926
Basically all installation headaches have now evaporated now that we are using blueCFD.  Once we do the new Butterfly release, we can close out this issue for good.

**Comment by mostaphaRoudsari** [comment]
We just released a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.
