### ISSUE TITLE
host does not exist

### ISSUE THREAD

**Issue by kerry0011** [ladybug-tools/butterfly#372]
Hi,

I am trying to install OpenFoam v1612+ following the instructions from: [Ladybug-tools](https://www.youtube.com/watch?v=e90FyyfVbe0).  

After installing, I tried to run the OpenFoam Environment but got the error message that says.. Host does not exist: "default"

![openfoam installation error](https://user-images.githubusercontent.com/45544487/49345727-e8fde400-f680-11e8-8954-99166ad9989b.PNG)

What could i have possibly done wrong, or how do i correct this error?

Many thanks.

**Comment by mostaphaRoudsari** [comment]
We just released a new version of Butterfly for Grasshopper that works with BlueCFD-Core and does not need Docker and VM. Try the steps below to install the new version.

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.
