### ISSUE TITLE
Basic N00B issue relating to Docker/Tar 

### ISSUE THREAD

**Issue by False-Design** [ladybug-tools/butterfly#373]
![capture](https://user-images.githubusercontent.com/45545532/49346678-c9b98380-f68d-11e8-83eb-1be08e9519c8.PNG)

Can some please spare 2 minutes to explain how i get from the \c\ to the 'Program Files (x86)' ?

Basically i don't understand the 

cd .. .. 
cd .. ..

part of the the process, i'm guessing its related to the address location on my pc but after trying various formats i continue to get a syntax error. 

So if anyone has any advice that would be great, thank you 

@mostaphaRoudsari

**Comment by chriswmackey** [comment]
@False-Design  ,

I would recommend that you

**Comment by chriswmackey** [comment]
Woops, I accidentally closed the issue.  I meant to say that you should try using blueCFD and the upcoming release of Butterfly posted at the end of this issue:
https://github.com/ladybug-tools/butterfly/issues/375#issuecomment-462976926

Basically all installation headaches have now evaporated now that we are using blueCFD.  Once we do the new Butterfly release, we can close out this issue.

**Comment by False-Design** [comment]
Thanks Chris,

Just installed and its now up and running without any hitches.

Regards

Tom

________________________________

**Comment by mostaphaRoudsari** [comment]
Great to know! Thank you for reporting!
