### ISSUE TITLE
error message in butterfly

### ISSUE THREAD

**Issue by dhurgai** [ladybug-tools/butterfly#378]
Hi
i installed openfoam and butterfly,i open the example file "outdoor airflow" in the block mess following error appears :
0. Runtime error (IOException): 'docker-machine' is not recognized as an internal or external command,
operable program or batch file.
Traceback:
  line 100, in getShellinit, "C:\Users\FHD\AppData\Roaming\McNeel\Rhinoceros\6.0\scripts\butterfly\runmanager.py"
  line 112, in getContainerId, "C:\Users\FHD\AppData\Roaming\McNeel\Rhinoceros\6.0\scripts\butterfly\runmanager.py"
  line 69, in containerId, "C:\Users\FHD\AppData\Roaming\McNeel\Rhinoceros\6.0\scripts\butterfly\runmanager.py"
  line 260, in _RunManager__command, "C:\Users\FHD\AppData\Roaming\McNeel\Rhinoceros\6.0\scripts\butterfly\runmanager.py"
  line 215, in command, "C:\Users\FHD\AppData\Roaming\McNeel\Rhinoceros\6.0\scripts\butterfly\runmanager.py"
  line 316, in run, "C:\Users\FHD\AppData\Roaming\McNeel\Rhinoceros\6.0\scripts\butterfly\runmanager.py"
  line 716, in command, "C:\Users\FHD\AppData\Roaming\McNeel\Rhinoceros\6.0\scripts\butterfly\case.py"
  line 748, in blockMesh, "C:\Users\FHD\AppData\Roaming\McNeel\Rhinoceros\6.0\scripts\butterfly\case.py"
  line 47, in script

![image](https://user-images.githubusercontent.com/47625132/52771773-d0d11a80-305c-11e9-8529-6793393382ef.png)

**Comment by mostaphaRoudsari** [comment]
@dhurgai, The component in your preview is old:

1. Try downloading the newer version 0.0.05 from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools). Use the installer file to remove the old version and install the new one.
2. Install BlueCFD-core following [this link](https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation).
3. Restart both Rhino and Grasshopper and try one of the updated sample files that comes with Butterfly  installation package.
