### ISSUE TITLE
Extremely Large Values in the Results. Can't visualize in ParaView but can visualize fine in Grasshopper

### ISSUE THREAD

**Issue by shu-toz** [ladybug-tools/butterfly#388]
Hi all,

I seem to be getting some really large values in the U-Magnitude.
Even after checking and ensuring there are no points within the butterfly boundary elements.

The results seem to be shown in grasshopper with no problems however, upon closer inspection and auto scaling in paraview, they seem to be extremely high.

any insights would be great

Thanks

![Screenshot_1](https://user-images.githubusercontent.com/29880430/57052646-16040080-6ccc-11e9-8833-99bcbb3cd70b.png)
![Screenshot_2](https://user-images.githubusercontent.com/29880430/57052647-16040080-6ccc-11e9-913f-9952b4f9e1a7.png)

[Atrium Test GH.zip](https://github.com/ladybug-tools/butterfly/files/3136473/Atrium.Test.GH.zip)

**Comment by ymg2007** [comment]
Maybe the time step in paraview is not the latest. Please check it

**Comment by ymg2007** [comment]
I have ran your Atrium test file. It showed the similar result  in Rhino and ParaView
![Velocity in Rhino and ParaView ](https://user-images.githubusercontent.com/24608776/57189151-5322f980-6f3d-11e9-8efb-858fc6958d61.png)

**Comment by shu-toz** [comment]
And you didn't use any other settings than just opening the .foam file???

**Comment by ymg2007** [comment]
Yeah, I just set a slice at Z=1m,and set the custom range 0-7m/s. 
![image](https://user-images.githubusercontent.com/24608776/57189329-fd038580-6f3f-11e9-98cf-f0b4e949e14b.png)

**Comment by shu-toz** [comment]
When I tried to press rescale, nothing happens. The model still shows the smallest value (blue)

Would you be able to send me your .foam file? 
If I can visualise with your .foam file it might mean there's something wrong with my butterfly install

**Comment by ymg2007** [comment]
The .foam file actually is an empty file. 
![image](https://user-images.githubusercontent.com/24608776/57190304-4ad1bb00-6f4b-11e9-9621-c74d4f433e3b.png)
Here is the .foam file. You can test it.
[Atrium_Test.zip](https://github.com/ladybug-tools/butterfly/files/3145244/Atrium_Test.zip)

**Comment by shu-toz** [comment]
Is the zip file your whole analysis?? That's what I meant sorry

**Comment by ymg2007** [comment]
The whole folder is 2.4GB size. I can not upload it to GitHub.Please give me your email. I will send you a share link.

**Comment by shu-toz** [comment]
It's sz@kirk.studio

**Comment by shu-toz** [comment]
> The whole folder is 2.4GB size. I can not upload it to GitHub.Please give me your email. I will send you a share link.

I tried to open the results, I could only see these, no U values...
![Screenshot_1](https://user-images.githubusercontent.com/29880430/57259155-ed9c4d80-70a1-11e9-81f3-75ea26c595b4.png)

**Comment by shu-toz** [comment]
Ah turns out I was taking my slice source from the wrong source.
I had the "InternalMesh" unticked. 
This was the correct source of information for the analysis. 

I can confirm everything is working as it should.
