### ISSUE TITLE
Is rhino run as administrator necessary for latest version of butterfly? 

### ISSUE THREAD

**Issue by kvwxyz1** [ladybug-tools/butterfly#391]
Hello,

Now that butterfly can be run with a windows installer, is it necessary to run rhino as administrator every time butterfly is used? I`m wondering if the following has not been updated since the windows installer became available. It is my understanding that admin was needed to use the virtual machine running the openfoam installer from previous.

ladybug-tools/butterfly
https://github.com/ladybug-tools/butterfly/wiki/2.1.-Getting-started-with-butterfly-in-grasshopper#2-installing-butterfly

“In order to butterfly you must run Rhino as an administrator. If you haven’t run Rhino as administrator, close Rhino and Grasshopper and run Rhino as administrator.”

Thanks, and sorry for cross-posting from ladybug forum.

**Comment by mostaphaRoudsari** [comment]
> Now that butterfly can be run with a windows installer, is it necessary to run rhino as administrator every time butterfly is used?

No. It should run fine also as a normal user. Your understanding is correct. We should update the Wiki.

**Comment by ymg2007** [comment]
Hi,@kvwxyz1  
This wiki is for butterfly Version 0.0.4.
https://github.com/ladybug-tools/butterfly/wiki/2.1.-Getting-started-with-butterfly-in-grasshopper#2-installing-butterfly
The newest version of butterfly is 0.0.5. The version is using BlueCFD as engine not necessary to use virtrual machine. 
https://github.com/ladybug-tools/butterfly/wiki/1.-blueCFD-Core-(OpenFOAM)-Installation.
After you installed butterfly 0.0.5, you juse need to run Rhino as administrator,no need to run BlueCFD as administrator.

**Comment by kvwxyz1** [comment]
Mostapha, ymg2007 
Thank you for your quick response. I have updated the wiki by removing the passage outlined above.
