### ISSUE TITLE
reconstructParMesh bug for butterfly

### ISSUE THREAD

**Issue by ymg2007** [ladybug-tools/butterfly#392]
Rencently I used butterfly for large scale wind simulation. In the process, I found a bug for reconstructParMesh. 
According to butterfly 0.0.05, it used BlueCFD as the engine. After setting the parameter of the snappyHexMesh, It generated a ir.bat file. 

> 
> call "C:\Program Files\blueCFD-Core-2017\setvars.bat"
> set PATH=%HOME%\msys64\usr\bin;%PATH%
> cd c:\Users\21223\butterfly\kaixuanlu
> decomposePar  | tee log\decomposePar.log
> mpirun -np 4 snappyHexMesh  -parallel | tee log\mpirun.log
> reconstructParMesh -constant | tee log\reconstructParMesh.log
> rm -r proc* | tee log\rm.log

The bug happened when reconstructParMesh -constant . reconstructParMesh.log showed 

> /*---------------------------------------------------------------------------*\
> | =========                 |                                                 |
> | \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
> |  \\    /   O peration     | Version:  5.x                                   |
> |   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
> |    \\/     M anipulation  |                                                 |
> \*---------------------------------------------------------------------------*/
> /*   Windows 32 and 64 bit porting by blueCAPE: http://www.bluecape.com.pt   *\
> |  Based on Windows porting (2.0.x v4) by Symscape: http://www.symscape.com   |
> \*---------------------------------------------------------------------------*/
> Build  : 5.x-963176928289
> Exec   : reconstructParMesh -constant
> Date   : Jul 01 2019
> Time   : 09:18:27
> Host   : "DESKTOP-4NPO7P8"
> PID    : 35712
> I/O    : uncollated
> Case   : c:/Users/21223/butterfly/kaixuanlu
> nProcs : 1
> SigFpe : Enabling floating point exception trapping (FOAM_SIGFPE).
> fileModificationChecking : Monitoring run-time modified files using timeStampMaster (fileModificationSkew 10)
> allowSystemOperations : Allowing user-supplied system call operations
> 
> // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
> Create time
> 
> This is an experimental tool which tries to merge individual processor
> meshes back into one master mesh. Use it if the original master mesh has
> been deleted or if the processor meshes have been modified (topology change).
> This tool will write the resulting mesh to a new time step and construct
> xxxxProcAddressing files in the processor meshes so reconstructPar can be
> used to regenerate the fields on the master mesh.
> 
> Not well tested & use at your own risk!
> 
> Merge tolerance : 1e-007
> Write tolerance : 1e-007

Merge tolerance is as same as Write tolerance. So reconstructParMesh  does not work. And then delete all the processor file. 
Please fix this bug.
I have to change writePrecision in controldict from 7 to 8 

writePrecision		8;

**Comment by mostaphaRoudsari** [comment]
Hi @ymg2007 can you clarify the issue again. Is the problem with `writePrecision` being set to 7 by default and you need it to change to 8?

The default is already set to 8 but regardless you can overwrite the value from the Grasshopper interface. You can also change the number in the source code in your installation folder and reload Rhino and Grasshopper.

https://github.com/ladybug-tools/butterfly/blob/8d57b75e2c7752082a0bec774c671e4808612df5/butterfly/controlDict.py#L25

**Comment by ymg2007** [comment]
Thanks for your reply. This method worked nice.
