### ISSUE TITLE
Integration with Blender via Sverchok

### ISSUE THREAD

**Issue by Moult** [ladybug-tools/butterfly#406]
Similar to #64 where this was mentioned previously, given new BIM capabilities given by https://blenderbim.org/ it would be good to integrate ladybug tools with Sverchok.

Ping @bitacovir who originally mentioned this, and @nortikin who is the creator of Sverchok.

**Comment by bitacovir** [comment]
Yes. This would be a great opportunity to incorporate rapid/easy environmental analysis/simulation into one of the stronger 3D software modeler available in the market, with a community of thousand of users and developers and strong support of companies such as Google. In addition, this will extend the alternative FOSS solutions for AEC world. Also, if we consider BlenderBIM addon and Svershock addon, we have already a strong alliance of productivity (BIM) and creativity (Generative design) tools already nested into Blender (with strong realistic rendering engines). Ladybug-tools could be the last member in a holy triumvirate that could make history. :)

**Comment by mostaphaRoudsari** [comment]
Hi @Moult and @bitacovir, I will reply on the osarch forum https://community.osarch.org/discussion/7/aec-free-software-directory#latest as this is a conversation larger than just butterfly. Thank you for reopening this issue. Cheers.

**Comment by mostaphaRoudsari** [comment]
See my reply here: https://community.osarch.org/discussion/comment/765/#Comment_765

Feel free to re-open this issue if you want to continue the conversation here instead of the forum.

**Comment by nortikin** [comment]
sverchok-extra repo would be best-fit. we only use pip to install this lib and providing nodes. but i never used this lib.
