### ISSUE TITLE
Solution exception: WindowsError

### ISSUE THREAD

**Issue by riswurck** [ladybug-tools/butterfly#413]
Dear mr Mostapha,  

I’m trying to run the latest outdoor airflow.gh file and everything seems to be working fine, up till the point where I toggle the blockMesh command which results in the following error:

Solutionexception: WindowsError

I’m running windows 10 pro v 1903,  64 bit operating system with virualisation and hyper V enabled, 

Rhino/ grasshopper 6 commercial
Butterfly 0.0.05
BlueCFD-core 2017, (OpenFoam 5)

All in admin mode:

see also:  attached screenshots incl full error report. 

Do you have any idea what might be causing this and/or how to fix it? 

kind regards, 

Ris. 
![errorreport](https://user-images.githubusercontent.com/72737140/95737082-6e904900-0c87-11eb-9ef6-d24a9b027f62.jpg)

![Core](https://user-images.githubusercontent.com/72737140/95734799-376c6880-0c84-11eb-8cd6-212197ace81a.jpg)
![error](https://user-images.githubusercontent.com/72737140/95734804-3804ff00-0c84-11eb-9be5-9eb9e2b487cf.jpg)
![hyper v](https://user-images.githubusercontent.com/72737140/95734806-389d9580-0c84-11eb-9886-96ae40c20183.jpg)

**Comment by JoshuaB-L** [comment]
Hi Ris,

It looks to me like the full stop your user name as 'ris.WURCK' is causing the issue.

You should keep your user name free of any special characters.

Try making a new new user name without the special character and no blank spaces.

I hope this helps ;)

Josh

**Comment by riswurck** [comment]
Works like a charm, thank you!
