### ISSUE TITLE
butterfly doesn't seem to wake up blueCFD

### ISSUE THREAD

**Issue by xinwei-zhuang** [ladybug-tools/butterfly#416]
I installed butterfly as instructed with blueCFD-Core 2017-2, rhino 6.31, gh 1.0.0007 and butterfly 0.0.05. When install it and run it, I use run as admin for both cfd terminal and rhino.
and

![image](https://user-images.githubusercontent.com/39757009/127625101-2eb6a51a-a861-479c-8fcf-53df1a8b47fc.png)

which I think the cfd is connected with butterfly.
However, the blockmesh does nothing, nothing happens and it yields no error or warning message, but the outputs are null.
any potential solution?
![未命名1627605904](https://user-images.githubusercontent.com/39757009/127624268-6d8caf29-1722-4522-a692-5355ac2d1996.png)

**Comment by JoshuaB-L** [comment]
Hi @vapeurz, you must first set the toggle switch to true on the 'write' blockMesh component. OpenFOAM requires the parameter file (blockMeshDict) to be written in order to run.

Best
Joshua
