### ISSUE TITLE
blockMesh grading factor calculator

### ISSUE THREAD

**Issue by TheodoreGalanos** [ladybug-tools/butterfly#96]
Hi @mostaphaRoudsari 

@bgschaid has developed a nifty utility for calculating the grading factor (and other) of the blockMesh properties. You can find it here http://openfoamwiki.net/index.php/Scripts/blockMesh_grading_calculation. Perhaps we can port it to BF or simply link to it for users. I think it can link nicely to the component we were thinking where grading regions are created through breps, calculating all these data as an output.

What do you think?

Regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
![image](https://user-images.githubusercontent.com/2915573/53279639-15555980-36e0-11e9-9209-1f11b3f01e46.png)
